- src/utils/create.py
> Fixing default permissions in create_player

- evennia/commands/default/building.py
- evennia/commands/default/tests.py
- evennia/locks/lockhandler.py
- evennia/locks/tests.py
- evennia/objects/__init__.py
- evennia/objects/objects.py
- evennia/players/__init__.py
- evennia/scripts/__init__.py
- evennia/server/evennia_launcher.py
- evennia/settings_default.py
- evennia/tests/resources.py
- evennia/typeclasses/tags.py
Some of the commits I was going to roll into the collab PR (but which are generally more useful) are included in this one instead. This includes the ability to check different lock types from one lock string, and the ability to clear tags by category.
However the meat and real concern of this PR is the testing system refactor it includes. This worked fine when played atop the current master but has broken in devel. I'm not certain why. The changes in the testing infrastructure here aren't quite enough to satisfy what I had in mind for #645, but they do take care of some issues-- breaking down each command into its own test, making tests transactional, and better handling of the settings for testing.
The current issues post-rebase are:
1. I'm not certain the paths are being loaded right …
> (WIP) Test improvements, and small things

- evennia/locks/lockfuncs.py
evennia.objects.objects.Object was renamed to
evennia.objects.objects.DefaultObject.
> Fix permissions bug due to class rename.

- evennia/contrib/lineeditor.py
- evennia/contrib/menusystem.py
- evennia/server/tests.py
Makes the line editor and menu system work again. Also forces evennia to initialize when running tests.
> Contrib fixes

- contrib/tutorial_world/build.ev
- src/settings_default.py
Gathered some more typos from settings file. I must have done something wrong because the new commits went together with the previous one (haven't got a grip yet in GitHub pull requests, sorry for that!)
> Tristano typos

- evennia/game_template/web/urls.py
- evennia/web/views.py
Fixes some comments and data presented to the default template for better display and accuracy
> Fixed comment and wording on web templates.

- evennia/commands/default/building.py
- evennia/commands/default/lineeditor.py
- evennia/contrib/__init__.py
- evennia/settings_default.py
- evennia/utils/test_resources.py
- evennia/utils/utils.py
Pulls the line editor into the main area, allows it to be overridden, adds long desc option, and also adds an exit to the test scenarios.
> Collab backports

- evennia/objects/objects.py
The exit command's particular implementation should be overridable without having to replace the cmdset generating function.
> Broke ExitCommand out for easier override.

- evennia/objects/objects.py
Some Google-Style docstrings formatting in `objects.py`.
> `objects.py` docstrings formatting

- evennia/commands/cmdhandler.py
- evennia/commands/cmdparser.py
- evennia/commands/command.py
- evennia/commands/default/building.py
- evennia/comms/channelhandler.py
- evennia/objects/objects.py
- evennia/server/evennia_launcher.py
- evennia/settings_default.py
- evennia/typeclasses/models.py
Allows for users to override name handling, and improves handling of disambiguation functions.
> Dynamic name handling

- evennia/commands/cmdparser.py
- evennia/commands/default/system.py
- evennia/contrib/extended_room.py
- evennia/server/portal/portalsessionhandler.py
- evennia/server/profiling/dummyrunner.py
- evennia/server/profiling/memplot.py
- evennia/utils/ansi.py
- evennia/utils/gametime.py
- evennia/utils/idmapper/models.py
- evennia/utils/prettytable.py
- evennia/utils/txws.py
- evennia/utils/utils.py
Note: / and // have the same behavior in python2.
> Move to python3 style division.

- evennia/commands/command.py
- evennia/commands/default/batchprocess.py
- evennia/commands/default/building.py
- evennia/commands/default/player.py
- evennia/contrib/dice.py
- evennia/contrib/menusystem.py
- evennia/contrib/rplanguage.py
- evennia/server/evennia_launcher.py
- evennia/server/profiling/dummyrunner.py
- evennia/settings_default.py
- evennia/utils/ansi.py
- evennia/utils/evform.py
- evennia/utils/evmenu.py
- evennia/utils/evmore.py
- evennia/utils/evtable.py
- evennia/utils/idmapper/tests.py
- evennia/utils/prettytable.py
- evennia/utils/tests.py
- evennia/utils/txws.py
- evennia/utils/utils.py
Including potential memory reduction due to not created unnecessary lists.
> Use python3 range.

- evennia/commands/cmdset.py
- evennia/contrib/rplanguage.py
- evennia/contrib/tutorial_world/objects.py
- evennia/objects/models.py
- evennia/objects/objects.py
- evennia/scripts/tickerhandler.py
- evennia/server/portal/imc2.py
- evennia/server/sessionhandler.py
- evennia/utils/evtable.py
- evennia/utils/idmapper/manager.py
- evennia/utils/idmapper/models.py
dict.keys() -> list(dict)
dict.values() -> listvalues(dict)
dict.tems() -> listitems(dict)
> Use list* from future.utils.

- evennia/objects/objects.py
> Added connection_time and idle_time properties to DefaultCharacter.

- evennia/commands/default/comms.py
- evennia/players/bots.py
- evennia/server/portal/irc.py
- requirements.txt
Adding the ability to connect to IRC with SSL.
The IRC server I use is SSL-only.
Introduces the dependency of `pyopenssl`.
> Added support for SSL IRC connections.

- evennia/web/webclient/static/webclient/css/webclient.css
- evennia/web/webclient/static/webclient/js/evennia.js
- evennia/web/webclient/static/webclient/js/webclient_gui.js
- evennia/web/webclient/templates/webclient/base.html
- evennia/web/webclient/templates/webclient/webclient.html
This work is in reference to [issue 924](https://github.com/evennia/evennia/issues/924).
- Fixed issue with input area positioning incorrectly on window resize
- Added "use strict" to the scripts, fixed some incorrectly scoped variables as a result.
- Made some CSS changes to improve the input area look & feel
- Changed onKeyDown handler to only do history navigation when the cursor is at the end of the line. (May be less necessary with the following change.)
- Added ability to save the currently editing text in the history stack (so that stray up/down arrows won't kill what you've been typing).
- Added input area resize-on-type functionality.
Make the web client easier to deal with, both from the user and developer perspective.
The AMD loader changes I mentioned on the mailing list will …
> WebClient fixes and enhancements

- evennia/web/webclient/static/webclient/css/webclient.css
- evennia/web/webclient/static/webclient/js/webclient_gui.js
Fixed bug with prompt feature.
Bugfix
Fix for issue #950: Webclient Prompt not displaying correctly
> Fix for issue #950: Webclient Prompt not displaying correctly

- evennia/contrib/chargen.py
Fixes a typo in contrib/chargen.py
> Fix typo in contrib/chargen.py

- evennia/contrib/tests.py
I've never written a unit test before, so I thought I might try to learn how and help out with #1105 . A few things I wasn't sure about, like whether I need to reverse the Mock up stuff of things like different settings variables or gametime.gametime in a tearDown method, or if that's not necessary.
Add unit testing for ExtendedRoom methods.
Part of #1105 task.
> Unit test for ExtendedRoom class

- evennia/utils/utils.py
> Speedup for m_len to not do the regex when not needed

- evennia/players/bots.py
- evennia/server/inputfuncs.py
- evennia/server/portal/irc.py
- evennia/server/portal/rss.py
The implementation of the RSS and IRC bot has been changed to utilise inputfunc to match current Evennia  input conventions. Cleaned up the bot commands no longer in use.
> Current RSS & IRC bot functionality recreated with Inputfunc.

- evennia/commands/default/comms.py
- evennia/commands/default/general.py
- evennia/contrib/tutorial_world/objects.py
- evennia/game_template/server/conf/connection_screens.py
Code cleanup in 4 modules, generally updated depreciated markup per #1212, PEP 8, LGTM alert, typos, redundant code removed.
Improve code readability, upgrade markup, closer PEP 8 compliance
Please advise/comment/update if code style deviates from project style policy.
> Improve code readability, upgrade markup, closer PEP 8 compliance, et al.

- evennia/contrib/barter.py
- evennia/contrib/chargen.py
- evennia/contrib/dice.py
- evennia/contrib/email_login.py
- evennia/contrib/extended_room.py
- evennia/contrib/tests.py
- evennia/contrib/tutorial_world/build.ev
- evennia/contrib/tutorial_world/rooms.py
Markup update and code cleaning to all contribs that contained depreciated markup (8 modules total)
Per #1212, PEP 8, and LGTM alerts, these changes are generally just code cleaning maintenance 
Changed some variable names in some modules for clarity/consistency
> Markup update and code cleaning to all contribs

- evennia/server/initial_setup.py
- evennia/server/portal/irc.py
- evennia/server/portal/ssh.py
- evennia/server/portal/telnet.py
Markup update to files that contained depreciated markup, and and small whitespace and text edits in server/portal 
Per #1212, this last PR should complete the change in all code to the newer markup style.
Precludes the `ext_ansi_map` in `utils/ansi.py` and `IRC_COLOR_MAP` in `server/portal/irc.py`
> Markup update and small edits to server/portal

- evennia/utils/evmenu.py
> EvMenu - Fixed Typo in code causing error.

- evennia/objects/objects.py
Explict bool return for move_to, typo fix
#1176 Target LGTM alerts
> Explict bool return for move_to, typo fix

- evennia/objects/objects.py
The previous fix to buggy sessions had a typo that prevented it from working. Whoops!
Resolve #1221 
Still not sure what the root cause of this issue is, mind you, but it should solve the recursion error in sessionhandler.
> Fix attribute name to resolve recursion error in sessionhandler's get() method.

- evennia/comms/comms.py
- evennia/comms/models.py
- evennia/settings_default.py
While working on channel logging, I noticed the performance of some of my channels was alarmingly bad - upwards of two seconds for the channels with the most subscriptions. By making the 'online' arg for the methods work, it reduced the time for the channel msg methods by a factor of ten.
Increase performance for busy channels by making the online method of channels function.
N/A
> Make offline check in Channel methods function

- evennia/server/server.py
- evennia/server/webserver.py
So issue #1128 is caused by trying to stop the threadpool when there are current requests, so I added a list to the web resource that keeps track of all current pending requests - a list of deferreds from their `notifyFinish` methods. During server shutdown, it checks a new method that returns a DeferredList from this list, which is then required to clear out before the rest of shutdown can proceed. This resolves crashing from long web requests that are currently pending when shutdown starts.
First attempt to resolve #1128 .
Although I'm reasonably certain this works for pending requests that were there at the start of shutdown, I'm less certain this works for requests made during the final `deferLater` call. I **think** it does, from trying to queue in a bunch of requests at the end for …
> Server hang fix (Resolves #1128)

- evennia/commands/cmdhandler.py
This pull request allows to use the 'yield' keyword in commands' `func()` method, in order to:
- Create a delay in seconds.
- Ask for user input.
This feels just neat to newbies who don't necessarily want to manage callbacks right away.  Newbies could enter commands like this:
```python
class CmdTest(Command):
key = "test"
def func(self):
obj = self.caller.search(self.args)
answer = yield "Do you want to go on?"
if answer == "yes":
self.msg("Processing... please wait...")
yield 3 # Wait 3 seconds
self.msg("You've found {}.".format(obj.get_display_name(self.caller)))
else:
self.msg("Stop processing.")
```
> Add cmdhandler's ability to handle 'yield' in command.func()

- evennia/commands/default/help.py
This PR offers to override the `suggestion_cutoff` and `suggestion_maxnum` in help, without re-writing the entire command.  They now are class variables one can either override from a distance, or just redefine in a class, adding the command as usual.
This allows to simply change the number of suggestions, and the accuracy of them.  `suggestion_maxnum` can be set to 0, which means no suggestion is offered at all.
> Allow to change suggestion_cutoff and suggestion_maxnum in help

- evennia/contrib/wilderness.py
Fix for #1362  Wilderness.py item manifest breaks when objects are deleted
Also some minor typo fixes
This should close #1362 (It was fixed according to my testing)
> Fix for #1362 -- contrib.wilderness

- evennia/commands/default/building.py
- evennia/server/evennia_launcher.py
- evennia/server/evennia_runner.py
I didn't open an issue for these, I'm just submitting for pull.
> Docstring typo fixes in evennia_runner and evennia_launcher

- evennia/contrib/extended_room.py
> docs: grammar

- evennia/comms/models.py
Added a check for an object in the subscription handler already being deleted to prevent an `ObjectDoesNotExist` exception being raised.
Hopefully resolves #1378 - pretty sure I introduced this issue with the `obj.is_connected` check for player (soon to be account) subscriptions, without checking if they're deleted.
Closes #1378 with any luck.
> Add check to subscription handler for deleted objects. Fixes #1378

- evennia/commands/default/building.py
Triple double quoted docstrings, comment edit, long lines shortened, some lines joined, removed unused code/redundant parenthesis
More PEP8-compliant code, readability, typo/phrasing edit
devel branch
> PEP8 code cleanup in building.py

- evennia/web/website/templates/website/base.html
- evennia/web/website/templates/website/index.html
Changes class names to reflect changes in Bootstrap
Closes #1424 
Should have caught this earlier - there wasn't any mention in the Bootstrap changes. We're staying on 4.0 now - it's the official release of the Beta, so no more nasty surprises should happen.
> Class name changes to fix #1424

- evennia/web/website/templates/website/_menu.html
- evennia/web/website/templates/website/base.html
The main menu appearing on all Evennia webpages has been moved in a partial template.
This allows for easier customization, editing the menu being a frequent need.
- Evennia Devel
> Separate the web menu in a partial template to easily override

- evennia/settings_default.py
- evennia/web/website/templates/website/base.html
- requirements.txt
- win_requirements.txt
> Sekizai part 2

- evennia/commands/default/building.py
- evennia/commands/default/tests.py
Fixes #1435 by adding typeclass support for the exit to CmdTunnel
@Griatch: I couldn't think of or find a way to double check the typeclass is set correctly in my test - I did test my changes on my own game and it works as intended.
> Added basic Typeclass support to CmdTunnel

- evennia/commands/default/admin.py
This PR fixes #1460 .
I have made the changes discussed over #1460 
Please review.
> Fixed #1460

- evennia/commands/default/building.py
How does this look?
Adds `@tel/loc` and also fixes an unescaped `|` in the error message.
Resolves #1462.
> add `@tel/loc`

- evennia/server/portal/ssh.py
Inform user to also install `pyasn1` for SSH client
Less time spent on debugging ImportError when installing for SSH client
Faster start for those who wants to solve #1427
> Fix ImportError for SSH client

- evennia/server/portal/irc.py
- evennia/server/portal/tests.py
Added Test Cases for:
- IRC formatting
- IRC color codes
Increase code coverage
See the Hacktober Fest Issue: https://github.com/evennia/evennia/issues/1458
> IRC Script Test Case Additions, minor tweak of variable names

- CHANGELOG.md
- evennia/accounts/accounts.py
- evennia/commands/default/account.py
- evennia/commands/default/unloggedin.py
- evennia/contrib/email_login.py
- evennia/utils/spawner.py
A few small text fixes in comments and output strings.
The main motivation for this PR is testing the setup and process - am I doing this correctly?  I'm pushing from the command line, but editing in PyCharm, instead of using the Github web, so this is a new process and learning experience.
PR against develop branch, though these fixes can be applied to master
> Text corrections in comments and strings

- evennia/accounts/tests.py
Accounts modules tests, for https://github.com/evennia/evennia/issues/1458
> adding accounts tests

- evennia/commands/default/building.py
Just quick fix to `@sethome`'s helpfile since its name changed, as well as its usage message.
Just small cleanup.
N/A
> Fix sethome's help file

- evennia/commands/default/admin.py
Changes account.pop() to account.first() - we provide a QuerySet on the search functions, not a list.
Fixes #1514
> Change pop() to first() in commands/default/admin.py

- evennia/objects/objects.py
Fix unused param in at_say that would allow for whisper message to be personalized, as the docstring indicates. Fix broken `str.join()` call.
Fix behavior in at_say to match docstring.
N/A
> Fix msg_receivers to be used

- evennia/web/webclient/static/webclient/js/webclient_gui.js
Step through the help and option popups when closing
Fixes #1531
In the future, we'd handle this differently, but this is a bug with the webclient_gui, it really should have been stepping through the popups.
> Step through help and option popup when closing, fixes #1531

- evennia/comms/channelhandler.py
typo
fixing typos
other issues include there being a typo.
> typo in docstring.

- evennia/contrib/README.md
- evennia/contrib/rpsystem.py
Fixes misspelling and missing periods.
> Minor update

- evennia/commands/default/general.py
> Wrong symbol on line 499

- evennia/utils/dbserialize.py
Replaces `__add__` with `__iadd__` and implements `__add__` with the more expected behavior of not modifying the Attribute in-place and returning a new list object.
Fixes a bug that caused attributes to change when unexpected.
Fixes #1624
> Fix __add__ in SaverList

- evennia/contrib/tutorial_world/objects.py
Simple message formatting fix
You folks have an awesome thing here and I want to help where I can :smile:
> Add space to the tutorial's CrumblingWall message

- evennia/objects/manager.py
Added code to copy tags
Fix oversight #1644
> Update to fix #1644

- bin/unix/evennia.service
Added a sample script for running Evennia as a systemd unit
Using newer distributions, the preferred method of managing system services is through systemd.
The documentation on the wiki would need to be updated to reflect systemd
This PR supersedes  Systemd unit #1317
> Add a systemd unit file using the latest "foreground portal" options

- evennia/prototypes/menus.py
> Fix a single test with try/except limited scope in Py3

- evennia/commands/default/tests.py
- evennia/contrib/tests.py
Very simple fix, one Windows-specific error in unittest.
> Fix two bugs in unittest (one Windows-specific)

- evennia/server/profiling/memplot.py
- evennia/server/profiling/tests.py
Add unit test for memplot, a memory profiling package, along with fixing a few errors in it that were probably holdovers from ages ago.
Increasing test coverage.
N/A
> Add tests for memplot

- evennia/web/webclient/static/webclient/js/plugins/history.js
This corrects the cursor position after a history up/down arrow key has been pressed. 
Regression bug fix for #1686
This will likely need a little extra testing on Edge/IE, since I dont have access to those to test with.
> Fix #1686 cursor placement issues

- evennia/accounts/accounts.py
- evennia/accounts/tests.py
- evennia/commands/default/unloggedin.py
- evennia/comms/comms.py
- evennia/comms/tests.py
- evennia/objects/objects.py
- evennia/objects/tests.py
- evennia/scripts/scripts.py
- evennia/scripts/tests.py
- evennia/server/throttle.py
- evennia/server/validators.py
- evennia/settings_default.py
* Implements username validation through configurable Django validators.
* Accounts now handle reflexive actions.
* Check if a name/IP are banned with a single call to Account.is_banned()
* Get or create a usable guest account (where enabled) with a single call to Account.authenticate_guest()
* Authenticate regular accounts with a single call to Account.authenticate(), which also checks login throttles, banlists and emits events to the security log upon success or failure.
* Usernames have excessive spaces stripped and visually-similar Unicode characters are treated as identical for the purposes of preventing duplicate (or duplicate-looking) usernames via Account.normalize_username().
* Create a fully-functional default Account or Account+Character pair with Account.create()
* Cleans up a …
> Typeclass-based object creation, validation, and authentication

- evennia/commands/default/system.py
Adds restart as alias for reset.
Addresses #1707
> Adds '@restart' as alias for '@reset'

- evennia/server/portal/irc.py
- evennia/settings_default.py
Changes loose to lose where it makes sense
Evennia is awesome and I want to help where I can 😄
> Change loose to lose where appropriate

- evennia/contrib/tutorial_world/build.ev
Fixes some spelling errors in the tutorial build.ev
Evennia is awesome and small changes are easy!
> Correct a few spelling errors in tutorial build.ev

- evennia/settings_default.py
- evennia/web/website/forms.py
- evennia/web/website/templates/website/object_detail.html
- evennia/web/website/urls.py
- evennia/web/website/views.py
* Documents all existing class-based views and forms
* Adds a generic DetailView for Character objects.
* Fixes a cosmetic issue where error messages were not rendering properly.
> Implements generic CharacterDetailView and documents all existing views

- evennia/comms/comms.py
- evennia/web/website/templates/website/_menu.html
- evennia/web/website/templates/website/channel_detail.html
- evennia/web/website/templates/website/channel_list.html
- evennia/web/website/templates/website/help_detail.html
- evennia/web/website/templates/website/help_list.html
- evennia/web/website/templates/website/object_list.html
- evennia/web/website/tests.py
- evennia/web/website/urls.py
- evennia/web/website/views.py
* Adds web_get_*_url methods to Channel objects
* Adds two views to list/detail Channels and their logs (authorization permitting)
* Minor cosmetic fixes.
Provides an alternate interface for reviewing historical logs, and offers better SEO to Evennia sites by making them look more robust and dynamic than they likely are :)
> Adds ChannelViews

- CHANGELOG.md
Updates CHANGELOG to address recent web development efforts.
By request in #1713.
> Updates CHANGELOG to reflect web development efforts

- evennia/web/webclient/static/webclient/js/evennia.js
- evennia/web/website/templates/website/_menu.html
- evennia/web/website/templates/website/help_list.html
- evennia/web/website/templates/website/index.html
- evennia/web/website/templates/website/registration/password_reset_done.html
- evennia/web/website/templates/website/registration/password_reset_form.html
Minor spelling, formatting and layout fixes.
> Minor cosmetic fixes to web templates and assets

- evennia/web/website/templates/website/_menu.html
- evennia/web/website/templates/website/character_list.html
- evennia/web/website/tests.py
- evennia/web/website/urls.py
- evennia/web/website/views.py
Adds a very basic and very generic ListView to display all Character objects for authenticated users.
Also fixes a permissions issue with CharacterDetailView.
Meant to add this in the initial suite but forgot.
> Adds CharacterListView

- evennia/__init__.py
- evennia/server/evennia_launcher.py
Fixes very slight bugs that could prevent an easy freeze (with cx_Freeze or PyInstaller, mostly) of Evennia.
This also fixes an issue with Windows-specific errors.
> Fix slight bugs that prevent a frozen version

- evennia/web/webclient/static/webclient/js/plugins/hotbuttons.js
- evennia/web/webclient/static/webclient/js/plugins/options.js
- evennia/web/webclient/static/webclient/js/plugins/splithandler.js
- evennia/web/webclient/templates/webclient/base.html
Fix various small Webclient bugs, including #1683
Bugs Bad...  Squashed Bugs, Good!
> Some Webclient bugfixes

- evennia/commands/default/building.py
> Correcting typo - "prot" to "proto"

- evennia/contrib/tutorial_world/mob.py
Tutorial. Fixes echo message on lack of argument for mobon command.
> Tutorial. Fixes echo message on lack of argument for mobon command.

- evennia/__init__.py
- evennia/scripts/globalhandler.py
- evennia/settings_default.py
Added a GLOBAL_HANDLER to the Evennia API and a GLOBAL_SCRIPTS dictionary to the settings. The GLOBAL_HANDLER ensures that the specific scripts are launched at startup and always exist if they are called for, while persisting unless stopped directly. 
Although Global Scripts have been around for a long time, there's never been any easy way to group their execution at startup or easily access them. A lot of games will want to use them.
This is basically a mockup to show how the system works and clean it up to even better standards. I figure it won't fly as-is. (though I did test it. it works!)
> Created basic GLOBAL_HANDLER for the Global Script API.

- evennia/objects/objects.py
Just a small addition meant to go along with the existing set of useful overloadable hooks.
Flexibility is good. Since some people (like myself) may be doing weird things with Django or other data sources, having the ability to copy THOSE TOO is most excellent.
Nothing I can think of, apart from it being unlikely to be used by MOST people. There's no pressing need, I just think it fits the philosophy and future building niceties.
> Added at_object_creation_copy hook to DefaultObject.

- evennia/contrib/tests.py
- evennia/utils/tests/test_gametime.py
Adds basic tests for gametime module
I want to confidently make changes to gametime and not worry about breaking anything
> Adding tests for gametime module

- evennia/utils/gametime.py
- evennia/utils/tests/test_gametime.py
Fixing bug detailed in issue #1833 
Bug fixing
> Fixing bug in gametime module

- evennia/web/webclient/static/webclient/css/goldenlayout.css
- evennia/web/webclient/static/webclient/js/plugins/default_out.js
- evennia/web/webclient/static/webclient/js/plugins/goldenlayout.js
This PR adds a small space to each input pane to print out server prompts.
This is a fix for #1858 
Currently this prints the prompt to all input panes, a future enhancement will be needed to add prompts to input panes selectively.
> rework prompts to show up in input panes

- evennia/web/webclient/static/webclient/js/plugins/options.js
I modified line 140:  Replacing the .append with .prepend.  This allows for a running log of previous help requests to be pushed to the bottom.
> Fixed Issue #1789: Help popup in web client not clearing after close

- evennia/accounts/accounts.py
- evennia/accounts/bots.py
- evennia/accounts/manager.py
- evennia/accounts/models.py
- evennia/accounts/tests.py
Changed strings to fstrings where appropriate.
Readability and performance.
> Updated various modules with f-strings.

- evennia/contrib/README.md
> Remove EGI mention in contrib README.md

- evennia/objects/objects.py
> Fix breaking typo in evennia.objects.objects

- evennia/server/evennia_launcher.py
- requirements.txt
- win_requirements.txt
Bug fix release. For more details, see:
https://docs.djangoproject.com/en/2.2/releases/2.2.5/
> Bump min Django version to 2.2.5

- evennia/web/website/views.py
These are not needed in Python 3.
> Remove a couple of lingering u strings

- evennia/commands/default/building.py
- evennia/commands/default/tests.py
> 1928 nested attributes

- evennia/utils/batchprocessors.py
- evennia/utils/tests/test_batchprocessors.py
Unit tests for `evennia/utils/batchprocessors`
Module coverage increased from 40.82% to 97.96%.
> Unit tests for evennia/utils/batchprocessors

- evennia/utils/tests/test_validatorfuncs.py
- evennia/utils/validatorfuncs.py
Tests for evennia/utils/validatorfuncs.
- text()
- color()
- datetime()
- duration()
- future()
- signed_integer()
- positive_integer()
- unsigned_integer()
- boolean()
- timezone()
- email()
- lock()
Coverage on this module increased from 15.87% to 100%.
#1458 Hacktoberfest
> Tests for evennia/utils/validatorfuncs.

- evennia/utils/tests/test_text2html.py
- evennia/utils/text2html.py
Unit tests for evennia/utils/text2html.
Coverage increase from 47.46% to 98.28%.
#1458 Hacktoberfest
> Unit tests for evennia/utils/text2html.

- evennia/utils/tests/test_eveditor.py
Increase coverage of module `evennia/utils/eveditor`
Coverage increased from 58.3% to 68.77%.
#1458 Hacktoberfest
> Increase coverage in evennia/utils/eveditor.

- evennia/scripts/scripts.py
> Task needs to be started if pause() was previously called

- evennia/typeclasses/managers.py
Refactors `get_by_tag` to eliminate usage of chained filters (which work but scale poorly with large tag batches) and implements the ability to search for a number of tags and sort objects by how many tags matched the query.
Addresses #1986
> Typeclass get_by_tag scalability improvements and weighted tag querysets

- evennia/objects/objects.py
- evennia/objects/tests.py
Addresses the issue reported in #1921 and adds a unit test.
> Fixes issue where accountless character creation fails (#1921)

- CHANGELOG.md
- evennia/commands/command.py
- evennia/commands/default/building.py
- evennia/commands/default/muxcommand.py
- evennia/commands/default/system.py
- evennia/commands/default/tests.py
- evennia/typeclasses/managers.py
This moves the logic contained in the default Command and MuxCommand's func() methods to a new
get_command_info() method, and alters func() to call this method by default.
It's one of those tiny adjustments that I feel make for an easier to explore API. With this, you can easily call up debug information on your command in the middle of writing func() without having to dig through potentially multiple layers of super() shenanigans.
Shouldn't be any!
> Segmenting the Command methods better.

- evennia/utils/ansi.py
- evennia/utils/tests/test_utils.py
Same as the last one. Adding f-string and str.format() support to ANSIString.
Making text formatting easier. ANSI is kind of a PITA.
Same as the previous attempt. No support for numeric formatting out of the box, but there's room for improvements.
> Fixing up ANSIString

- evennia/game_template/server/conf/web_plugins.py
- evennia/server/portal/portal.py
> Proxy plugins 2

- evennia/objects/objects.py
- evennia/objects/tests.py
> Validators and normalization of character names

- evennia/comms/channelhandler.py
> comms i18n

- evennia/accounts/accounts.py
- evennia/accounts/bots.py
- evennia/commands/cmdhandler.py
- evennia/commands/cmdsethandler.py
- evennia/help/manager.py
- evennia/locks/lockhandler.py
- evennia/objects/admin.py
- evennia/objects/objects.py
- evennia/utils/utils.py
- evennia/utils/validatorfuncs.py
i18 for accounts and utils
objects and locks are already done
commands and typeclasses are out of scope
jade is doing comms
kovi is doing scripts
this might be about done.
> i18n stuff

- evennia/utils/create.py
documents the return value of evennia.create_account
fixes #2072
> documents return value of create_account

- CHANGELOG.md
- evennia/server/server.py
- evennia/settings_default.py
Pretty brainless inclusion of importlib.import_module(settings.INITIAL_SETUP_MODULE) bada-bing bada-boom.
Do you want to be able to change the initial database setup? I do. Now you can, too. Even if you didn't want to.
> Replaceable init setup

- evennia/objects/manager.py
- evennia/objects/objects.py
Manager.py is returning a couple of querysets instead of lists. Fix for bug #2088
https://github.com/evennia/evennia/issues/2088
> Manager.py is returning a couple of querysets instead of lists. Fix for bug #2088

- evennia/server/portal/portalsessionhandler.py
Tiny little change to the Portal Session Handler to ensure unique IDs.
Want to overload this without having to replace the ENTIRE .connect() method.
> Spinning off sessid generation to make overloading easier.

- evennia/utils/create.py
> added return docstring on create_script

- evennia/typeclasses/tags.py
- evennia/typeclasses/tests.py
Adds Has method to TagHandler
Feature request #2204
> Add 'has' method on TagHandler with a few tests

- evennia/comms/tests.py
Adds tests for Channels wholist property
Increasing test coverage
> Adds tests for Channels wholist property

- evennia/web/webclient/static/webclient/js/plugins/history.js
Fixes the issues with not saving partial text before hitting shift+up/down for history control.
bugfix
fixes #2233
> History bugfix

- evennia/locale/fr/LC_MESSAGES/django.po
I just updated the string in order to fix the translation issue
PS: I don't know why every lines is considered as changed. I checked the file format, it's fine for me.
> [i18n] fix a string from "%" formating to ".format"

- evennia/utils/eveditor.py
Fixes a bug where typing "n" in a room with a "north" exit goes north instead of closing the editor when prompted.
Bug fix
> Increase SaveYesNoCmdSet priority to 150

- docs/source/Setup/Choosing-An-SQL-Server.md
The base documentation covers local server use cases. This PR adds an advanced Postgresql configuration that is useful to support multiple developers and development machines.
To expand the documentation for advanced use cases.
> Add section on usage of a remote Postgres database

- docs/source/Objects.md
In "the process of traversing an exit" section, at_before_leave(obj, destination) was updated to at_object_leave.
Avid participant/follower in the Discord channel (Mysterin) and actively learning as I develop my own Evennia world. Glad to help others learn from things I've figured out along the way!
> Function name updated

- bin/unix/evennia.service
Need to add path of twistd binary to environment when creating service
So we can start evennia upon server  reload
issue #2307
> Adding PATH of twistd binary to environment when creating service

- evennia/utils/utils.py
delay docstring update
The old one had not been properly updated or formatted.
An update to utils.delay's docstring
I had it formatted incorrectly. Also it's return message was incorrect.
> delay docstring update

- CHANGELOG.md
- evennia/utils/tests/test_utils.py
- evennia/utils/utils.py
Adds Oxford comma and removes comma from "X and Y" string syntax
PR requested by Griatch. I personally think it looks nicer this way.
> Update iter_to_string with handling for list size of 2

- evennia/commands/default/cmdset_character.py
- evennia/commands/default/system.py
- evennia/commands/default/tests.py
Allows command line manipulation of evennia tasks (delays).
https://github.com/evennia/evennia/issues/2417
A single unit test in evennia.commands.default.tests.TestHelp fails. Message pattern mismatch.
It may just be something lingering in my evennia migrations folder.
All other unit tests pass using default run level. Tasks should not be affected by run level.
> CmdTasks Created

- evennia/contrib/xyzgrid/README.md
Change path to account for xyzgrid folder in contrib
Fixing the doc
> Fix paths to xyzgrid contrib in documentation

- docs/source/Howto/Starting/Part1/Searching-Things.md
Looked like a simple omission. Spotted by Jarenko.
> Wiki amendment: Appended caller to search method call

- evennia/commands/cmdparser.py
- evennia/settings_default.py
This fixes an issue where multi-match commands aren't passing args correctly due to the MULTIMATCH_REGEX being changed in the develop branch.
This fixes issue #2514.
Also resolves issue #2431.
> Fix multimatch error. Resolves #2514

- docs/source/First-Steps-Coding.md
changed class to match imported name in game_template/commands/command.py
> small change to first steps doc

- evennia/prototypes/prototypes.py
- evennia/prototypes/tests.py
> Issue 2261

- evennia/commands/default/system.py
- evennia/server/sessionhandler.py
- evennia/settings_default.py
- requirements.txt
Addition of BROADCAST_SERVER_RESTART_MESSAGES flag to notify all sessions that the server is restarting.
Resolves #2506
> Addition of BROADCAST_SERVER_RESTART_MESSAGES flag to notify all sessions that the server is restarting.

- docs/source/First-Steps-Coding.md
- evennia/utils/evmenu.py
environments typo corrected.
Fixes #2355
> Fix typo in comment

- docs/source/First-Steps-Coding.md
[Documentation] add triple quotes for docstring
Update documentation
Fixes #2249
> triple quotes

- evennia/utils/dbserialize.py
Added remove() method per https://docs.python.org/3/library/collections.html#collections.deque.remove
I need to remove things from my saved deque.
No issues or discussions for this PR, I can open one if needed.
> Added missing remove() method to _SaverDeque

- evennia/commands/default/admin.py
- Resolves #2595 by removing obsolete string format.
- Added |w to `value` for consistency matching with `CmdBan`.
> Fixed bug with unban command. Resolves #2595

- docs/source/Online-Setup.md
Add Azure App Services and Huawei Cloud to docs as possible hosting providers
Burnt some time in Azure and Huawei, decided to add them in for fun. 
Nil.
> Add Azure App Services and Huawei Cloud to docs

- README.md
> Fix gh-pages README.md link text

- evennia/contrib/game_systems/cooldowns/README.md
- evennia/contrib/game_systems/cooldowns/cooldowns.py
Fix typo in import path in instructions for installing cooldowns contrib.
Keep docs fresh.
> Fix typo in contrib import path.

- evennia/commands/default/tests.py
- evennia/contrib/game_systems/crafting/tests.py
- evennia/objects/manager.py
- evennia/prototypes/prototypes.py
- evennia/utils/test_resources.py
This ensures the prototypes are loaded before being searched
Fix issue
https://github.com/evennia/evennia/issues/2620
> 2620 fix prototype loading

- docs/README.md
Corrected grammar and spelling issues in the ReadMe. Included removing unintentionally repeated words and rewording clunky grammar.
I'm learning Python, played MUDs for the last 20 years, and would like to contribute to this project as my skills increase.
> Made simple grammar and spelling changes.

- evennia/utils/dbserialize.py
- evennia/utils/tests/test_dbserialize.py
Attempts to fix #2519 
Unfortunately, not working still. See review comments.
Hi @Griatch, any suggestion?
> WIP Issue 2519

- evennia/utils/funcparser.py
Fixes #2679
I also corrected the typos in the docstrings I identified in #2675 along with a couple of others I found in the process.
> fix $pron syntax error and docstring typos

- evennia/locale/fr/LC_MESSAGES/django.po
I updated the fr django.po file for evennia
> Develop Updated fr po translation files

- docs/source/Links.md
Minor update to the Links page of the documentation to add a direct link to Designing Virtual Words PDF
Closes #2733
> Links update

- README.md
Replace old link to Google groups with a link to GitHub Discussions
Keep documentation up to date, especially for new members of the community
> Update link to GitHub Discussions

- docs/source/Howtos/Beginner-Tutorial/Part1/Building-Quickstart.md
Fixing multiples typos to conform documentation to 1.0-dev codebase.
Having a better documentation.
> Beginner tutorial typos

- requirements.txt
Editing the requirement.txt file to see if it fix the build in the github action for the documentation part
Fix based on [https://github.com/sphinx-doc/sphinx/issues/10291](https://github.com/sphinx-doc/sphinx/issues/10291)
Might be updated to trigger multiple test on develop branch
> Testing to fix the jinja2 problem

- evennia/accounts/accounts.py
- evennia/commands/default/building.py
- evennia/commands/default/comms.py
- evennia/commands/default/help.py
- evennia/game_template/world/README.md
- evennia/game_template/world/prototypes.py
- evennia/server/sessionhandler.py
- evennia/utils/evmore.py
- evennia/utils/utils.py
All are in comments and docstrings, and none should be controversial
in any way (e.g. British versus American spelling).
Just stretching my legs a little to make sure I have things set up correctly.
> Fix various typos in several files.

- evennia/accounts/accounts.py
- evennia/commands/default/building.py
- evennia/commands/default/comms.py
- evennia/commands/default/help.py
- evennia/game_template/world/README.md
- evennia/game_template/world/prototypes.py
- evennia/server/sessionhandler.py
- evennia/utils/evmore.py
- evennia/utils/utils.py
Is this the right way to handle pull requests to keep the develop branch in sync?
> Typos from master, plus a couple more.

- evennia/utils/tests/test_search.py
Added two unit test cases for search_script_attribute and an additional test case for search_script_tag.
Increase code coverage.
> Unit tests for search_script_attribute and seach_script_tag

- evennia/utils/tests/test_search.py
Added positive and negative test cases for script search by key
Increase code coverage
> Update test_search.py - test script_search by tag

- evennia/commands/default/building.py
Fix `attributes.get` call within a list comprehension to always return a list and prevent tracebacks.
Bug fixing
> Fix @set traceback

- evennia/accounts/accounts.py
- evennia/commands/default/help.py
This PR add couple f-strings prefixes that were missing.
Thank you, regards
> add missing f-strings prefix

- evennia/commands/cmdparser.py
- evennia/commands/command.py
Streamlined the cmdparser so that it has less code when running build_matches, and moved the command matching logic
over to the default Command class using cmd.match(cmdname, include_prefixes: bool).
The default Command class had some unused optimization and caching which are now used properly, accordingly.
When running tests I noticed that this new branch completes `evennia test evennia.commands` about .8 seconds quicker but haven't exactly crunched to figure out if that was just random chance.
Making heavy modifications of the command system easier by exposing more API to within dev reach.
I can now much more easily make a partial match adjustment on Athanor, for instance, using this approach.
All is well!
> Improved CmdParser

- evennia/commands/default/building.py
- evennia/commands/default/tests.py
This PR allow preserve key case when setting them in existing key attributes
close: #2795
> case sensitive set dict keys

- .github/workflows/github_action_test_suite.yml
This PR only enable coverage collection for the combo that's actually used to send stats to coveralls
speedups
> only cover 3.10/sqlite

- evennia/contrib/rpg/buffs/README.md
- evennia/contrib/rpg/buffs/buff.py
- evennia/contrib/rpg/buffs/samplebuffs.py
- evennia/contrib/rpg/buffs/tests.py
Added a few new things to the buff contrib based on feedback:
- A "div" default modifier that divides values
- A buff property that returns the duration remaining
- A buff helper method that alters the buff cache
- A buff attribute interface that allows you to edit existing cache values easily (thanks @aogier!)
- A handler helper method that returns modifier values without applying them (for stat screen readouts and the like)
- Readme and test updates supporting the new features
- General readme improvements
- Misc fixes
Addressing feedback from discord.
> Buff contrib improvements

- evennia/typeclasses/attributes.py
Makes AttributeProperty try using default value as a factory.
Lets dev use lambdas or other callables as default value.
#2697
> AttributeProperty tries spawning child instances of default value (#2697)

- docs/source/Components/Webclient.md
- evennia/commands/default/general.py
- evennia/web/static/webclient/js/plugins/html.js
- evennia/web/static/webclient/js/plugins/text2html.js
- evennia/web/templates/webclient/base.html
Add a pair of plugins to expand the webclient's HTML-message support
The first plugin is just a quicky "html" outfunc message capture plugin, in the same vein as the multimedia plugin.  It allows server-side-generated HTML to be displayed "natively" in a pane.
The second plugin is a rework of my old text2html client-side rendering engine, but this time as a simple text2html outfunc plugin handler.  This allows 1.0-devel to have *some* client-side rendering support for those devs that want to go through the effort of updating their commands to use it instead of the server-side renderer.
> html and text2html plugins

- evennia/objects/objects.py
> Fixed Typo in Object.Search() Comments

- docs/source/Howtos/Add-a-wiki-on-your-website.md
https://demo.django.wiki > https://demo.django-wiki.org
Minor fix.
> Corrected the link to the example wiki

- docs/source/Howtos/Add-a-wiki-on-your-website.md
I went through the process of installing django-wiki onto my own game and cross-checked the guide as I went. Most of it was still good, with just some minor changes to the examples and wording. e.g. taking out the "updated for 0.9" stuff as this is the 1.0 documentation.
The section on permissions, I rewrote to give a more general tone, and also to mention using Django's Groups for the built-in wiki permissions system.
I also removed the "evennia-wiki" section, since the repository in question hasn't been updated for several years and is still on version 0.5 of evennia.
> Update and revision of the wiki guide

- evennia/locale/pt/LC_MESSAGES/django.po
Updates Portuguese translation.
Translation was outdated.
Ref.: #2884
> Portuguese translations updated

- docs/source/Components/Prototypes.md
Fixing the table in markdown on Prototypes.md, enabling sphynx to correctly turn it into an HTML table.
Closes: #2880
> docs: fix markdown syntax for table

- evennia/contrib/game_systems/crafting/crafting.py
- evennia/contrib/game_systems/crafting/tests.py
See https://github.com/evennia/evennia/issues/2703#issuecomment-1264797628
#2703
> fix: Add NonExistentRecipe for gracefully craft an unknown recipe.

- docs/source/Tutorials.md
- Fixes several broken links.
- Updates the link to the MIT introductory python class to use a more recent version of the class that includes video lectures.
> docs: fix broken links in Tutorial

- evennia/utils/logger.py
Changes `self` to `super()`
Bug fixes
Resolves #2875
> Fix logger recursion

- evennia/scripts/tests.py
- evennia/utils/containers.py
- evennia/utils/tests/test_containers.py
See https://github.com/evennia/evennia/issues/2706#issuecomment-1264514914 and https://github.com/evennia/evennia/issues/2706#issuecomment-1264527145
#2706
> fix: Global Scripts loading now catches parse errors

- evennia/web/static/webclient/js/plugins/default_in.js
- evennia/web/static/webclient/js/plugins/goldenlayout.js
- evennia/web/templates/webclient/base.html
- Fixes focus issues when using multiple input tabs
- Cleans up some duplicated event handlers via `once` helper
Fixes #2608, #2216
~~For discussion: in recent times, the trend has been for front-end developers to move away from using Lodash. So why add it as a dependency here? Evennia's webclient is using fairly old-school technologies, like jQuery and Bootstrap. Even [this blog post](https://thejs.dev/jmitchell/its-time-to-let-go-of-lodash-nqc) encouraging developers to let go of lodash acknowledges that "In the world of Bootstrap, jQuery, underscore, prototype and a huge number of other tools, lodash provided a consistent and clear interface. Classes, functional programming, and all the goodness and richness that we take for granted was years away." Therefore, I propose Lodash be added …
> fix: multiple inputs now retain focus correctly

- evennia/utils/tests/test_funcparser.py
Increased test coverage. Based on looking at coveralls coverage for a modified coveralls report based on a local build.
Increase test coverage, uncover bugs, learn more about Evennia.
Will fix bugs found in follow up PR.
> Increase test coverage for funcparse.py, finding bugs in the process

- evennia/typeclasses/managers.py
- evennia/utils/search.py
- evennia/utils/tests/test_search.py
Minor change
Link TypedObjectManager's 'typeclass_search' to allow use in searching objects by typeclass
Allow easy searching of objects by typeclass
https://github.com/evennia/evennia/issues/2933
> Adding search_typeclass to search utils

- evennia/contrib/utils/git_integration/git_integration.py
[v minor change]
Removes unix-dependent library which wasn't being used anyway.
Stop causing suffering for Windows users.
Throws breaking errors in Windows.
> Remove library (unix only, breaks on windows)

- docs/source/Setup/Settings-Default.md
- evennia/settings_default.py
> fix: Remove refs to @tz #2770

- evennia/commands/default/account.py
- evennia/commands/default/building.py
- evennia/commands/default/general.py
- evennia/commands/default/help.py
- evennia/commands/default/muxcommand.py
- evennia/commands/default/system.py
Extend usage of fstrings for consistency and readability.
> Add fstrings

- evennia/utils/funcparser.py
Correction to TypeError exception catching when converting a string to an integer - ValueError instead of TypeError.
Hacktoberfest! And I love games, with MUDs having a special place in my heart. :)
Closes #2911
> chore: convert try/except on TypeError to ValueError

- evennia/utils/utils.py
Re-adds an incidentally lost `hasattr` check before accessing the `category` attribute
bug fixing
closes #2969
> Fix traceback in `at_search_result` with tags

- evennia/commands/command.py
A very small fix of some typos in the `Command` class docstring.
1.0 readiness
> Update Command docstring

- evennia/commands/default/batchprocess.py
Adds usage of fstrings to make the file cleaner to read.
> Extend fstring usage

- evennia/utils/tests/test_funcparser.py
- evennia/utils/verb_conjugation/pronouns.py
- evennia/utils/verb_conjugation/tests.py
Adds some additional tests/parameters to hopefully better catch errors without going so far as testing every possible option.
This PR is being submitted with the expectation that tests will fail, as it will now catch pre-existing issues.
Ultimately, bug fixing.
See #2683 and discussion in #2903
> Expand pronoun tests

- evennia/contrib/rpg/character_creator/tests.py
Updates and corrects broken tests for the character creator contrib
> Fix character creator tests

- docs/source/Howtos/Extending-the-REST-API.md
The REST API is a pretty under-appreciated tool, so I'm giving it some extra attention by writing a guide for it. (Also Wendy asked me to. >.>)
This is a very rough draft, but I don't have a lot of experience writing guides and tutorials so I'd like some input from people on how easy to follow it is before I do formatting and cleanup and all that.
> Add an API guide

- evennia/contrib/game_systems/clothing/README.md
- evennia/contrib/game_systems/clothing/clothing.py
- evennia/contrib/game_systems/clothing/tests.py
This updates the clothing contrib to use new hooks, cleans up some of the code, and updates the `%s` replacement syntax to fstrings, as well as updates the tests a bit.
Additionally, the configuration variables have been made overrideable by game settings rather than requiring you to modify the contrib code.
Preparing for 1.o release
> Update clothing contrib for 1.0

- evennia/contrib/tutorials/evadventure/chargen.py
Tidy up of evadventure chargen module to get it to a runnable state
I think it's a good place for newbies to start so I wanted to make it work
> evAdventure tidy up to get chargen.py working

- docs/source/Howtos/Web-Character-Generation.md
Fixes a link typo and updates to suggest the new auto-character setting instead of multisession mode.
1.0 release prep
> Minor fix to "Web Character Generation"

- evennia/commands/default/general.py
Corrects a comma to a period
Bug fixing
Traceback was reported to discord
> Fix typo in nick command

- evennia/accounts/bots.py
I made a late-stage change to a couple of keyword args when making requested changes, which turns out to have introduced a couple of bugs/regressions from when I'd tested it. This fixes that.
Bug fixing and regretting my poor development practices
> Fix Discord issue involving keyword mismatch

- .github/actions/setup-database.yml
- .github/workflows/github_action_test_suite.yml
Fixing strings that I unintentionally broke.
I was bad and I'm trying to be good.
I didn't know that GitHub expressions required single-quotes for strings and that double-quotes were forbidden. 💦
> Workflow string fixes for GitHub

- evennia/utils/tests/test_search.py
Added positive and negative test case for searching objects by attribute.
Increase code coverage for unit tests.
> Unit Tests for Searching Objects by Attribute

- evennia/commands/default/comms.py
- evennia/server/portal/discord.py
Fixes a bug involving Discord's regular reconnection requests, cleans up a couple docstrings, and gets rid of the factory-based log spam.
Bug fixing and user QoL
> Minor Discord bugfixes and polish

- evennia/commands/default/account.py
- evennia/game_template/world/help_entries.py
Fixes for minor typos in the help.
> Fix help typos

- evennia/contrib/grid/xyzgrid/__init__.py
Moves the `commands` import in init back to the bottom.
Bug fixing
Resolves #3036
> Fix regression bug in xyzgrid contrib

- docs/source/Components/Typeclasses.md
Small grammar fix.
I want the joke to not be hampered by people noticing the error.
> Minor grammar error fix

- docs/source/Setup/Online-Setup.md
> Text update to online setup doc

- evennia/commands/default/admin.py
Replaces the color code that got lost in revision
bug fixing
> Typo correction in CmdPerm

- evennia/accounts/bots.py
+ update legacy SESSIONS reference to SESSIONS_HANDLER
Fixes string appearance on error: 
Into:
Minor change
> Close color code in string to avoid color bleed [tiny fix]

- docs/source/Components/MonitorHandler.md
- docs/source/Components/Objects.md
- docs/source/Components/Scripts.md
- docs/source/Concepts/Messagepath.md
- docs/source/Contribs/Contrib-Crafting.md
- docs/source/Howtos/Evennia-for-roleplaying-sessions.md
- evennia/commands/default/account.py
- evennia/contrib/base_systems/ingame_python/typeclasses.py
- evennia/contrib/game_systems/crafting/crafting.py
Making various small typo fixes
Finding typos in documentation is jarring
N/A
> Fix various typos

- evennia/utils/tests/test_search.py
Added unit tests for searching by typeclass; Rooms and Characters.
Increasing code coverage (https://github.com/evennia/evennia/issues/1458)
> Added two unit tests for searching objects by typeclass

- evennia/typeclasses/tags.py
- evennia/typeclasses/tests.py
Casting tags to strings when using has(), get(), remove(); following what add() already does
Consistency with tag handling
https://github.com/evennia/evennia/issues/3103
> Cast tags to strings

- evennia/utils/logger.py
####Brief overview of PR changes/additions
Add a delete_log_file function for logger.
####Motivation for adding to Evennia
I want to be able to delete logs from within the game, and it seems better to have it in core than a one-off delete command. In particular, I want characters to be able to delete their own roleplay logs. Though that example is a game-specific use.
> Adding a log delete function

- evennia/commands/default/tests.py
- evennia/comms/comms.py
- evennia/comms/tests.py
Ensure nicks created from channel subscriptions match the `@channel` command.
Bug fix.
Resolves #3120
> Fix issue with channel nick aliases.

- evennia/contrib/game_systems/clothing/clothing.py
Fix an f-string to be an f-string (currently it gets caught by .msg_contents which attempts to format it).
For https://github.com/evennia/evennia/issues/3132
> Fix f-string in clothing contrib

- evennia/utils/ansi.py
This reworks the logic for which ANSI colors are chosen as fallbacks when XTERM256 is unavailable. Since Evennia officially supports a minimum Python version of 3.10, this PR also takes advantage of that to use match-case for the logic instead of if-else blocks.
A number of people have expressed dissatisfaction with the ANSI color fallbacks over the past couple of years - most notably with magentas producing blues.
Here is an image of what the current method produces:
As you can see, there are *many* colors that are very much not what you'd expect to get from the original xterm color. `405` being bright blue is a strong example, as is `544` being bright red.
Here is an image of what my new method produces:
While there are still a number of colors that are significantly different from the …
> Replace ANSI color fallback logic

- docs/source/Components/Channels.md
- docs/source/Components/Locks.md
- docs/source/Concepts/Internationalization.md
- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Building-Quickstart.md
- docs/source/Howtos/Implementing-a-game-rule-system.md
Fixes a few typos in the documentation I came across.
It's neat :3
N/A
> Fix a few documentation typos

- docs/source/Howtos/Tutorial-NPC-Merchants.md
Little typo fix.
Make this tutorial work.
https://github.com/evennia/evennia/issues/3172
> Typo fix for doc issue #3172

- evennia/typeclasses/attributes.py
This addresses issue #3160 where the AttributeHandler's all() method isn't handling category filtering like our docs say it does.
Should be self-explanatory.
Closes #3160
> Small fix to the AttributeHandler.all(). Fixes #3160

- evennia/scripts/tickerhandler.py
This rewrites the .save() method on the TickerHandler to be a little bit easier to read, since referencing the store_key values by index is less than ideal.
When attempting to track down the cause for some ticker issues a couple of us have had, I discovered that the save method is retrieving `store_key[1]` as the interval and using it as such - however, `store_key[1]` is actually the stored method.
This change corrects for that and helps prevent further related issues in one fell swoop.
> Minor refactor for TickerHandler.save()

- docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Utilities.md
- evennia/commands/default/system.py
- evennia/utils/tests/test_utils.py
Just adding to the options dictionary for outgoing Py output so that it can be specially highlighted by an eventual Rich usage.
We eventually want to move to Rich. I want to use Rich now in my Project, and this change breaks nothing.
> Py adjustment

- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Tutorial-World.md
Fixes #3190 
I just started going through Evennia today and I am loving what I'm seeing. I ran across this doc issue. I will try and fix more if I run across them :smile:
> fixed broken link to tutorial world build script

- docs/source/Setup/Config-Nginx.md
This PR removes extraneous text from the first code block, as well as rewrites a few phrases for clarity and grammar.
I happened to be in the nginx config page and noticed that at some point it had been edited and some editing artefacts got left in, so I did a quick pass on the whole page to check for any other things and smoothed out some of the wording in the process
> Minor cleanup of nginx docs page

- evennia/contrib/grid/extended_room/extended_room.py
Updates Extended Room look to handle the returned search list and multimatches when looking at objects
Bug fixing
Fixes #3206
> Fix ExtendedRoom look logic

- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.md
Fixed typo on: https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.html
Made change from "is_resting" to "is_sitting".
> Beginner Tutorial Typo Fix

- docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Rules.md
Typo in Tutorial section 3.2.4 about testing
The tutorials have been a huge help to me and I want to make it easier for others to follow along too, especially if they don't have dev experience.
First contribution, apologies if I did something wrong.
> fix: beginner tutorial 3.2.4 "Rules and Dice Rolling" typo

- docs/source/Howtos/Howtos-Overview.md
* Add initial paragraph introduction of this overview page.
* Add page's overview as a TOC sidebar (hopefully, cannot preview production HTML in git editor) 
* Reduce Beginner Tutorial TOC depth to move next page header above the fold.
* Camel Caps for headings
n/a
> docs(how-to): 💄 enhance overview layout

- docs/source/Howtos/Beginner-Tutorial/Beginner-Tutorial-Overview.md
- Heading camel case consistency
- List item punctuation consistency
> docs(beginner-tutorial): :memo: update sidebar

- docs/source/Howtos/Beginner-Tutorial/Beginner-Tutorial-Overview.md
edited copy for syntax, grammar, consistency, economy, and clarity
> docs(beginner-tutorial): :memo: enhance overview text copy

- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Part1-Overview.md
* format sidebar for consistency
* edit prose for syntax, grammar, consistency, economy of word, and clarity
n/a
> docs(beginner-tutorial): :memo: improve part 1 overview

- docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Part3-Overview.md
* format heading
* format sidebar for consistency
n/a
> docs(beginner-tutorial): :memo: update part 3 overview

- docs/source/Howtos/Beginner-Tutorial/Part4/Beginner-Tutorial-Part4-Overview.md
* format heading for consistency
* format sidebar for consistency
n/a
> docs(beginner-tutorial): :memo: update part 4 overview

- docs/source/Howtos/Beginner-Tutorial/Part5/Beginner-Tutorial-Part5-Overview.md
* format heading for consistency
* update sidebar for consistency
n/a
> docs(beginner-tutorial): :memo: update part 5 overview

- docs/source/Howtos/Beginner-Tutorial/Part2/Beginner-Tutorial-Part2-Overview.md
* format sidebar for consistency
* edit text copy for syntax, grammar, economy of word, and clarity
n/a
> docs(beginner-tutorial): :memo: update part 2 overview

- docs/source/Setup/Installation.md
Stack's OCD copy editing...
syntax, grammar, consistency, and formatting
progress, not perfection.
n/a
> docs(installation): :memo: improve text copy

- evennia/commands/default/building.py
> Fixing CmdSetHome DocString Typo

- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Building-Quickstart.md
- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Tutorial-World.md
subject/verb agreement, split infinitives, fix typos, etc. 
Progress, not perfection
> docs(tutorial-building): :memo: revise for clarity and consistency

- evennia/utils/evmenu.py
Adds back initial definition of `helptext` in EvMenu parsing
bug fixing
Closes #3262
> Add back initial `helptext` definition

- evennia/commands/default/building.py
A new method was added to CmdExamine: format_last_login
The "Last Login' key was added to 'objdata' in get_formatted_obj_data with the new method being called.
Addresses #3223 
Not sure what went on with my previous PR. Sorry for the confusion.
> Added 'Last Login' to 'examine' command.

- evennia/objects/objects.py
I was looking through all sessions references and spotted this - I'm pretty sure it's supposed to be recaching to sync up before trying to get again, rather than go into infinite recursions.
Bug Prevention :tm:
> Add recache step to ObjectSessionHandler

- evennia/web/templates/website/homepage/accounts-widget.html
- evennia/web/templates/website/homepage/database-stats-widget.html
- evennia/web/templates/website/homepage/evennia-widget.html
- evennia/web/templates/website/homepage/main-content.html
- evennia/web/templates/website/homepage/recently-connected-widget.html
- evennia/web/templates/website/index.html
**Changes/Additions:**
**Homepage Main Content Refactor: ( Closes #3266 )**
- Extracted the main welcome content from the home page and moved it to a separate template: website/homepage/main-content.html.
- The main template now uses {% include "website/homepage/main-content.html" %} for better modularity and ease of content management.
**Widget-based Design:**
- Introduced a widget-based design for the home page for better separation of concerns and improved readability.
- Extracted account statistics, recently connected users, and database stats into individual widget templates:
- website/homepage/accounts-widget.html
- website/homepage/recently-connected-widget.html
- website/homepage/database-stats-widget.html
- Similarly, the Evennia description at the bottom of the home page has …
> Refactor Home Page Template for Improved Modularity

- evennia/locale/pt/LC_MESSAGES/django.po
3fc913e3c6001c90125ebeebf3e47c8db0aaceed introduced a new string to be translated, as well as changed one other. This commit now updates the Portuguese translation for those two strings.
Keeping the translation up to date.
> Updated Portuguese translation

- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Learning-Typeclasses.md
added terminating `:` to example .at_object_creation method
Progress, not perfection.
close #3293
> docs(Learning-Typeclasses): :memo: fix loop example

- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Learning-Typeclasses.md
use python interpreter to make the get.stats() call outside interactive python mode
Progress, not perfection.
n/a
> docs(Learning-Typeclasses): :memo: fix instructions calling self.get_stats()

- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Learning-Typeclasses.md
correct prose and code example/result
Progress, not perfection
close issue #3299
> fix(Lesson 7.1.2): :bug: correct prose and code example/result

- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.md
missing a period in both code example blocks for do_stand
should I make and close issues for small changes like this? it seems excessive but I will if that's the preference
> docs(Sittable-Object): :memo: add terminal punctuation to do_stand code

- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.md
we have to use the python interpreter to create the armchair as well as sit in it as the command does not yet exist. so, here we just prefix the example code's first two lines with `py`. The third line here is the resulting output from the server. 
> docs(Sittable-Object): fix :bug: armchair creation done in @py

- evennia/contrib/game_systems/clothing/clothing.py
- evennia/contrib/game_systems/clothing/tests.py
Corrects a typo in `CmdWear` that caused the command to check the wrong attribute on clothing.
Also adds a test on clothing limits to prevent future regressions.
Bug fixing
> Fix Clothing contrib ignoring clothing type limits

- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.md
add the missing line numbers to be emphasized
> docs(Sittable-Object): :memo: emphasize and list all uses of `adjective`

- evennia/utils/funcparser.py
- evennia/utils/tests/test_funcparser.py
Adds $your() and $Your() to ACTOR_STANCE_CALLABLES
People are gonna want more of these.
Nah it's really that simple.
> Adds $you() and $your() to the ACTOR_STANCE callables.

- evennia/accounts/accounts.py
- evennia/accounts/tests.py
- evennia/commands/default/account.py
- evennia/objects/objects.py
I feel that there are numerous inefficiencies with the way CmdCharCreate duplicates logic found in DefaultAccount.create_character() and how .create_character() lacks logic found in CmdCharCreate...
So, I decided to refactor the way that character slots and player character creation works, moving most of the logic into DefaultAccount.create_character() and adding some new methods onto DefaultAccount to enable per-account handling of character slots, though the existing settings.MAX_NR_CHARACTERS is still the assumed use case. Now different accounts might have different numbers of slots if people want to override those methods.
New hooks have been added to make it easier to customize the creation of player characters by overloading methods on the Account typeclass.
I believe there are …
> Improved generation of Player Characters using charcreate

- evennia/contrib/tutorials/evadventure/batchscripts/turnbased_combat_demo.py
suggested path variable name is incorrect
borks if used as-is
> fix: correct pathing in header

- evennia/contrib/grid/xyzgrid/launchcmd.py
> Fixing if/else tree in XYZGrid launchcmd

- evennia/server/portal/service.py
I remembered to re-add register_plugins() to the EvenniaPortalService privilegedStartService call.
I goofed in an earlier PR, and am fixing it.
> EvenniaPortalService now launches plugins properly.

- evennia/server/portal/service.py
- evennia/server/portal/webclient_ajax.py
- evennia/settings_default.py
Made the Ajax classes in webclient_ajax now imported by python path so they can be replaced.
Just making it modular same as everything else in Evennia!
> Ajax client classes are now customizable.

- evennia/commands/default/building.py
Adds command prefix for @dig to @tunnel's function
Should fix issue #3374
> Add prefix to CmdTunnel implementation

- evennia/contrib/rpg/character_creator/README.md
- evennia/contrib/rpg/character_creator/character_creator.py
- evennia/contrib/rpg/character_creator/tests.py
Properly updates the `character_creator` contrib for the recent refactor of the character creation system, as well as re-applies the feature respecting START_LOCATION, which has apparently been missing/broken for some time.
The unit tests have also been slightly modified/extended to more accurately match and test the contrib's functionality.
Bug fixing, maintenance
> Update character_creator contrib

- evennia/server/service.py
In the recent server startup refactor, the line initializing the global scripts appears to have been lost. This just adds it back.
Bug fixing
> Start global scripts

- docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Python-classes-and-objects.md
The code block demonstrating the in-game py shell uses the wrong call method for the tutorial `hello_world` method.
> Fix tutorial code block

- evennia/utils/evmenu.py
Adds a check for the screenreader mode flag in the options formatter.
Closes #3392
> Make EvMenu options single-column for screenreader mode

- evennia/contrib/rpg/rpsystem/README.md
- evennia/contrib/rpg/rpsystem/rpsystem.py
- evennia/contrib/rpg/rpsystem/tests.py
Corrects the regex for identifying language keys, as well as expands slightly on speaking in languages in the main documentation and adds a unit test case.
Bug fixing
> Fix rpsystem language syntax to be consistent with documentation

- evennia/contrib/base_systems/godotwebsocket/README.md
- evennia/contrib/base_systems/godotwebsocket/test_webclient.py
- evennia/contrib/base_systems/godotwebsocket/webclient.py
1. Bugfix following latest portal changes with added regression test
2. Update examples in docs as Godot 4 changed how websockets are handled since.
Maintenance
Related to https://github.com/evennia/evennia/issues/3404
Example result
> [Godot] Fix Godot Contrib

- evennia/contrib/rpg/traits/README.md
Corrects the header level for the "Static trait" section, and moves the base Trait block to the beginning of the section where it makes more sense.
Clarity of documentation
> Update traits contrib documetation

- docs/source/Components/OnDemandHandler.md
Small Typo - registes to registers
> Typo correction of OnDemandHandler.md

- docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Utilities.md
General prose editing for punctuation, syntax, grammar, clarity, etc. including fix for #3360.    
closes #3360
> docs(beginner tutorial unit testing): revise prose and bug-fix

- evennia/commands/default/general.py
- evennia/commands/default/tests.py
Fixes an issue that caused a traceback when calling a descendent command with no args. Also adds a unit test specifically on the new class to prevent future issues.
Bug fixing
closes #3486
> Fix traceback in new NumberedTargetCommand

- evennia/commands/default/account.py
- evennia/server/inputfuncs.py
- evennia/server/portal/naws.py
- evennia/server/portal/portalsessionhandler.py
- evennia/server/portal/telnet.py
- evennia/server/serversession.py
It turns out the protocol_flags were being updated with NAWS updates but weren't being saved. I added an exception in the Telnet dataReceived method to handle them and a flag in the options to ignore them if NAWS isn't supported, the flag is set to false, or a size is manually assigned.
Fun problem to work on that involved exploring the bowels of Evennia.
See #3484.
> Automatic Terminal resizing

- evennia/contrib/rpg/character_creator/character_creator.py
I originally neglected to add the callback case for exiting, rather than completing, the chargen menu in the character creator contrib. This adds it.
> Auto-look when quitting the chargen contrib menu

- docs/source/Setup/Online-Setup.md
The Akami/Linode service described is their shared computing suite, which are all VPS. Cloud services are also offered by the company but are not that service.
> Update host provider info

- docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Rules.md
remove preceding . in pathing to example test command
throws error because path is incorrect
> fix(docs): :memo: fix path to test

- evennia/contrib/grid/extended_room/extended_room.py
> (docs): Update extended_room.py

- evennia/contrib/utils/git_integration/git_integration.py
Adds a call to "collectstatic" when your game's files have been updated, so the server will reflect any changes both to the game *and* to the website.
Improved utility
> Update static files from the git integration command when code updates

- evennia/commands/default/building.py
> fix: TagCmd.switch_options was misnamed

- evennia/contrib/game_systems/achievements/README.md
The README has a typo that got missed 😭 
keeping docs good
> Fix typo in Achievements contrib

- evennia/utils/ansi.py
i'll add documentation to https://github.com/evennia/evennia/pull/3579 shortly
> add formatting tags: underline reset tag, italic + reset tag, strikethrough + reset tag

- evennia/utils/tests/test_utils.py
- evennia/utils/utils.py
Modifies the multimatch output to iterate disambiguators only for results with matching names.
It's significantly more complex to make it remove the disambiguator entirely if only one match has a given display name, like the example in the related issue mentioned below, so the output instead looks like this:
```
>>> self.search('red')
More than one match for 'red' (please narrow target):
red box-1
red block-1
red block-2
>>> self.search('red box-1')
red box
```
Bug fixing
Resolves #3570
> Group search multimatches by displayed name

- evennia/utils/evmenu.py
Adds the `kwargs` dict to the generated goto options for option-page navigation.
Bug fixing
Closes #3604
> Pass node kwargs through `@list_node` pages

- docs/source/Coding/Setting-up-PyCharm.md
Rewrites the setting up pycharm with a linux perspective and some new images.
It also details how to get debugging working with linux.
#3431 
The setup process detailed here precedes installing Evennia and uses a virtualenv by default.
I did not test the windows instructions again as I no longer have windows to do it.
> Rewrite doc for pycharm

- evennia/commands/default/system.py
Set the locale to the POSIX default [("C")](https://docs.oracle.com/cd/E19253-01/817-2521/overview-1002/index.html) when running system utility commands like `ps` to ensure standard output.
Use the `server` command without traceback.
Fixes #3638
> Use consistent locale settings for system utilities

- evennia/contrib/rpg/character_creator/character_creator.py
Core character creation error messages are returned as a list, not a string; this changes the error feedback line to properly convert it.
Maintaining UX
> Update error message for Character Creator

- evennia/server/portal/mccp.py
- evennia/server/portal/mssp.py
- evennia/server/portal/mxp.py
- evennia/server/portal/naws.py
- evennia/server/portal/suppress_ga.py
- evennia/server/portal/telnet.py
- evennia/server/portal/telnet_oob.py
- evennia/server/portal/ttype.py
**Brief overview of PR changes/additions**
- Fixes a memory leak in Portal Telnet connections
- Forces weak references on Telnet negotiation objects
- Stops _nop_keepalive LoopingCall on disconnected sessions
**Motivation for adding to Evennia**
Community complaints about memory leaks
**Other info (issues closed, discussion etc)**
https://github.com/evennia/evennia/issues/3225
This is not everything. There is also a leak in AttributeHandler, I believe, but I will separate that. I think these fixes should come 1 at a time for stability.
> fixing memory leaks

- docs/requirements.txt
There is a typo on a comment.
Typos make me sad.
If this PR is accepted, there no longer is this typo on that comment.
> fix (non user-facing) typo

- docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-AI.md
#3659 describes a typo within documentation. PR resolves.
Easy fix
> #3659 Fixing doc typo for beginner tutorial

- evennia/utils/evmore.py
Checks for EvMore object on the account if it's not found, and give a friendlier error if it's not.
Bug fixing.
Closes #3641
> Gracefully handle missing `caller.ndb._more` in `CmdMoreExit`

- evennia/help/tests.py
- evennia/help/utils.py
- Factor out lunr related code from help_search_with_index function
- customize default lunr stemmer to return stemmed and wildcard matches
- unit tests
Fixes issue #3564  where commands with keys beginning with a '*' didn't return help results.
Closes #3564 
This was related to lunr treating '\*' as a special wildcard search character.  Generally you can search for things like 'ex*ine' and it will return 'examine'.
When lunr indexes a document for searching it will stem words so it can match better, from docs `For example, the stem of “searching”, “searched” and “searchable” should be “search”`.  
`*examine` is stemmed to `*examin`.
Then when you search, lunr usually stems that term too, however it **won't stem wildcard searches**.  So the search is for exactly '*examine' and will be a …
> 3564 - Fix leading wildcard help search

- evennia/contrib/rpg/llm/README.md
I fixed the issue with twisted expecting header content to be iterables, but didn't think to review the documentation for examples.
This fixes those examples.
Avoiding confusion
> Update LLM contrib docs

- evennia/utils/dbserialize.py
- evennia/utils/tests/test_dbserialize.py
fix for https://github.com/evennia/evennia/issues/3699
> fix for serializing IntFlag types

- evennia/commands/default/system.py
fix for https://github.com/evennia/evennia/issues/3703
> update about command

- evennia/accounts/bots.py
- evennia/commands/default/comms.py
- Adds logging for situations that otherwise result in silent failures (e.g. connecting to a channel)
- Cleans up channel-loading by using a single function instead of redundant code
- Rewords the link management UI to avoid confusion when deleting links
Improving usability and issue identification for game admins and devs.
> Minor usability improvements for the Discord integration

- evennia/VERSION_REQS.txt
- pyproject.toml
add support for Python 3.13
it's been requested a couple times
fixes https://github.com/evennia/evennia/issues/3715
i've tested it on Windows
suggest merging https://github.com/evennia/evennia/pull/3718 first to ensure a proper upgrade for Windows users
> add support for Python 3.13

- docs/source/Howtos/Tutorial-Persistent-Handler.md
> Minor code typo in handler docs

- evennia/contrib/base_systems/godotwebsocket/README.md
Using localhost causes a significant delay when connecting, using 127.0.0.1 avoids that.
Bugfix
Thanks to CatDadKai for finding out the solution!
> Update godot contrib README.md

- evennia/contrib/base_systems/godotwebsocket/test_text2bbcode.py
- evennia/contrib/base_systems/godotwebsocket/text2bbcode.py
Fixes an improper tag replacement on the contrib side.
Bugfix
It still requires a proper handling of the tags on the client side, which I will add to the docs hopefully soon.
> [Godot Contrib] Fix text2bbcode mxp links

- evennia/scripts/tickerhandler.py
fixes https://github.com/evennia/evennia/issues/3759
> rebuild TickerHandler store_key if it's been serialized

- evennia/commands/command.py
- evennia/commands/default/building.py
- evennia/commands/default/general.py
Fixes the bug mentioned in https://github.com/evennia/evennia/issues/3750. I tested that the `inventory` and `access` commands both work now.
Closes #3750
> Handle missing account in Command

- docs/source/Components/Prototypes.md
> Resolving Syntax Error in Spawner/Prototypes Doc

- evennia/utils/utils.py
Adds proper type hinting for the type that `lazy_property` wraps. Hat tip to @owllex on discord for pointing me in the right direction.
I like type hints :)
> Add type hint to lazy_property to return the underlying type
