evennia/evennia

evennia/commands/default/general.py
This makes it so that iguana does not match this command.
=> The inventory command should not have arguments.

src/objects/admin.py
Admin module's `util` module renamed `utils`. Fixed this, and removed a bunch of old comments that don't appear to apply anymore.
Resolves #668
=> Fixed admin creation of objects. Removed 'code zombies'.

src/commands/default/building.py
TYPO IN COMMENTS: file "/src/commands/default/building.py"
one exact copt of the original
....copT = copY...
copy of the ....
=> TYPO IN COMMENTS of CMD @copy

evennia/commands/default/help.py
Color Cyan the comma in Cmd aliases and suggestions...
When Help lists aliases and suggestions, text is cyan except for aliases and suggested commands (which are white). The separating commas are also white; I've turned them cyan because it's better in separating items from output, and its more consistent.
Nothing big, but something I though worth to implement in my own game.
=> CmdHelp Aesthetic Improvement

evennia/objects/objects.py
Just a typo in the docstring of `create_exit_cmdset()` in module `evennia\objects\objects.py`
=> Typo in create_exit_cmdset docstring.

evennia/commands/default/player.py, evennia/utils/ansi.py
Description of the suggested feature and how it is supposed to work for the admin/end user:
On MUX, one can use %cu, and on Penn, one can use [ansi(u, ... )] to underline selected text. On Evennia, one would theoretically use {u to underline text but it is not implemented.
A list of arguments for why you think this new feature should be included in Evennia:
Feature compatability with MUX/Penn
Ability to create cleaner-looking tables and headers for those not using xterm256.
Extra information, such as requirements or ideas on implementation:
After doing some digging around in the code, I noticed that ANSI_UNDERLINE is defined in utils/ansi.py, but it is never used. All I had to do to get this to work was add the appropriate map to ext_ansi_map on line 255: (r'{u', ANSI_UNDERLINE), and I …
=> Added {u to the ansi parser for underlining text.

evennia/contrib/tutorial_world/rooms.py
tutorial_info is assigned incorrectly in IntroRoom and OutroRoom init.
Instead of setting obj.db.tutorial_info, it sets obj.db_tutorial_info.
=> tutorial_info fix in some tutorial_world.rooms

evennia/players/players.py
This PR addresses Issue #907. The problem was that the `at_look` hook was being called within `at_post_login` with target=None. Modified this to pass in the player's db._playable_characters attribute. 
This revealed a second problem, where the messaging would indicate there were characters, even with an empty character list. This happens because an empty _StorageList cast as boolean evaluates to True. Addressed this by using list() to disconnect the attribute from the db.
=> fixed login error for multisession_mode = 2

evennia/utils/dbserialize.py
There was an error when checking for mysql version, so I removed `self` from `_get_mysql_db_vesion(self)`, as it is not in an object.
File modified: `evennia/utils/dbserialize.py`
=> Removed 'self' from _get_mysql_db_version()

evennia/server/inputfuncs.py
I noticed that channel aliases didn't work while in an ooc state, and it was a typo in the input_func.
=> This fixes channel aliases not working while in an OOC state.

evennia/utils/evtable.py
A player noticed that a table that was formatted by EvTable looked odd, because the align method does not strip out whitespace when wrapping lines, so it was common to have a line start with a whitespace. Now if a 'justify=True' kwarg is passed, the align kwarg will have the text strip out the whitespace on either the left or right border, depending on alignment.
Text formatting for evtable more in line with player expectations.
N/A
=> Add 'justify' kwarg to EvTable

evennia/server/amp.py
My portal logs have been rotating several times a day, and they're mostly filled with lines of amp factory starting and stopping, which happens every time someone connects/disconnects. I found that you can suppress these messages with the 'noisy=False' argument for factories, and I can't really think of a reason why someone would want to see them, since they make the portal logs pretty hard to read.
Make portal logs less spammy and fill up much slower.
N/A
=> Make portal log less noisy

evennia/web/webclient/static/webclient/js/webclient_gui.js
Addresses issue #1109 in a simple and paste-friendly way.  
The user may now paste multiple lines into the web client. Each line will be submitted to evennia in order, regardless of the success of previous lines.
Solve the multiline issue.
This is a bugfix for newline parsing, a new issue is probably appropriate either for this 'fix' or for managing any UX enhancements.
=> Added a line by line command parser in the web client.

evennia/utils/evtable.py
Try to make lstrip and rstrip in EvTable only strip out an offending whitespace character from improper alignment, rather than anything like ANSI codes, newlines, etc.
Attempt to resolve issue #1117 
There might be other stuff going on there, but hopefully this does it. I should have realized that rstrip/lstrip should have been lstrip(" ") and rstrip(" ") originally when that unit test failed, my bad.
=> Change to make strip() in EvTable more specific for fixing align

evennia/server/portal/mxp.py, evennia/utils/text2html.py
Partially addressing issue #1002 - MXP commands and text can now contain a (simple) single quote/apostrophe without quoting issues. 
This works around the problem of having to escape single quotes (apostrophes) in MXP commands or texts, but then requires (simple) double quotes to be escaped.
Caveat - webclient does not expect simple double quotes in MXP commands or text, so this is not a full solution when trying to include a double quote in MXP commands or texts.   Escaping them for webclient may need to be a separate issue or more needs to be done in this PR to address that.
=> MXP tags to use double quote instead of single

evennia/web/webclient/templates/webclient/base.html
This does nothing more than get JQuery over HTTPS.
In the current state (getting JQuery over HTTP), the webclient raises a security error when running on a remote server and accessed in a browser (I encountered this when running Evennia on c9.io). The webclient then fails to load, stating that JQuery was unavailable. This is possible for the user to get around by opting to "run unsafe scripts" in their browser, but that's a suboptimal experience. This is a simple fix with no potential fallout which will make the user experience smoother and improve security.
I think this is a no-brainer, but interested if there's anything that needs to be discussed around it. I didn't upgrade the JQuery version while I was in there because that's outside the focus of this fix, which is simply to make the …
=> Get JQuery over HTTPS to prevent browsers from blocking it

evennia/comms/admin.py, evennia/objects/admin.py, evennia/players/admin.py, evennia/scripts/admin.py, evennia/typeclasses/models.py, evennia/utils/picklefield.py
For some reason, the save_model method in ObjectDB admin doesn't seem to properly assign the typeclass when an object is being created, which causes server errors in creating the object. Additionally, it prevents the server from being reloaded, as ObjectDB.get_all_cached_instances() will fail with an ObjectDB lacking a typeclass and raising an AttributeError when at_server_reload is called.
Prevent nasty errors on attempting to create an object from django admin.
The real question is why the typeclass isn't assigned normally from `TypedObject.__init__`, and I don't have an answer there. I even tried explicitly importing and calling `TypedObject.__init__(obj)` just to see if it would work, and nothing. Apparently the `__class__` has to be specifically assigned here, and I have no idea why.
=> Fix to error on django admin's objectdb creation

evennia/server/portal/portalsessionhandler.py, evennia/settings_default.py
Just an optional setting, MAX_CHAR_LIMIT, that lets you specify the maximum length of any string passed on from the portalsessionhandler to the server, to prevent people from obnoxiously spamming and the like.
Just a little optional anti-troll protection.
I made the default None, which leaves it uncapped, so current behavior is unaffected.
=> Put in check for maximum character size in input strings

evennia/commands/default/general.py
Just a little change to CmdSay and CmdPose to set from_obj to be the caller, so that it can be used in msg_contents/msg.
Allow from_obj to be used for CmdSay and CmdPose to identify the person who executed the command from various hooks, for things like logging and so on.
N/A
=> set the from_obj for CmdSay and CmdPose, so they can be used properly

evennia/commands/default/help.py, evennia/help/manager.py, evennia/help/models.py
Adding support for aliases on help files. This includes giving an AliasHandler to HelpEntry, updating HelpEntryManager to match searches on aliases, and modifying the default help command to display aliases in formatted topic help files.
=> Adding aliases to help entries

evennia/utils/text2html.py
When displaying a line that starts with a single space, the webclient won't render it.
Quick example:
```
>>> me.msg("|_This is a line.")
This is a line.
None
>>> me.msg("|_|_This is a line.")
This is a line.
None
```
The second line with two leading spaces shows both spaces.
The first line with only one leading space won't render that space.
This is an issue only in the webclient. Telnet works fine.
Bugfix.
=> Webclient: don't strip single leading space at the start of a line

evennia/typeclasses/tags.py
`Taghandler.clear()` calls delete on a queryset of Tags, not the through model, resulting in deleting tags for all objects rather than just the object trying to clear the tags. It was easy to miss because of caching making the other tags appear to remain until a `@reload` wiped them.
Fix other tags disappearing if tags are cleared.
N/A
=> Change taghandler clear to delete through models, not Tags themselves

evennia/commands/default/help.py
This display tweak to the help command listing resolves difference in display color markup between Telnet and Webclient where coloration of command in format_help_list was not persisting across new lines.
It adds the `?` alias for the `help` command.
Also updates depreciated markup
Makes display of format_help_list's color markup look consistent between Webclient and Telnet, by ensuring that each line listing commands within a category are colored as intended.
Also, the `?` for help as a default gives a single character shortcut to help.
and lastly, also updates depreciated markup where present.
The call to `fill` to format the lines might not be considering the additional length of the color markup.
=> help command display tweak, adds `?` alias

evennia/contrib/tests.py
Inside of the tests run by `ExtendedRoom`, there's a class that overrides `datetime`, specifically its `fromtimestamp` method.  It's only active during the tests of `ExtendedRoom`.
Tests pass corectly on my system now.
=> Fix #1234: use a mock datetime class to force UTC

evennia/server/amp.py, evennia/server/portal/irc.py, evennia/server/portal/portal.py, evennia/server/portal/ssh.py, evennia/server/portal/ssl.py, evennia/server/portal/telnet.py, evennia/server/portal/telnet_oob.py, evennia/server/portal/ttype.py, evennia/server/serversession.py
1. Markup character now escaped when found at end of line.
1. Propagated disconnect reason further along code chain
1. minor code cleaning and PEP 8 whitespace, comment, docstring edits
1. Escaping end of line markup character avoids collision when concatenated with ASCII reset
1. Propagated disconnect reason further along chain to methods that accept disconnect argument.
1. PEP 8 whitespace more consistent and a possible LGMT alert fix.
=> Markup character at end of line edge case fix

evennia/utils/ansi.py
The `raw` utility in `utils.ansi` now escapes vertical bars in addition to left braces.
=> The ansi.raw utility now escapes vertical bars

evennia/players/bots.py
Indent fixes to address #1258 pulls the code that sends to the channel outward one indent level.
PEP 8 whitespace and docstring edits, 
also addresses an unexpected typo in code that prevented RSS toggle off/delete (Now issue #1263 )
Restore BOT posing IRC /me message to Evennia channel
and some gentle code cleanup.
First fix spotted by @CloudKeeper1 -- under the southern cross he stands.
Second fix spotted by @lmclarke *after* I already commited the typo fix in this PR.
One PR against two issues was unintentional.
=> Indent fixes to address #1258 & Typo #1263

evennia/commands/default/tests.py
The `CommanTest.call()` method performed operations on the received message, like removing end-of-line characters.  This has been removed when no message to compared is specified.
Comparing the received message without modification is necessary when testing an EvTable or something similar.  As it was, testing the presence of a line in a table wasn't possible without a lot of tweaking.  This modification makes sure the returned message is identical to what the caller should perceive (ANSI is removed based on parameters, as usual).
The usual operations are performed if a message to compare is specified in argument, so this modification doesn't break any unittest.
=> Make sure CommandTest.call() returns the received message as is

evennia/contrib/mail.py, evennia/contrib/tests.py
Checks to see if OOC or Puppeting during get_all_mail
Trying to use the mail system fails when OOC
This fixes the test failure and the bug introduced in PR #1262
=> CONTRIB: mail.py: check if ooc or puppeting before finding player object during get_all_mail

evennia/utils/eveditor.py
This PR simply adds automatic escaping of color codes (like `|w` or `{y`) in the EvEditor.
When using the EvEditor in code mode, the fact that Evennia should interpret symbols as color codes is a problem:
```python
character.msg("{word} would sound high and clear.")
```
This is problematic for code, but is it problematic for standard descriptions?  I hesitated a few days before deciding even for room descriptions, it would be more comfortable seeing plainly the color codes, that would make modifications easier (not mentioning more straightforward for us who can't see colors but are willing to use them).  Still, the decision on whether this should be added only for code editing or for any EvEditor isn't mine to make.
=> Add automatic escaping of color codes in the EvEditor

evennia/game_template/commands/command.py
Adjust docstring to resolve #1300
Also realigns code indent to multiple of 4 after `# ` is removed to uncomment
Reference the correct names of BaseCommand methods in the docstring and realign line comments if/when uncommented.
PyCharm line comments/uncomments by adding/removing `# `, so to have correct indentation, the single space was added to the line commented code.
=> Adjust docstring to resolve #1300 in shipped command.py

evennia/utils/idmapper/models.py
CmdServerLoad uses idmapper's `cache_size` function, but that builds a list of classes by name, rather than using their `__dbmodel__` attribute to distinguish them. As a result, there was a duplicate entry for each typeclass with identical values: for example, it would show each of your ObjectDB typeclasses that were currently represented in memory with a number corresponding to the number of ObjectDB instances next to each typeclass, which was misleading. So I just added them by their `__dbmodel__` to the class dict for a better representation.
Have cache_size return a classdict of the `__dbmodel__` class names to be more accurate and readable. It wasn't a big deal, but it was hard to read when you have a lot of different typeclasses.
N/A
=> Remove duplicate entries from CmdServerLoad

evennia/utils/idmapper/manager.py
The manager for the SharedMemoryManager would retrieve any cached instance by ID when used as a RelatedManager, whether the object was related to the instance doing the related query or not. Added a check to see if we have the appropriate field name set in the instance.
Make `object.relatedmanager.get(id=num)` properly raise `DoesNotExist` if the id of the class instance is in our cache, but is not one of our related objects.
While this seems to be working so far, this is dabbling with stuff in django I don't have a very good grasp on, so I'm hoping this actually works properly.
=> Fix SharedMemoryManager to respect foreignkeys for cached instances

evennia/contrib/events/scripts.py, evennia/contrib/events/tests.py
The event task ID was always increasing, which would create long IDs if the system was often used.
With a system that creates lots of chained events, the task ID would have gone up pretty quickly.  Now, IDs can be re-used.  This doesn't create conflicts, as ID are free when the task is executed anyway.
=> Remove the over-incrementing task ID

evennia/settings_default.py, evennia/utils/logger.py
I added a logfile class based on Twisted's rotating logfiles to use for the filehandles for channel logs. I overrode its `rotate()` method in order to write the tail end of the previous log file to the new one after rotation, so that people don't see the channel history vanish whenever it rotates. Size of rotation and how many lines to rotate are both customizable with settings.
To allow for channel logs to rotate rather than ominously growing unbounded in the background, growing ever more powerful, biding their time to strike. Resolves #1253 
I tested this a bit, but since my familiarity with twisted's logging consists of an afternoon of staring at their logging API and tinkering, I'm hoping that I didn't miss anything horrific.
=> LogFile class for rotating channel logs

evennia/server/portal/portal.py
Currently, http logging is still done for every request because while the server uses Evennia's Website class that suppresses these logs unless `DEBUG` is on, the portal does not. This just changes it to use the class as well.
To prevent logging of every single request done to the portal unless DEBUG mode is on so I don't have `http_requests.log.53` waiting for me after a week of not looking.
Other portal versions of the webserver don't use Evennia's classes - for example, the `TCPServer` from portal doesn't use Evennia's threaded webserver variant. Is that an issue at all? I don't really know if that matters at all.
=> Change portal to use Evennia's Website class

evennia/commands/command.py
Currently, get_extra_info will raise an AttributeError if self.obj is defined in the command, but is currently None. This prevents the AttributeError and returns an empty string correctly.
Prevent following traceback:
```
2017-06-01T02:13:04-0400 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/commands/cmdhandler.py", line 597, in cmdhandler
2017-06-01T02:13:04-0400 [AMPProtocol,0,127.0.0.1] [::]     sysarg = yield _SEARCH_AT_RESULT([match[2] for match in matches], caller, query=matches[0][0])
2017-06-01T02:13:04-0400 [AMPProtocol,0,127.0.0.1] [::]   File "/home/tehom/arx/evennia/evennia/utils/utils.py", line 1769, in at_search_result
2017-06-01T02:13:04-0400 [AMPProtocol,0,127.0.0.1] [::]     info=result.get_extra_info(caller)) …
```
=> Prevent AttributeError in multimatch commands when command.obj is None

evennia/server/server.py
Just a quick fix to make it check if `WEBSERVER_ENABLED` during shutdown, so it doesn't get an AttributeError.
Small fix for people who don't have the webserver enabled.
N/A
=> Fix AttributeError when webserver isn't enabled.

evennia/commands/default/player.py, evennia/server/inputfuncs.py, evennia/server/portal/telnet.py
Like it says on the tin; add a MUDPROMPT @option and key the IAC + GA on the end of output blobs off of that @option. :)
Several clients interpret IAC + GA as a linefeed, in order to support MUDs that always end a line with them.  This causes Evennia to spew empty lines everywhere if IAC + GA is always on.  Giving the option to toggle it seems a good solution.
=> Change IAC + GA to key off of MUDPROMPT @option

evennia/server/webserver.py
I was looking over my portal log for any hints about the AMP Errors. No luck there, but I did see a traceback for an errback in `notifyFinish` that had an AttributeError.
Resolves following traceback:
```
2017-06-05T00:17:35-0400 [twisted.internet.defer#critical] Unhandled error in Deferred:
File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/web/http.py", line 1951, in connectionLost
request.connectionLost(reason)
File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/web/http.py", line 1337, in connectionLost
d.errback(reason)
File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
self._startRunCallbacks(fail)
File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/d …
```
=> Fix another AttributeError in errback for #1207.

evennia/__init__.py, evennia/commands/cmdhandler.py, evennia/commands/command.py, evennia/commands/default/tests.py
This pull request adds an `evennia.commands.command.InterruptCommand` exception to terminate commands before the `func()` execution.
For the time being, it's not possible to interrupt a command, let's say, in its `parse` method.  If the parser encounters an error (like a lacking option), `func()` has to handle it.  The `func()` method is called regardless.  This new exception allows to interrupt the command at any moment (in the `parse` method will be the most frequent, I think) before its `func()` is even called.  Its other hooks are therefore not called either.
None
=> Add the InterruptCommand exception to cleanly interrupt commands

evennia/objects/objects.py
`announce_move_from` and `announce_move_to` allow you to pass mappings and other useful kwargs to them in order to override their behavior, but `move_to` itself does not take these arguments and does not pass them to the hooks. I just added them to `move_to` arguments and pass them along to the hooks.
Allow `announce_move_to` and `announce_move_from` hooks to take advantage of their mapping and msg arguments.
N/A
=> Add kwargs for hooks to move_to

evennia/typeclasses/attributes.py
So while playing around with the incredibly weird bug that only seemed to affect me (issue #1173 ), where db_model added to a query with db_attrtype and/or db_category would produce game-stopping lag, I randomly read somewhere about LIKE statements possibly interfering with the performance of an index in some types of databases, and saw django's notes about the __iexact/exact flags using LIKE. So just as a random experiment, I tried adding __iexact to db_model, and the lag issue resolved instantly. Now, this surely seems like a bizarre bug somewhere, and I have zero idea **why** this should work, but here we are.
Fix crippling lag issue that cropped up in one instance of an SQLite database. Still don't know root cause.
Resolves #1173
=> Fix weird lag issue with db_model (Resolves #1173)

evennia/contrib/ingame_python/README.md, evennia/contrib/ingame_python/callbackhandler.py, evennia/contrib/ingame_python/commands.py, evennia/contrib/ingame_python/eventfuncs.py, evennia/contrib/ingame_python/scripts.py, evennia/contrib/ingame_python/tests.py, evennia/contrib/ingame_python/typeclasses.py, evennia/contrib/ingame_python/utils.py
This pull request simply renames the "event" contrib to "ingame_python".
It's probably much clearer this way.  The documentation has also been updated.
For those of you already running the event system in your game, there are a few steps to follow to still have access to your callbacks:
1. Backup your database before merging this pull request (or pulling from master).
2. Before doing an "evennia start", run an "evennia shell" instead.  The path of the event handler has changed, we need to update it, otherwise, nobody will be able to connect.
In the `evennia shell`, enter the following lines:
```python
import evennia
script = evennia.ScriptDB.objects.get(db_key="event_handler")
script.swap_typeclass("evennia.contrib.ingame_python.scripts.EventHandler", run_start_hooks=None)
```
> This …
=> Rename the event system into in-game Python system

evennia/commands/default/tests.py, evennia/contrib/tests.py, evennia/contrib/unixcommand.py
This pull request adds the `UnixCommand` class in `evennia.contrib.unixcommand`.  This class can be used as a parent for commands using Unix syntax.
It can be interesting to have other alternatives for command parsing.  Though the Unix command cannot, obviously, be chosen as a default choice, nor would it be very comfortable for players, it can definitely be useful to builders.
=> Add the UnixCommand, to parse unix-like command options

evennia/contrib/rpsystem.py
In the `evennia/evennia/contrib/rpsystem.py` file, the documentation for the `get` function of the `SdescHandler` class was missing the word `if`.
Clarification of docs for future readers.
=> docs: add missing word

evennia/server/portal/irc.py
Uses IRC \002 (bold) for highlight
Fixes #1367 
You may want to just strip |h instead of using IRC Bold, it's up to style choice.
=> use bold for |h (highlight)

evennia/contrib/wilderness.py
Wilderness.py exits created in wilderness aren't added to 'manifest'
=> Fix for #1364 - Wilderness.py contrib

evennia/web/website/templates/website/evennia_admin.html, evennia/web/website/templates/website/index.html
After being moved to the Devel branch, the new base templates still referenced Players instead of Accounts. This PR fixes those references, adding back in the player list and connected/registered counts.
See above - fixes bug introduced via the merge into Devel
=> Fix Player -> Account in Website Templates

evennia/utils/evmenu.py
Currently, if the start node has options of None then any input causes a "Choose an option or try 'help'." message to display and then ending the menu. This is because EvMenu only supports ending the menu via the _input_parser. We add a check to the goto method which calls to display the starting node and thus allows the menu to exit seamlessly from a single node.
This matter was discussed on length on IRC. Whilst it is agreed that EvMenu should not be used to display a single node where choices are not required of the player, I would suggest that EvMenu should have the option to deal with that eventuality seamlessly regardless. I can envision situation where the starting menu has the option of ending on the first node due to some condition, which if not present would otherwise lead to a …
=> Add EvMenu support for ending on start node.

evennia/commands/default/help.py, evennia/settings_default.py
Adds setting for global CmdHelp's help_more flag, defaulted to True (as before)
Allows toggling help_more flag as a server option within `CmdHelp` without need to overwrite/replace it.
Setting `HELP_MORE` placed near `CLIENT_DEFAULT_WIDTH` and `CLIENT_DEFAULT_HEIGHT`
Although it's easy to alter by overwriting in game, less code change is involved by making it a server option, and other coders have expressed interest in toggling this directly.
=> Add setting for global CmdHelp's help_more flag

evennia/commands/cmdsethandler.py, evennia/settings_default.py
Checks the path of any cmdset that fails to load against a dict in settings that can provide a fallback to try instead, making syntax errors in code much more forgiving.
In Evennia chat, @DamnedScholar brought up that cmdset failure isn't very forgiving - any syntax error in an imported file is likely to wreck the entire process and leave them in a state where they can't even `@reload` the server. While I discussed the workarounds, such as catching exceptions in import statements, this isn't particularly newbie friendly. An automatic fallback of the default cmdsets seemed like a good solution to me.
N/A
=> Create fallback for default cmdsets that fail to load

evennia/server/sessionhandler.py, evennia/utils/ansi.py
This change forces any string objects after encoding to be literal, builtin string objects in order to make sure they are handled properly across the wire.
Fixes #1392
=> Force ANSIString into bytestring before sessions send it over the wire.

evennia/server/evennia_launcher.py
Remove list wrapper from arguments passed to Django from evennia_launcher.py
Fixes #1398, allows multi-database use of Evennia, as well as any other Django command requiring an argument to be passed with "--", for instance, "evennia migrate --database=myapp" or "evennia dbshell --database=myapp"
Closes #1398 
Tested - Does not seem to interfere, but @Griatch, you might want to check my reading - I couldn't find any reason to pass a list to Django.
Unittesting - I'm unsure if we unittest the evennia_launcher and I'm unsure of how to do so - perhaps a future thing to do.
=> Remove list wrapper from value passed to Django

evennia/utils/dbserialize.py
Adds a more clear error message for the edge case of someone removing an Attribute and then modifying the mutable that was stored there.
To prevent confusion in anyone as easily confused as I am.
Resolves #1400
=> Add more clear error message to _SaverMutable

evennia/scripts/taskhandler.py
This bug was due to an unhandled error when removing an object with a permanent delay.
- Fix issue #1407
=> Fix a bug in the permanent delay when the object is destroyed

evennia/commands/default/building.py, evennia/commands/default/tests.py
The default `@destroy` command now displays a confirmation before deleting.  This behavior can be bypassed in several ways.
- Using the `@destroy/force` switch, no confirmation is displayed.
- Modifying the `confirm` class variable in the `CmdDestroy` class, no confirmation will ever be displayed.
Destroying objects has to be efficient, but lots of damage can be done by a change in letter.  The default behavior is a bit more secure: it will display a confirmation message (with the list of keys and IDs) before destroying.  The user has to enter `y` or `yes` in order to continue.  If the user is really sure about what she does, the `/force` switch has been added to the command.  If an admin wishes to go back to the previous behavior (no confirmation), a simple class variable on the command …
=> Add a confirmation to the default @destroy command

evennia/web/website/templates/website/base.html
Uses just-released Bootstrap v4 Beta, instead of the current Alpha version.
The Beta version is even less likely to change than the Alpha was - this doesn't break anything, and the CDN should have these files available for a while.
=> Change Bootstrap Version from Alpha to Beta

evennia/settings_default.py
So, this is embarrassing. I had the `sekizai` app declared in my personal `settings.py` file and didn't even notice that I hadn't added it to `default_settings.py`, which breaks the web site. This fixes that problem.
=> Fixing a mistake.

evennia/commands/default/building.py, evennia/utils/spawner.py
Spawned objects were not getting locations assigned to them.  By default
the locations should be assigned to the caller's location.
Fixes some conditional checks in the spawn builder to add locations to the
spawned item if not using "noloc" switch and "location" is not part of the
prototype.
Potential fix for issue #1455
=> Fix locationless spawned objects

evennia/web/website/templates/website/registration/logged_out.html, evennia/web/website/templates/website/registration/login.html
The login and logout pages of Evennia's website have the wrong css classes - card-block instead of card-body. This causes a lack of spacing around them.
Renames these classes - looks a little nicer than it did before.
=> Rename card-block to card-body on Login and Logout Pages

evennia/contrib/rpsystem.py
The `at_before_say` method does not accept `caller`. At present, it throws an error when you try to speak:
```
Exits: riverport(#7)
say hi
File "/home/amfl/evennia/commands/cmdhandler.py",
line 591, in _run_command
ret = cmd.func()
File "/home/amfl/evennia/contrib/rpsystem.py",
line 861, in func
speech = caller.location.at_before_say(caller, self.args)
TypeError: at_before_say() takes exactly 2 arguments (3 given)
An untrapped error occurred.
```
Introduced in 291fd6fa34080540a57524b619eb8523e283d441
=> RPsystem contrib: Pass at_before_say the corrent number of arguments

evennia/web/webclient/static/webclient/js/webclient_gui.js
In `webclient_gui.js`, we attempt to call the Notification API without checking if it's available. If it's not available, we get a crash as described in #1468.
Fixes #1468, also may add support for browsers/plugins that don't have the Notification object available for whatever reason.
Closes #1468
=> Fix #1468 by checking if Notification is available

evennia/commands/default/tests.py, evennia/utils/test_prototypes.py, evennia/utils/test_resources.py
Tests the @spawn command and its variations.  The test is designed to
aslo check the properties of the spawned objects for some common/obvious
settings.
Test also adds a new prototypes file to be used with the Evennia unit
tester for any tests that require named prototypes.  The spawner test
requires testing named prototypes, so it is added in this change.
Mainly tests the @spawn command and its side-effects.
Test should cover my recent fix for issue #1455
I've also added a change to add new prototype testing files.  I'm not sure if this should go along with this change, or separately.  I could definitely split it up into two separate changes - but since the @spawn testing required this named prototypes, I was hoping to check it in together.
This is for issue #1458
=> Add a @spawn unit test

evennia/commands/default/help.py, evennia/server/inputfuncs.py, evennia/web/webclient/static/webclient/css/webclient.css, evennia/web/webclient/static/webclient/js/webclient_gui.js, evennia/web/webclient/templates/webclient/webclient.html
This change resolves #1448 by hiding the webclient options popup before log-in and after disconnection, in addition it will close the options dialog in the event of a disconnect, to keep things consistent. For optimal UI design, there is no reason to show the button to the user when it provides no functionality.
Included in this commit are two related bug fixes. The first fixes new accounts not having any saved webclient options despite the default settings. This is because nothing is saved to `account.db._saved_webclient_options` until the user makes a change on the other end. This explains why a server might have `helppopup` be a default setting, but it has no effect on the user's end until they toggle the checkmark off, then back on.
The second fix tags "no help entry found" messages …
=> resolve #1448, fix 'no help entry' not popping up in webclient

evennia/utils/evtable.py
There seems to be an issue with adding an empty column (i.e. a column
with empty data) to an EvTable that has already been set up.  It seems
that the column with empty data is added with one extra row than the
rest of the table, and when a new call to add_rows() is made to EvTable,
the data in the column that was added previously is offset by 1.
This change fixes that by calculating the size of the new column to take
into account the headers BEFORE making the calculation on whether to
expand the column to match the table's size or not.
This change just moves calculation of new column size until after the header has been taken into account.
Fixes issue #1479
=> Fix an issue with adding an empty column to an EvTable

evennia/contrib/extended_room.py
Change the desc command in the ExtendedRoom contrib to not use the \@ symbol in the desc command's aliases
Fixes an odd bug around that command - since 0.7 changed commands to ignore prefixes, the command wouldn't ever reach the part that actually relied on the command being called being `detail`.
Fixes an odd behavior on Ainneve's develop branch. :D
=> Fix ExtendedRoom's desc Command

evennia/web/webclient/static/webclient/js/webclient_gui.js
This makes the webclient use the callback-based `Notification.requestPermission(callback)` API instead of the `Promise`-based `Notification.requestPermission().then(callback)` API. The older API is supported in all browsers that support notifications, while the `Promise`-based API is only supported in Chrome 46+, Firefox 47+, and Opera 40+.
Right now, this throws an error in older browsers and Safari, preventing notifications from being displayed.
Extracted from https://github.com/evennia/ainneve/pull/97.
=> Add notification support to a few older browsers and Safari

evennia/commands/default/comms.py, evennia/comms/admin.py
In Evennia 0.7, the admin page for the Channel objects still referred to `db_subscriptions`, which caused a server error.
Fixes 500 error on admin page for channels
Built against master - since it's a bugfix.
=> Fix Admin page for Channel objects

evennia/contrib/README.md, evennia/contrib/tests.py, evennia/contrib/tree_select.py
This contrib module allows developers to generate an EvMenu instance with options sourced from a multi-line string, which supports categories, back and forth menu navigation, option descriptions, and passing selections to custom callbacks. This allows for easier dynamic menus and much faster deployment of simple menu trees which does not require the manual definition of menu nodes and option dictionary-lists.
Adds a new contrib system for easily generating branching menus sourced from strings.
EvMenu is great - it's powerful and flexible - but for simple menu selection tasks, it can be sort of like using a VTOL jet to go to the grocery store. This contrib allows for a much simpler way of using EvMenus for applications where its more powerful features aren't needed.
I workshopped this one …
=> Add simple menu tree selection contrib

evennia/contrib/health_bar.py, evennia/contrib/tests.py
Adds a contrib module, health_bar, which gives developers a highly flexible function for displaying data as filling bars rendered with ANSI or xterm256 color codes.
Everyone loves a health bar! I had bars similar to this in my old learning project, but I was able to make the function that produces them much more stable and flexible this time.
Since this module consists of just one function, I wasn't sure whether it worked best as a contrib or if it could be perhaps integrated into Evennia's utils somewhere.
=> contrib: Health bar

evennia/comms/admin.py
In the admin window, searches wouldn't work for Channels because it was trying to search db_aliases, which didn't exist, rather than db_tags. Viewing any channel would try to go for a few minutes before returning a database lock error if you had large numbers of objects in the database due to not having raw_id fields set, so added those.
Prevent errors from being raised in channel admin.
N/A
=> Fix search and timeout with large database

evennia/settings_default.py
When running the test runner, the automatic check popped up a warning that `TEMPLATE_DEBUG` is deprecated - it's supposed to now be the `debug` field in the `options` dict of `TEMPLATES`. So I just moved it there.
One less deprecation warning.
N/A
=> Replaced deprecated TEMPLATE_DEBUG setting

evennia/objects/objects.py
at_say hindered flexibility in ignoring parameters that could be passed to it. For example, you could not have speaking in a foreign language send different messages to some players and not others. Or send a different room message for a private message, such as 'Bob is seen whispering to Jane.'
Make at_say more flexible.
Did separately from the bug fixes in #1525 since this is a feature/functionality change rather than fix.
=> Flexible at say

evennia/server/portal/telnet.py, evennia/server/session.py, evennia/settings_default.py
This adds a new setting in the default settings.  One can change Telnet default encoding to something other than utf-8.
There's a little issue though (see below).
Some countries are used to a certain encoding, and that's not necessarily utf-8.  Here in France Windows often comes with a latin-1 encoded system and natively supports it, while utf-8 may not be as widely supported.  Changing the default encoding, only for telnet, while allowing full customization per user, would be good in principle.
As it is, the code is pretty straightforward.  However, if you use `@options/save` to change your encoding and save it in the account, then the encoding is dropped the next time you connect or reload the server.  I am not positive why this happens.  The overridden flag still appears in the account …
=> Add a setting to change telnet default encoding

evennia/settings_default.py, evennia/web/webclient/templates/webclient/base.html
Patch for #1421. Allows a proxy port to be used in websocket url setting.
`wss://` support.
=> Update websocket URL so proxy port can be utilized. Resolves #1421.

evennia/utils/logger.py
Adds exception handling to the `log.msg` calls in the logger module.
A first attempt to try to solve the server crash bug that seems somehow related to `log.py`. It started when I switched to using log files for channels, and my theory is it might be related to failing to open a file handle, and then attempting to execute `log.msg` to send the message, which somehow also fails and causes the server to fail with an uncaught exception.
Attempt to fix #1305
=> Attempt to handle any errors in logging.

evennia/commands/default/building.py
Adds support for Channels and Scripts to `@set`, as well as allowing for global-searching via typeclass on non-dbrefs for regular objects.
So I want to gradually do a pass over the existing building commands and extend them to allow users to interact with the AttributeHandlers and TagHandlers of the TypedObjects that currently aren't supported - Channels, Scripts for both, and for Tags that'll include Msg and HelpEntry objects. The latter is more complicated because they don't have all the same fields as TypedObjects, so I started with `@set` first.
Resolves the `@set` part of #1104 
Other thoughts - I'm not sure the most DRY way of implementing the searches for other stuff. It could be added as a mixin on a per-command basis to different ObjManipCommands, but some of those wouldn't make …
=> Allow other typeclasses to have their Attributes set via command.

evennia/typeclasses/admin.py, evennia/utils/picklefield.py
Resolve issue with repeated `repr()` calls on validation errors, making the attributes unusuable. Handle edge case of sets not converting properly with literal_eval in python 2.x - believe it's fixed in 3.x.
Make sure that changing attributes in django admin won't break anything.
Resolves #1521
=> Fix errors in django admin for Attributes

evennia/contrib/extended_room.py
This just extracts the part of return_appearance in ExtendedRoom that would update its current desc if the time/season has change into its own method.
To allow us to update the desc without either copy/pasting the code or discarding the unused result of the return_appearance `super()` call if the string has to be modified, which is usually the case when overriding return_appearance. I didn't really like doing `ExtendedRoom.return_appearance(self, looker)` just to update the seasonal desc.
Also fixed the signature to include `**kwargs` in return_appearance.
=> Refactor ExtendedRoom return_appearance to extract desc update into its own method.

evennia/contrib/ingame_python/typeclasses.py
The `say` event for characters was never called.  Some fixes along that line with a wrong `inherits_from`.
=> [IGPS] Fix mistakes in the say event

evennia/commands/default/admin.py, evennia/commands/default/tests.py
Notes that message will also be sent to unlogged in sessions, not just connected accounts.
Previous wording is slightly misleading, not mentioning unlogged in sessions will also receive the sent message.
For master branch, if this is considered a fix.
If the intended behavior is send only to accounts (all logged in), then the unlogged in sessions need to be removed before sending.  Options could allow accounts, unlogged, or both to target specific sessions instead of all.
=> CmdWall docstring and message correction

evennia/game_template/server/conf/settings.py
In Python 3, docstrings can contain arbitrary values escaped with `\`.  The current setting file (created by default in `mygame/server/conf/settings.py`) also contains the absolute path.  On Windows, this path has `\` in it.  As it is, it raises a `SyntaxError` on reading the docstring.
Fixing this little conflict was trivial and simple.  However there might be some discussion on how to do that:
1. I chose to place a simple `r` in front of the docstring itself to escape the `\` it might contain.
2. We could also require the path be escaped.
I don't suppose it's worth a long debate and that's the only file which gave me this issue, so I don't think a general policy would be required but...
* Evennia on Py3k (note, again, I work on Python 3.6, Python 3.5 doesn't work with Evennia on Windows …
=> Add automatic escaping of the settings docstring for Windows' sake

evennia/server/session.py
Whoops! There was more than one typo in #1555 . The `.attributes.get()` had the default empty dict outside it as a second argument to update, which only accepts one argument. So upon reload every at_sync would fail.
Quick fix to at_sync.
Additional fix to #1555
=> Fix at_sync update call to have right number of arguments.

evennia/comms/models.py, evennia/objects/objects.py
Applies fix described in #1570 as well as adds/fixes a couple other conveniences for people attempting to subscribe objects to channels.
Fixes #1570, better supports inter-object messages through channels
1. Applies fix described in #1570 in `comms/models.py`, changing an if statement so that objects without accounts can still be subscribed to a channel
2. Move options dict being added to kwargs in the DefaultObject `.msg` function to _prior_ to sending over to `at_msg_receive` hook - this allows us to see what channel sent the message in the `at_msg_receive` hook, as seems to have been intended.
3. Add `is_connected` property to DefaultObject, defaulting to `False` or the account's `is_connected` property, if available. This avoids an error message we would get otherwise.
=> Change if statement in comms/models.py to fix #1570

evennia/commands/command.py, evennia/commands/default/building.py, evennia/commands/default/general.py, evennia/commands/default/tests.py, evennia/settings_default.py
If using `@locate` alias and only one object is found and the found object has a location, display that information.
Also, typo fix in CmdWhisper help docstring and access method in Command class
If one wants to know the location of an object, instead of doing a `@find` then an `@examine`, one can just `@locate` the object, provided the search identifier locates a unique object that has a non-None location.
For develop branch, though the feature (and typo fix) can easily be back-ported.
Should a unit test be written for this minor addition?
=> `@locate` alias of CmdFind shows location of find

evennia/commands/default/account.py, evennia/commands/default/admin.py, evennia/commands/default/batchprocess.py, evennia/commands/default/building.py, evennia/commands/default/comms.py, evennia/commands/default/general.py, evennia/commands/default/help.py, evennia/commands/default/muxcommand.py, evennia/commands/default/system.py, evennia/commands/default/tests.py, evennia/comms/models.py, evennia/contrib/extended_room.py
Allowing the shortest unique  text to be used as a command switch.
https://github.com/evennia/evennia/wiki/Coding-FAQ#add-parsing-with-the-to-delimiter
This is easy to add as an optional feature, just like switch abbreviations, so adding it to `CmdTeleport` and `CmdGet` demonstrates how they work to developers creating new commands.
MUX command switch abbreviations is a useful time-saver for users familiar with all the switches of a command. 
An example is typing `@tel/l Griatch` as a shortcut for the `/loc` switch.  
A side effect of this feature is that it relies on the command class knowing which options are valid, which helps organize them, but is purely optional.
The split delimiter is something that several developers have asked about.
Although unit tests were added, to be sure, …
=> Optional features for MuxCommand, added to default Evennia commands

evennia/commands/default/cmdset_unloggedin.py, evennia/commands/default/tests.py, evennia/commands/default/unloggedin.py
Added a simple 'INFO' command which outputs a handful of statistics in MUDINFO 1.1 format. 
This will allow Evennia games (like Arx) to be added to mudconnector and mudstats, who insist on polling a game with MUDINFO to ensure the game is up/running/active.
=> Add support for MUDINFO 1.1 query at login screen

evennia/commands/default/tests.py
So `CommandTest` currently calls all the different hooks, but if `at_pre_cmd` returns a truthy value, command execution is supposed to stop, and currently it just ignores the value. This just is a small fix to that.
Let commands that use `at_pre_cmd` to stop execution pass tests when using `CommandTest`.
N/A
=> Fix CommandTest to stop if at_pre_cmd should stop execution.

evennia/scripts/scripts.py
This tries to fix duplicate script calls that can be caused when the idmapper flush is called on scripts without their `_task` being properly stopped.
Avoid `at_repeat` being called more than once on a script after a cache flush.
Fixes #1519
=> Fix duplicate script calls

evennia/comms/comms.py
I was trying to figure out why there was so much lag in channels on peak times, and I realized that the mutelist property I created was being retrieved inside a loop. Whoops!
Reduce execution time for high-traffic channels by a large amount.
The amount of horsepower it needed for channels during peak hours could have been a contributing factor in #1305 - hopefully it'll be reduced a bit now.
=> Move query/unpickling out of loop for mutelist.

evennia/typeclasses/managers.py
It dawned on me that annotate wasn't defined as a manager method to add the appropriate `db_typeclass_path` filtering, so I went ahead and added that.
Edit: Also added values and values_list, for the same reason.
To allow `TypeclassManager.objects` methods `.annotate`, `.values`, and `.values_list` to filter by the corresponding typeclass path automatically, as expected.
I'll need to edit the [object search tutorial](https://github.com/evennia/evennia/wiki/Tutorial:-Searching-For-Objects) to fix that bit about annotations not playing well with typeclass paths. Whoops.
=> Fix TypeclassManager filtering for annotate, values, values_list methods

Dockerfile
Allows for tls on telent out of the box when starting up a docker container
Addresses feature request in issue #1637
Installs py2-openssl as well as cryptography, pyasn1, and service_identity
Allows for tls on telent out of the box when starting up a docker container
=> Python depends for telnet tls

evennia/commands/cmdset.py
Changes an `except TypeError ` to a `callable()` check in the `_instantiate()` function of `cmdset.py`.
`TypeError`s can be thrown for many different reasons; expecting them to always come from calling an uncallable object should be considered a bug. Python has a built-in function, `callable()`, to test whether an object can be invoked. If a class's `__init__` method unexpectedly throws a `TypeError`, an extremely cryptic exception about unbound methods is raised from `cmdparser.py`, which is, to say the least, counterintuitive.
=> Change callability check

Dockerfile
This PR adds `procps` to the Dockerfile as a dependency.
Certain evennia commands, such as the `@server` command, rely upon `ps` to run correctly. Unfortunately, alpine uses the BusyBox `ps`, which is somewhat idiosyncratic in its option handling. Adding the `procps` dependency installs a more standard `ps`, allowing server maintenance commands to work correctly. 
For further background, see gliderlabs/docker-alpine#173.
This fixes #1635.
=> Add procps dependency to Dockerfile

Dockerfile
In order of decreasing significance:
* Move addition of all files later to avoid premature build cache invalidation
* Add separate instructions to copy over files needed earlier
* Change deprecated MAINTAINER instruction to LABEL maintainer
* Change ADD to COPY, as ADD apparently behaves weirdly in some cases
* Alphabetize dependencies for readability
Most of these are just stylistically nice, and therefore not particularly necessary, even if they do increase readability. However, the build cache change is significant, because it vastly reduces  (according to my limited testing, by more than 80%) docker build times in the common case of changes to code only.
The only other change to be somewhat significant is the change of `MAINTAINER` to ` LABEL maintainer`, as the former is deprecated …
=> Change Dockerfile to comply with best practices

evennia/utils/evform.py, evennia/utils/tests/data/evform_example.py, evennia/utils/tests/test_evform.py
Force evform.raw_form to have all lines of the same length - effectively a rectangle
See #1459
=> EvForm tracebacks with dissimilar line length

evennia/commands/default/unloggedin.py, evennia/server/tests.py, evennia/server/throttle.py
Reimplements the existing _throttle function as a standalone class and removes the Session requirement so that it may be used to restrict traffic on both the webserver and the terminal server.
The existing throttle is a nifty feature with a lot of potential but limited in what it can be used for due to the fact that it is a private function buried in an obscure module (evennia/commands/default/unloggedin.py) and requires a Session object.
The current implementation also stores empty lists on keys instead of purging them once timeouts have elapsed, and there are no constraints (beyond network bandwidth) on the growth of member lists. This PR drops sparse keys upon detection and uses deques to limit the number of timestamps recorded per IP.
=> Improved Throttle

evennia/utils/logger.py
Adds a logger to the existing collection that classifies log entries as security events (prefix "[SS]").
#1383 and others have highlighted the need for better logging of security-related events, but we do not currently have a commonly accepted destination to send them to. This PR aims to define one.
=> Adds a logger for security-related events.

evennia/web/webclient/static/webclient/js/plugins/hotbuttons.js
This adds a small extra split pane with 9 "hot buttons" on it that can send frequently used commands (like @who). This initial PR is intended more for starting the discussion around this functionality than a final form.
What Works:
- click an "unassigned" button to record the current command that has been typed into the input textarea.
- click to send that command to the server
- shift-click to clear the button back to "unassigned" status.
Many games have very-frequently-used commands that become a pain to type over-and-over on mobile devices and similar browser situations.
=> initial support for webclient HotButtons

evennia/web/webclient/static/webclient/js/plugins/history.js
This restores the ability to cycle back through the last 21 input lines using the up/down arrow keys.
The old implementation of tracking the current typing (character-by-character into a temp buffer by firing a timer and then resetting the history count to zero and then only listening for up/down arrow events when the cursor position is at the end of the input line) conflicts with the new plugin onKeydown and onSend approach.
Bug fix for #1668
This is not the only way to fix this, but this is the simplest code.  If the scratch area handling is a must-have, then I would suggest having the fwd() and back() functions store/restore the current inputfield value to/from the scratch area.
=> Fix #1668 - up arrow key regression

evennia/settings_default.py
Modifies settings_default to lazily reverse the named URLs for login and logout endpoints (instead of using hardcoded values).
Settings has `/accounts/login` and `/accounts/logout` set for login and logout (stock Django values), but there are no endpoints by either name in Evennia-- here the authentication endpoints are located as subpaths of `/authenticate/`.
Usage of Django LoginRequired view controls will yield 404 errors when the user is redirected to a login endpoint that does not exist.
https://github.com/evennia/evennia/blob/8c0dca25002378156d5748ee0b5c1d7d53d58885/evennia/web/website/urls.py#L16
=> Fixes incorrect LOGIN_URL and LOGOUT_URL values

evennia/commands/default/admin.py, evennia/commands/default/cmdset_account.py, evennia/commands/default/system.py
This PR implements feature request #1477.
It moves the code from CmdDelAccount into a switch check in CmdAccounts, making some minor style adjustments (mostly normalizing the quotes around strings and compressing newlines), and adding an explicit permission check to the new switch (as `@delaccount` has a higher permission lock than `@accounts`). It then completely removes all references to CmdDelAccount.
It does _not_ carry over the /delobj switch from CmdDelAccount as that switch appeared to be completely unimplemented.
=> Move delaccount functionality to `@accounts/delete`

evennia/commands/default/building.py, evennia/commands/default/tests.py
- Resolution for #1499
- Tests for `@desc obj=`
Failing tests demonstrates 2 issues (commit fde9f151889):
1. `@desc obj=` doesn't clear `obj` description.
2. `@desc obj=` sets the current room description as `'obj='`.
=> Bug 1499: [READY FOR REVIEW AND MERGE] No way to clear object descs without resulting to `@py`

evennia/server/portal/telnet.py, evennia/server/portal/tests.py
Simple unit test of a sample run for telnet/ttype negotiation. Doesn't test a lot of options, like oob commands, mccp, mssp, etc, just ensuring that the handshakes occur and the protocol flags are set.
I noticed that a lot of the server/portal stuff lacked test coverage, so I wanted to get the ball rolling on adding unit tests here. This  is a pretty simple/minimal test of different options, which I think could be expanded upon a lot. Since I'm a total neophyte at network stuff I didn't really feel confident in making more detailed tests, though my understanding is that the mocked transport from `proto_helpers` is intended to let you see the buffer of what a client receives.
Part of #1458 . Yay Hacktoberfest!
=> Add unit test for ttype/telnet

evennia/commands/default/building.py, evennia/commands/default/tests.py
Add searching for local exits before trying to search globally.
Convenience change for the `@link` command to prevent always having to use dbrefs.
Resolves #1355
=> Implement local-first search for @link command

evennia/commands/default/system.py, evennia/server/amp_client.py, evennia/server/portal/amp_server.py, evennia/server/portal/portal.py, evennia/server/sessionhandler.py, evennia/utils/gametime.py
Puts in tracking for the uptime of the portal and transmits that data upon the server connecting to the portal via the amp bridge, then makes that information accessible in `gametime`, which is then displayed in the `@time` command.
Implementing an old feature request.
Resolves #1420
=> Add portal uptime to @time command.

evennia/accounts/tests.py, evennia/objects/objects.py
Adds a line of code to the object deletion hook to check for and remove the object from an account's playable characters list.
For multisession modes greater than 1, when a character is deleted, it leaves a null value in the account object's playable characters list instead of shrinking the list.
=> Removes deleted characters from account playable characters list

evennia/commands/default/admin.py, evennia/commands/default/cmdset_character.py, evennia/commands/default/tests.py
Add a simple command to the other admin commands to allow a staff member to force an object to execute a command.
It's a simple use case that comes up occasionally, such as when someone is running a roleplay event and wants to force objects to execute specific commands, and saves people the trouble of resorting to `@py`.
N/A
=> Add a simple 'force' command to force objects to execute commands.

evennia/accounts/accounts.py, evennia/accounts/tests.py, evennia/objects/objects.py, evennia/objects/tests.py, evennia/typeclasses/models.py
This PR is designed to let one generate paths to an object's web interface(s) from within a Django template.
It adds a set of methods to retrieve HTTP paths for DefaultAccount objects and all children of DefaultObject:
* `get_admin_url()`: Returns a path that, if followed, will display the object in the Admin backend.
* `get_absolute_url()`: Django construct; returns a path that should display the object in a DetailView.
* `get_update_url()`: Returns a path that should display the object in an UpdateView.
* `get_delete_url()`: Returns a path that should display the object in a DeleteView.
Note that this does not magically expose all your objects, create DeleteViews for everything, let random users into Admin or enable any sort of new or scary functionality.
The admin function works out of …
=> Object URL references, named paths and pseudo-slugs

evennia/settings_default.py, evennia/web/utils/middleware.py, evennia/web/website/views.py
* Renames `MIDDLEWARE_CLASSES` to `MIDDLEWARE` to adhere to Django 1.10+ new-style middleware expectations.
* Reimplements the `shared_login` view function as a middleware class.
I haven't tested it, but based on the current logic I believe that given the way we had this set up, `_shared_login` would only kick off if someone went to the index page. It would not run if someone tried to access a protected page, received an auth prompt, was redirected back to the destination page, and then hopped over to the webclient. The webdev would likely have to call this method on all views.
Implementing this as middleware forces the credentials to synchronize on all submitted requests.
As for the rename, we didn't have any custom middleware written so it's a matter of renaming a setting for the sake …
=> Converts shared_login view function to a middleware class, updates middleware setting

evennia/typeclasses/models.py
Slugifies meta.verbose_name for web_get_*_url methods. Prior to this, any camel-cased classname would be split and separated by a space. This eliminates the space by making it a slug.
Bugfix.
closes #1712
=> Slugifies meta.verbose_name for web_get_*_url methods

evennia/web/utils/middleware.py, evennia/web/webclient/views.py
Fixes incorrect order of operations when synchronizing credentials across webclient/website and removes redundant code from webclient view.
=> Fixes failure to pass credentials to website when authenticating through webclient (#1723)

evennia/web/webclient/views.py, evennia/web/website/tests.py
Webclient is currently hidden instead of disabled. This PR returns a 404 at the view level if the webclient is supposed to be disabled.
Issue #1731
=> Returns 404 if webclient is supposed to be disabled (fixes #1731)

evennia/web/website/templates/website/help_detail.html
Removes the 'safe' template tag from the help detail template.
I put the tag in with the intention of letting writers use HTML in their help entries but in retrospect this makes little sense (HTML won't render if the same entry is viewed in a terminal client) and is a security vulnerability anyway (malicious HTML/scripts that find its way into a help entry will be happily rendered).
It would be better to ship secure by default and force user acceptance of the risks by modifying the template themselves.
=> Removes 'safe' template tag from help detail page (vulnerability).

evennia/web/webclient/templates/webclient/base.html
Update URL for the CDN for split.min.js - fixes #1737 
The CDN URL changed for split.min.js - this fixes that, and also keeps the version the same.
Closes #1737 and fixes the same bug on desktop.
=> Update split.min.js CDN URL - fixes #1737

evennia/prototypes/protfuncs.py, evennia/prototypes/prototypes.py, evennia/prototypes/tests.py
Fixes #1704 
- `#number` is not automatically converted to object search by `#dbref`. 
- New `$dbref()` protofunc is introduced as alias for `$obj(#Number)`.
- Traceback no longer happens as automatic object search is not done unless explicit `$obj()` or `$dbref()` protofunc is used.
=> #1704: traceback when prototype key contains `#Number` [READY FOR REVIEW/MERGE]

evennia/commands/default/account.py, evennia/commands/default/tests.py, evennia/objects/objects.py
When characters are created using CmdCharCreate or Character.create(), a delete() lock is now set to explicitly let account owners delete characters.
Inconsistent handling; see #1729
=> Adds delete() lock to new character objects (#1729)

evennia/commands/default/unloggedin.py, evennia/settings_default.py
Adds a setting to specify the point of contact unauthenticated users should use to contact a staff/admin member.
Will display the address in the unloggedin help command text if it is set.
If one can't login, they have no other support channels open to them-- no way to appeal bans, address client/auth issues, or anything.
Closes #1719
=> Adds STAFF_CONTACT_EMAIL setting and value to unloggedin help command

evennia/server/evennia_launcher.py, evennia/settings_default.py
Since the new evennia launcher, both `makemessages` and `compilemessages` were broken.  This offers a solution to fix it and allow both commands to work.
Translation of the main Evennia server wasn't possible. Notice a few changes though, some of which may not be appropriate:
- In `settings_default`, the `GAMEDIR` can now be the `EVENNIA_DIR` if the user is running from `evennia`.  We'll let another method check whether it's a problem or not.  Having this check performed in the settings AND in the launcher was a understandable redundancy that didn't help here.  This test is still performed, however, so error messages are correctly displayed if the user isn't in a valid game directory and tries to perform a command like `evennia start`.
- In the launcher, `init_gamedir` now takes an …
=> Allow the 'makemessages' and 'compilemessages' commands

evennia/__init__.py, evennia/server/evennia_launcher.py
The `WindowsError` exception was checked for compliance and is now removed to support non-Windows systems.
=> Fix #1754: WindowsError is replaced with OSError

evennia/commands/default/building.py
Spawn/delete <prototypekey> was not actually deleting anything.  This enables the command to work as expected.
=> BugFix - Delete Prototypes using spawn command

evennia/objects/objects.py
When overriding the `search` method, and providing default candidates, search fails when using DBREF directly.  This has been fixed.
The problem is a bit hard to describe.  When overriding the `search` method (say, in `Character`) and providing default candidates (not changing anything else), the search will fail.  This is due to the fact that `use_dbref` is calculated in the super method, along with `exact`.  So I made sure to place `candidates` to an empty value if the search was evaluated to an exact, global search, otherwise it created problem downstream.
=> Fix a slight error in search with candidates

evennia/server/evennia_launcher.py, evennia/server/portal/amp.py, evennia/server/portal/telnet.py, evennia/server/session.py
The current branch running on Python 3.5 of Python has some issues with encoding that most ASCII users wouldn't notice.  Basically, it's either ASCII, or utf-8, the rest doesn't work.  And while I would be happy to have everyone using utf-8, it's clearly not a good choice, particularly with Evennia's settings.
To see the problem:
1. Install a fresh Evennia with the develop-py3 branch.
2. In the `server/conf/connection_screens.py` file, append some utf-8 in the file (see mine below).
3. With a client that uses a different encoding (mine uses latin-1 for instance), connect to localhost:4000.  You will see an error on the accented character, as you should (default encoding isn't changed).
4. Use the `@encoding` command to change your output encoding.  In my case: `@encoding latin-1` .
5. And …
=> Encoding and Python 3

evennia/utils/dbserialize.py
I jsut removed yet another `to_str()` call on the `dbserializer`.  Not only did it fix my issue, but it makes old databases (generated with Evennia 0.8) completely usable now.
It seems like a win-win.  Just a tiny change, Evennia works better and maintains compatibility of data, which was a concern for me, with some users having a much more important database than I.  I worried it would generate problems, but it seems more than stable and to actually fix issues.
The thing is to get used to the idea that pickle needs bytes, and to not convert these bytes to str, especially not with `to_str`.  Basically, pickle will return binary data, and using `to_str` on it will attempt encoding the binary which is dangerous and unnecessary.  So now, I let pickle do its magic and if it wants bytes, bytes …
=> Fix accents in Evennia py3, bring compatibility with Evennia 0.8 data

evennia/web/website/templates/website/404.html, evennia/web/website/templates/website/500.html, evennia/web/website/templates/website/evennia_admin.html, evennia/web/website/templates/website/flatpages/default.html, evennia/web/website/templates/website/tbi.html
Fix the missing padding in the default 404, 500, tbi, admin, and the flatpage templates by setting the correct class on the cards.
Fixes issue #1780
=> Switching card-block to card-body.

evennia/contrib/tutorial_world/build.ev
Bugfix: barrel description `@desc barrel =` was executed in tutorial batch file build.ev before the barrel was even created with `@create/drop barrel:`.
Now the sequence is fixed and tested working properly with @batchcommand/interactive tutorial_world.build.
=> bugfix: barrel(rack_barrel) description before the barrel is even created

evennia/commands/default/building.py
Fixes bug in @lock command, where Superuser does not bypass control/edit access when attempting
to use switches per command's secondary syntax.
Resolves #1796.
=> Fix lockcmd bug not ignoring superuser when using switches. Resolves #1796.

evennia/commands/default/building.py
Made a few minor adjustments to the @examine command so it will display the categories of Attributes.
I actually think Categories are useful and there's no good way to differentiate Attributes without @py at the moment.
Doesn't seem to be any problems.
OLC looks like it was SUPPOSED to show Categories but it doesn't... but it's beyond my ability to fix.
MonitorHandler doesn't have an option for watching Attributes by category... but it's beyond my ability to fix.
=> Changed @examine to list Attribute categories.

evennia/web/webclient/static/webclient/js/plugins/default_in.js, evennia/web/webclient/static/webclient/js/plugins/dual_input.js, evennia/web/webclient/static/webclient/js/plugins/history.js, evennia/web/webclient/templates/webclient/base.html
This set of changes alters the webclient's current plugins to allow for a second input textarea.
This requires some changes to the current default_in plugin and extensive changes to the history plugin.
To make this work, the auto-focus-on-keypress must be removed.  This is a change in default behavior.
Lots of game types benefit greatly when the client supports the option for dual input text areas
=> Add a dual_input plugin

Dockerfile, evennia/server/evennia_launcher.py
Switched the Dockerfile to python3
**evennia/evennia:develop** is still on python2 and can't actually run evennia any more!
- Changed the base image from `alpine` -> `python:3.7-alpine` due to alpine only having python3.6 in repos. Some packages have changed as a result.
- I had to remove the zope `__init__.py` workaround because evennia was trying to alter zope files in the container which were owned by `root`. I don't think this will cause any problems since [python hasn't required a blank `__init__.py` since 3.3](https://stackoverflow.com/questions/37139786/is-init-py-not-required-for-packages-in-python-3).
**There hasn't been much testing on this!** You may prefer to wait until the vanilla alpine container ships python3.7.
=> Update Dockerfile to use Python3.7

evennia/__init__.py
Add the BASE_WHATEVER_TYPECLASS properties to evennia API, containing the loaded typeclasses. EG:
evennia.BASE_CHARACTER_TYPECLASS contains the actual class, not a path to the class.
I feel it's silly that these are imported over and over again all over the place using class_from_module()
Having them all in one place for an easy, direct import seems much smarter, more efficient, and cleaner.
Then again, I'm not sure why you haven't done this already. Because of that, I'm just proposing this at the moment instead of CHANGING ALL OF THOSE CALLS. What do you think of this idea?
=> Added Base Typeclass loading to Evennia API.

Dockerfile
Starting up evennia gives a list of internal/external ports. Right now there is a random mix of internal and external ports being exposed. This PR exposes **all** and **only** external ports.
external ports:
telnet: 4000
webserver-proxy: 4001
webclient-websocket: 4002
internal_ports (to Server):
webserver: 4005
amp: 4006
Running the docker container and publishing all exposed ports via the `-P` flag to `docker run` will result in the web client being unusable, as 4002 is not exposed. 
This PR also fixes small whitespace issues with the examples.
=> Dockerfile: Only expose external ports

evennia/game_template/world/prototypes.py
The examples in the game template world prototypes say to use "prototype" when specifying a parent for a prototype, but that currently should be "prototype_parent". I suspect something changed in the code and the these docstrings were missed in the update.
=> correct the prototype parent keyword in the examples

evennia/web/webclient/static/webclient/js/plugins/goldenlayout.js
Fix for issue #1869: tagged messages for preconfigured webclient components are still displayed in components that should only show untagged messages
closes #1869
=> pre-populate the untagged types (fixes #1869)

evennia/commands/default/system.py, evennia/utils/evmenu.py
- When typing the `py` command with no argument, a Python console opens in the client.
- The `evennia.utils.evmenu.get_input` function had to be very slightly altered.
This feature adds a great simplicity for Evennia debugging and administrator operations through the `py` command.  If the admin has full privilege, she can use the `py` command with no argument, open a Python console and interactively type commands in, to see the result, create variables and so on:
> py
Python 3.7.3 ...
Type 'exit' to quit this console.
>>> evennia
<module evennia>
>>> var = 5
>>> if var < 8:
...     var = 32
...
>>> var
32
>>> for obj in here.contents:
...     here.msg("You are in this location.")
...
>>> # And perform more...
... exit
Closing the Python console.
The advantage of this over the editor …
=> Opens an interactive console when using the py command with no argument

evennia/web/webclient/static/webclient/js/plugins/goldenlayout_default_config.js
This PR switches the webclient back to a single input pane by default.
Griatch asked to for this to avoid confusing new users
=> Make single input window the default instead of dual inputs

evennia/web/webclient/static/webclient/js/plugins/multimedia.js, evennia/web/webclient/templates/webclient/base.html
This PR adds a multimedia (images, mp3 audio, mp4 video) plugin to the webclient.
Some clients provide the ability to display images or play sounds, since this is one of the strengths of a webclient, this is a simple plugin to provide this feature.  It also serves as an example of how to map arbitrary .msg() content to new handlers.
=> Add a multimedia plugin to respond to images/audio/video server commands

evennia/web/webclient/static/webclient/js/plugins/default_in.js, evennia/web/webclient/static/webclient/js/plugins/history.js
This PR updates the default_in and history plugins to handle input focus a little smoother.
Fixes issues with default focus handling that makes using history more frustrating than it should be
#1890
=> fix shift-up focus issue and enter-key always clearing focus

evennia/server/portal/ssh.py
This trivial PR fixes an error on current SSH default setup, where if I just enable the service I then get
```
couldn't match all kex parts
```
but the twisted error there is spurious, as I can see on the logs:
```
19-08-21 15:04:50  |Portal| disabling non-fixed-group key exchange algorithms because we cannot find moduli file
19-08-21 15:04:50  |Portal| Unhandled Error
File "/home/oggei/.virtualenvs/evennia-bJd7NXTz/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
return context.call({ILogContext: newCtx}, func, *args, **kw)
File "/home/oggei/.virtualenvs/evennia-bJd7NXTz/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
return self.currentContext().callWithContext(ctx, func, *args, **kw) …
```
=> fix ssh server

evennia/commands/default/general.py
This PR fixes whisper behaviour when user type twice a whisper recipient, eg
```
whisper foo,foo,bar = asd
```
with a `set` repetitions no longer matter, we don't have any duplication receiver side
ciao!
=> do not duplicate whispers

evennia/settings_default.py
pylint complained and indeed now that you droppped python2, importing range from builtins is no longer needed:
```py
In [1]: from builtins import range as r
In [2]: r is range
Out[2]: True
```
thanks!
=> importing `range` no longer needed

evennia/server/portal/ssh.py
added a required python library for use SSH. In newer versions, cryptography seems already installed because pip dependencies, but this is not the case for pyasn1 (already present in err message) and bcrypt, tracking it down required a temporary patch on evennia.server.portal.ssh module
I've left the original message untouched but you could probably delete cryptography dependency too
Thank you, ciao!
=> fix ssh import error message

evennia/contrib/clothing.py
The `clothing` contrib could be used in standalone.  If new clothing types were created (say, if you created a `Shoe` typeclass inheriting from `Clothing`), you couldn't equip objects from the `Shoe` typeclass.
Knowing how a contrib is used can be hard.  But allowing for inheritance does seem important in this case.  Some users find it actually more logical to create a typeclass per equipment type and set their `db.clothing_type` in `at_object_creation`.  Although this wasn't the intended use of the contrib, where one can easily create clothes using the `Clothing` typeclass, allowing to inherit from `evennia.contrib.clothing.Clothing` while still being able to use the wear and remove commands is important, I think.
The reason why this was not possible was due to the use if `is_typeclass` …
=> [clothing contrib] Allow to create new Clothing classes

evennia/utils/tests/test_utils.py, evennia/utils/utils.py
This PR removes our last remaining usage of the deprecated "imp" module, which resides in the `evennia.utils.utils` module. Since the new importlib equivalent works a bit differently, this required refactoring the logic a bit.
The good news is that the new equivalent should be quite a bit faster!
Fixes #1929.
=> Remove deprecated "imp" module uses in evennia.utils.utils

requirements.txt
This was originally suggested due to an imagefield, but that is no longer present. Since Pillow is not required to run Evennia, we should remove it and let the users opt into it if they end up wanting/needing it for their custom code.
I can follow up this merge by removing it from the install docs. That should simplify things greatly for Linux and Windows users both.
=> Remove pillow from requirements

evennia/utils/tests/test_utils.py, evennia/utils/utils.py
This updates the utils.latinify function to support Python 3 and adds a set of unit tests for that function. More details on the changes available under “Other info” below.
In Python 3’s string/unicode changes, `encode` is strictly string -> bytes and `decode` is strictly bytes -> string. Each still accepts similar parameters to determine how to generate or interpret the appropriate byte sequence.
As such, in order to continue to accept as many strings as possible, a first check is done to see if the input string is a sequence of bytes and, if so, it decodes that to a string. Later on, because `unich` will now always be a string, it must be encoded first before decoding. Additionally, to also support the new unit tests, I’ve extended `_UNICODE_MAP ` to have mappings for both left and …
=> Update utils.latinify to support Python 3

evennia/objects/admin.py
Add id, other core fields to ObjectDB search_fields
HactoberFest. This is my first PR on github for an open source project. Please guide me if I made a mistake.
Issue #1951
=> Add id, other core fields to ObjectDB search_fields

evennia/utils/tests/test_validatorfuncs.py, evennia/utils/validatorfuncs.py
#1970 
Fixed calculation of days (from days and years) and allow for any `\d+[smhwyd]` to appear more than once.
(found during #1967)
=> validatorfuncs.duration() returns incorrect datetime.timedelta() Closes #1970

evennia/utils/text2html.py
Replacing deprecated escape function from the cgi module with escape function from the html module (new since Python 3.2). 
https://docs.python.org/3.5/library/html.html#html.escape
Fixes errors printing messages to the web console.
=> Replacing deprecated method from cgi with html.escape()

evennia/typeclasses/attributes.py, evennia/typeclasses/tags.py, evennia/typeclasses/tests.py
When TYPECLASS_AGGRESSIVE_CACHE is disabled, the Attribute and Tag handlers will both continue to write/update the cache, but not read from it. This might be manageable under normal conditions but was causing a memory leak when I attempted to export the contents of my database.
Closes #1996 and #1997
=> Stops Attribute/Tag handlers from caching when TYPECLASS_AGGRESSIVE_CACHE is disabled

evennia/comms/models.py, evennia/comms/tests.py
Not much to say. Small modification to the __str__ method for Msg objects to account for senders with no 'key' attribute.
Closes #1982
=> Fixes Msg str rendering where no key attribute exists for sender

evennia/objects/manager.py, evennia/objects/tests.py
Small tweaks to the objectmanager `copy()` method to replicate categorized attributes and tags.
Problem was reportedly with tags only but the same behavior occurred with attributes as well.
#1972
=> Fixes failure of copy() method to replicate categorized attributes and tags

evennia/accounts/accounts.py
The account.characters property was treated as an iterable, even if None. I suspect this was causing some problems on the web frontend during account creation.
Possible resolution to #1905
=> Fixes TypeError with Account characters property if unset

evennia/accounts/accounts.py, evennia/settings_default.py
Read the settings for the account throttles (account creation and login) from the settings files, rather than hard-code them in the app.
There are several use cases where an admin may want to tweak the throttle settings for account creation on a per-site basis. For example, if you maintain a separate test realm shard, you could set stricter throttles in the secret settings without having to change your code base.
I personally run a public-facing shard behind an nginx proxy, so that shard in particular needs a loose throttle because it applies to all connections.
=> put account create and login throttle parameters in the settings files

evennia/commands/default/system.py, evennia/typeclasses/managers.py
Moves the aggregation-processing burden of ObjectDB's `object_totals` into the backend instead of iterating *n* queries to do the same app-side.
=> Makes ObjectDB `object_totals` perform aggregations in-database instead of in-app

evennia/server/portal/webclient.py, evennia/web/utils/middleware.py, evennia/web/webclient/static/webclient/js/webclient_gui.js
This PR introduces a series of fixes for bugs related to WebSocket connections in various browsers.
There are a few issues:
---
* According to the spec, an exit code of `1000` means that the WebSocket connection was closed through JavaScript while an exit code of `1001` means that the WebSocket connection was closed because the user navigated away from the page. Some browsers (e.x., Firefox) seem to wrongly send code 1000 when the user navigates away or reloads the tab/window. Other browsers (e.x., Google Chrome, Mobile Safari) send code 1001 which is then considered an error.
The first change is to properly disconnect the WebSocketClient when exit code 1001 is received.
---
* Both Google Chrome and Mobile Safari end up making a new WebSocket connection _before_ the old connection is …
=> Fix for WebSocket failing to log the user in when the page is refreshed

evennia/commands/command.py
Command.client_width() doesn't use its fallback properly when dealing with strange NAWS issues or the WebClient. Fixing that by making some adjustments to client_width()
Stuff's gotta work, man.
I changed it to always return the default width for more consistency. If returning a None would cause formatting to fail and traceback when a command's run by an NPC, then it's a problem. Yes, it's better if the command never creates a message to send in the first place if there's nobody listening, but...
=> Fixing error with Command.client_width()

evennia/scripts/scripts.py
This should fix the issue with passing 0 as the `interval` parameter for the `restart` function in evennia/evennia/scripts/scripts.py.
Issue reference: https://github.com/evennia/evennia/issues/2039
=> Fix for the interval=0 bug in the restart script function

evennia/server/portal/telnet_ssl.py
Decodes bytes into utf-8 string.
Certificate generation causes an error due to response not being a string (on current master).
=> Adds .decode() to byte stream to convert to string

evennia/utils/dbserialize.py
Just a bugfix for dbserialize error logging.
=> log_error is not a function in utils/logger.py; changed to log_err in utils/dbserialize.py

evennia/server/portal/portal.py
Django returns a 404 for any putChild inside the proxy plugin module.
As written, this actually isn't putting the child into the Evennia Proxy, it's putting it into Webserver, which is explicitly not the point.
These two lines have to go down below the proxy resources are loaded.
=> Fixing unintended consequences of proxy_plugins

CHANGELOG.md, evennia/contrib/turnbattle/tb_equip.py, evennia/objects/objects.py, evennia/typeclasses/models.py
- All unspecified instances of is_typeclass in core are now exact=True;
- is_typeclass defaults to exact=False
the promise of a better future
=> Defaulting is_typeclass to exact=False

CHANGELOG.md, evennia/objects/models.py, evennia/objects/objects.py
Adds light / mild indexing to the ContentsHandler on ObjectDB, reducing the filtering and sorting that must be done for frequent operations like viewing a room description.
Also changed ContentsHandler's ._pkcache to be a set() instead of a 'Dictionary that only cares about keys and has None for values'. Because using a dictionary that way is weird.
Seeing how DefaultObject.return_appearance() was constantly guessing at what it was trying to display offends my sensibilities. I'm putting this out there as a possible alternate approach.
I'm not 100% sure the Wilderness contrib likes this.
=> Add a contents indexer to optimize inventory lookups.

CHANGELOG.md, evennia/server/amp_client.py, evennia/server/portal/amp.py, evennia/server/portal/amp_server.py, evennia/server/portal/portal.py, evennia/server/portal/portalsessionhandler.py, evennia/server/portal/ssh.py, evennia/server/portal/ssl.py, evennia/server/portal/telnet.py, evennia/server/portal/webclient.py, evennia/server/session.py, evennia/server/sessionhandler.py, evennia/settings_default.py
Made it so that the hierarchy of networking-based classes (SessionHandlers, Protocols, ServerSession) and bits and pieces related to it (such as session._attrs_to_sync) are components that can be swapped out / altered via settings.py configuration.
You know me well enough by now! I want to replace / update things smoothly. It proved difficult to do things such as 'change how reload and logins works', so I'm adding in more hooks where things can be ripped out and replaced with alternate code.
All tests pass. Am able to login and boogie just fine. Some new stuff from other branches is failing - stuff that has to do with the REST framework. evennia.server, server.portal, .objects, .scripts, .typeclasses, etc, all of that's working nicely.
=> Replaceable networking guts!

evennia/server/portal/ssh.py
Correct the ssh server getKeyPair method to correctly use the cryptography module instead of the Crypto module.
Removed the import of Crypto
Corrected the key creation to correctly use the RSA module from cryptography module.
Wanted to use ssh on my server, but it was broken.
=> Fix ssh server getKeyPair method

evennia/utils/test_resources.py
The EvenniaTest class hardcodes in DefaultObject, DefaultCharacter, etc as the spawned typeclasses. This inherited class uses the defaults as defined by settings.py
Tests shouldn't break because my hooks don't run when objects are created. This could probably be extended further as a proper 'mygame tester'
I know this is all perfectly doable without a core contrib, but anything that reminds people "hey, you can actually use unit tests by yourself even if you don't intend to contribute" is a good thing.
=> LocalEvenniaTest - uses settings-defined typeclasses

evennia/contrib/puzzles.py
Puzzles do not survive server reload (because their scripts aren't persisted).
As builder
1. Create puzzle
```
@create/drop flint
@create/drop steel
@create/drop fire
@puzzle fire, flint, steel = flint, steel, fire
```
2. List puzzle
```
@lspuzzlerecipes 
[Alternatively ...]
@scripts
...
```
3. Reload server
```
@reload
```
4. List puzzle
Puzzle should be displayed
Zero puzzles. Puzzle won't appear in the list of puzzles nor in the list of scripts.
When a puzzle gets created, it's not persisted. Hence, after a server reload, puzzle is lost. 
Puzzle should survive server reload.
=> Bug: Puzzles do not survive server reload (because their scripts aren't persisted)

evennia/accounts/accounts.py, evennia/objects/objects.py, evennia/server/serversession.py, evennia/typeclasses/attributes.py, evennia/typeclasses/models.py, evennia/typeclasses/tests.py
Almost completely refactors the Attribute system to introduce swappable "Backends" for AttributeHandler, and a proper In-memory Attribute used by the NAttribute system. This means that the .attributes and .nattributes API are now identical - .nattributes can do everything that Attributes can do.
This opens the doorway for more advanced shenanigans; my goal is allowing session.ndb (or perhaps a special session.pdb ? ) to save data over AMP to the PortalSession which can survive a reload. This is now easily possible using a subclass of the InMemoryAttributeBackend and InMemoryAttribute.
Strangely, a few contribs fail tests with these changes. I am not sure why. Hoping someone can help me figure it out.
=> Attribute refactor

evennia/server/portal/tests.py
Adds a websocket unit test
One bug in this PR, I'm hoping it's an easy fix. While the class passes tests when run by itself, when run with the other tests in the evennia test library, it leaves an Unclean Reactor. I'm guessing I need to do something in tearDown to make that not happen, but I'm not sure what.
=> Websocket unit tests

evennia/contrib/puzzles.py
The current help text of the `use` command is confusing to regular users. 
This PR makes the help text a bit user friendlier.
=> Make Puzzle's use command user-friendly.

evennia/commands/default/building.py
Edit building.py to make the open command assign control permissions to the creator. 
Ran into bug while playing around in the demo.
Not tested but based on existing code in CmdCreate so I imagine it will work.
Solves issue #2152
=> Make CmdOpen grant control to creator

evennia/contrib/color_markups.py
This corrects the contrib/color_makrup.py colors to match the ones in ANSI.py, as it was both lower and uppercase resulted in the same color.
This seems to be how it was intended to work, I think?
=> Correcting curly brackets colors

evennia/scripts/scripts.py
Fix a bug that script whose `db_interval` is 0 will be run when call its `start` method twice.
A script whose db_interval is 0 should not call self._start_task and self._step_task. Because of line 482 in the script.py: 
```
if self.db_interval > 0:
self._start_task()
```
So the `ExtendedLoopingCall(self._step_task)` will not be called.
But if its start method is called twice, codes in line 440 will run self._step_task:
```
if not self.ndb._task and self.db_interval >= 0:
self.ndb._task = ExtendedLoopingCall(self._step_task)
``` 
In my case, when a new session connects to the server, the `portal_connect` of the sessionhandler will be called. It will call `_ScriptDB.objects.validate()`, then the `validate` method of the script's manage.py will be called and it will call `script.start`.
=> Fix a bug that script whose db_interval is 0 will be run when call its start method twice.

evennia/contrib/tutorial_examples/example_batch_code.py
Removed spaces at code and header rules.
the /interactive switch was not working as expected. It was seeing the entire files as one block. So when run as interactive everything would run on a single `pp`. Removing the white space after # resolved the issue. Though the @batch command does see the header as a block to run.
Found while following https://github.com/evennia/evennia/wiki/Batch-Code-Processor
=> tutorial_examples/example_batch_code interactive patch

evennia/contrib/gendersub.py
`text` in the msg method of GenderSub is a positional argument causing it to not function as expected in regard to projects documentation on the DefaultObject.msg method.
This changes text to being an optional kwarg.
allow GenderSub.msg to work as expected
Example `GenderSub.msg(prompt="this is your prompt")` will cause traceback errors.
=> gendersub msg method removed positional argument

evennia/web/webclient/static/webclient/js/plugins/goldenlayout.js, evennia/web/webclient/static/webclient/js/plugins/multimedia.js, evennia/web/webclient/static/webclient/js/plugins/options2.js
This PR refactors the goldenlayout plugin to allow non-text outputfunc's (in this case the multimedia plugin)
to use the same routing as the text outputfunc uses.
Also added some settings to the multimedia plugin to enable/disable each type.
Some users want to control where the multimedia resources are displayed (or completely turn them off).
Addresses #2199
=> update multimedia and supporting plugins to allow message routing

evennia/server/portal/webclient_ajax.py
This change will make it possible to see user IP addresses even while behind a proxy, similar to the websockets implementation.
Keeps expectations similar regardless of which technology is used by the webclient.
Unsure of relevant Issues. Happy Hacktoberfest - inspired me to try fixing some bugs or helping out!
=> Separate User IP from Proxy when webclient uses AJAX

evennia/accounts/accounts.py
When a game uses naïve datetime settings, an error occurs as `.localtime()` is called. The error prevents users from logging out, as the server attempts to announce the event. This fix checks server settings first and substitutes `.now()` accordingly.
Adding a check will prevent this error on timezone-naive games: 
```
File "d:\arxdev\evennia\evennia\server\sessionhandler.py", line 527, in login
account.at_post_login(session=session)
File "d:\arxdev\evennia\evennia\accounts\accounts.py", line 1297, in at_post_login
self._send_to_connect_channel(_("|G{key} connected|n").format(key=self.key))
File "d:\arxdev\evennia\evennia\accounts\accounts.py", line 1265, in _send_to_connect_channel
now = timezone.localtime()
File "d:\arxdev\venv\Lib\site-packages\django\utils\timezone.py", line 207, in …
```
=> Add a check for timezone-naive settings

evennia/locks/lockfuncs.py
Modifies the `objtag` and `inside` lockfuncs to perform checks on the appropriate objects.
Commands locked `cmd:objtag(blah)` were checking for tags on the Command instance instead of the bound Object.
Commands locked `cmd:inside()` were checking if the Command instance was inside the bound Object instead of the caller.
Partial fix for #2227.
=> Adds appropriate object checking to objtag lockfunc

evennia/commands/command.py
Adds `client_height()` method to Command.
Balance; there is a `client_width()` but no simple way to get the height.
=> Adds client_height() method to Command.

evennia/commands/default/help.py
```python
"%s" % string
"{}".format(string)  # since python 2.6
f"{string}"  # since python 3.6
```
and remove the the form a += b because it rely on CPython's efficient implementation of in-place string concatenation for statements in the form a += b or a = a + b. This optimization is fragile even in CPython. Used "".join() instead.
Up-to-date formatting and less string update.
=> [refactor] CmdHelp.format_help_entry for up-to-date formatting and string concatenation

evennia/accounts/accounts.py, evennia/commands/default/account.py
When account.execute_cmd() is called without an explicit session
argument for a server using MULTISESSION_MODE 2 or 3, it does not
know which session to use and may leave it None. Downstream, code
attempting to get the puppet from the session can fail with an
error because of the None session.
This change adds in checking for the None session, and sets the puppet
to None if there is no session defined.
Addresses bug #2252
=> Add null checking when getting puppet from session

evennia/commands/default/system.py
CmdTime has two table outputs that are not aligned in the same width. This change aligns the tables to the same width of 78.
Just a simple fix for a simple mistake with the table outputs in CmdTime where one table was not the same width as the other.
Because it was simple, yet annoying.
=> Adjusting the width of the output in CmdTime

evennia/commands/default/help.py, evennia/comms/channelhandler.py, evennia/game_template/commands/command.py, evennia/objects/objects.py, evennia/utils/eveditor.py
As suggested in mygame\commands\command.py, I'm overriding COMMAND_DEFAULT_CLASS in settings.py to try to make sweeping changes. Having certain commands inherit directly from the base Command class thwarts this.
The only difference between Command and MuxCommand is that MuxCommand defines some custom parsing, but that's overridden by these commands anyway, so there should be no practical difference.
The import change in game_template/commands/command.py was required to fix an exception on server reload caused by the channelhandler.py change (I guess something to do with import order?)
Makes it easier to edit gamewide look/feel, and brings codebase more in line with documentation that suggests all default commands inherit from COMMAND_DEFAULT_CLASS .
=> Make more commands honor settings.COMMAND_DEFAULT_CLASS

evennia/utils/gametime.py, evennia/utils/tests/test_gametime.py
This fixes evennia.utils.tests.test_gametime; datetime.fromtimestamp assumes the current system's timezone, so some of the unit tests currently fail if the system's timezone is set to EST (on Windows).
Bug fix.
=> Fix test_gametime.py for non-UTC servers

.gitignore, evennia/accounts/accounts.py
Fixes START_LOCATION behavior for default account creation (ie from the connection screen). Current behavior is to start new characters in the Void, even when START_LOCATION is overridden in settings.
Bug fix.
=> Fix settings.START_LOCATION behavior

evennia/server/evennia_launcher.py
When superuser is created pull details from environmental variables so that no interaction is required. If environmental variables are not present then fallback to typical behavior.
Very helpful when launching via Docker (see feature request #2248).
I am not sure to what extent we would like this to mimic Django's support (see [here](https://docs.djangoproject.com/en/3.1/ref/django-admin/#createsuperuser)). The approach I have proposed here looks for both a username AND email address first, and then will check to see if an environmental variable for the password is present. Django's `createsuperuser` command does not allow for setting the password programmatically so I am leveraging `evennia.accounts.models.AccountDB` to perform that operation.
=> Make use of environmental variables for superuser creation

evennia/accounts/accounts.py
Changed `ooc <message>` to `public <message>`
I suspect the public channel used to be called "OOC" but was changed at some point. `ooc <message>` is no longer a valid command. This PR updates the guidance to the user to use the public channel instead, which seems to be the intention.
=> Suspect OOCLook commands are out of date

evennia/objects/objects.py
Added from_obj=self to announce_move_from() and announce_move_to(), and to the individual at_msg_receive() calls in msg().
The standard msg() function was not passing from_obj on to the at_msg_receive() hooks of the objects it sent messages to, causing them to lack potentially vital information. This has been remedied. Also, for the sake of consistency, I added from_obj kwargs to the msg_contents calls for moving in and out of a room, and set them to the object that is moving.
=> Add from_obj where missing

evennia/server/portal/portal.py, evennia/server/server.py, evennia/server/tests/test_server.py
Should resolve #2336
Adjusts maintenance time calculations from seconds to minutes, as maintenance is run every minute.
Fixes stale DB connection issues when running MySQL, and does these maintenance items in the time frames that are expected.
=> Maintenance time calculations should be done in minutes, not seconds.

evennia/contrib/rpsystem.py
rpsystem.send_emote now passes kwargs to obj.msg.
rpsystem.send_emote uses sender as from_obj when calling obj.msg
All evennia unit tests pass.
rpsystem.send_emote now passes kwargs to obj.msg.
rpsystem.send_emote uses sender as from_obj when calling obj.msg
https://github.com/evennia/evennia/issues/2386
=> rpsystem.send_emote passes kwargs, uses sender as from_obj

evennia/prototypes/prototypes.py
If you have an exact match on a module prototype, the current logic will go on to fuzzy match on database prototypes and potentially match things from the db in addition to the exact match from the module prototype.
The existing behaviour results in many matches for a spawn when there is an exact match available.
=> Don't allow fuzzy match on db if exact match on module prototype

evennia/server/portal/suppress_ga.py, evennia/server/portal/telnet.py, evennia/server/portal/tests.py, evennia/server/portal/ttype.py
Mudlet contains a isPrompt() function to detect prompts. This is powered by the presence of a GA on the line that sends it (most clients in 2021 suppress GA). This patch is to only send a GA if SGA is False and the line is a prompt. It also turns on FORCEDENDLINE for Mudlet as it only displays mud output if there's either a GA or a newline.
Pretty sure it's broken without it.
=> Fix ga for mudlet

evennia/objects/objects.py
There seems to be no reason NOT to pass kwargs passed into move_to to the hooks underneath (I actually had this overridden solely for this purpose, locally).
Makes move_to more flexible, and I suspect it should work this way anyway.
=> Pass **kwargs to various hooks on move_to

CODING_STYLE.md, evennia/commands/cmdhandler.py, evennia/commands/default/syscommands.py, evennia/contrib/building_menu.py, evennia/prototypes/prototypes.py
There are small typos in:
- CODING_STYLE.md
- evennia/commands/cmdhandler.py
- evennia/commands/default/syscommands.py
- evennia/contrib/building_menu.py
- evennia/prototypes/prototypes.py
Fixes:
- Should read `traverse` rather than `traverese`.
- Should read `shortcuts` rather than `shorcuts`.
- Should read `multiple` rather than `multuple`.
- Should read `multiple` rather than `mulitple`.
- Should read `indentation` rather than `indendation`.
Avoids ambiguity and confusion in the documentation.
Closes #2420
=> docs: fix a few simple typos

evennia/commands/default/account.py
- In `who` command, object IDs were showing up next to user names, even when the caller doesn't have dev/admin privileges.
- This is because a local variable was being re-used inside the scope of a loop, causing the access check to be run against the account being looked at, rather than against the account issuing the command.
Example, from a non-dev account:
And after fix:
And proof, after fix, that privileged view still works:
=> Fix priv check when displaying names in CmdWho

CHANGELOG.md, docs/source/Concepts/Clickable-Links.md, evennia/server/portal/mxp.py, evennia/utils/ansi.py, evennia/utils/tests/test_tagparsing.py, evennia/utils/text2html.py
Adds an anchor tag for MXP, |lu. Same syntax as |lc but instead of sending a command when you click on it, it opens a new page/tab.
PR requested by Griatch. Adds more MXP functionality to Evennia.
=> Add anchor tag for MXP

evennia/commands/default/help.py, evennia/settings_default.py, evennia/utils/utils.py
Help topics and subtopics are clickable when the CmdHelp command is used.
Includes class attribute to disable clickable links.
unit tests evennia.commands.defaul.tests.TestHelp and evennia.utils.tests.test_utils.TestFormatGrid pass.
evennia.utils.utils.format_grid now has an option to ignore ansi markups when calculating row lengths. Including white spaces between elements.
Verified CmdHelp was only only evennia code (in develop branch) that uses format_grid.
Ease of use. Especially for disabled users.
output example:
Verification that formatting is unchanged.
clickable topics off:
Clickable topics on:
=> Cmd help clickable topics

evennia/commands/command.py, evennia/help/filehelp.py, evennia/help/models.py, evennia/web/templates/website/help_detail.html, evennia/web/templates/website/help_list.html, evennia/web/website/tests.py, evennia/web/website/views/help.py
Adds command help entries (command doc strings) and web.
Discussion: https://github.com/evennia/evennia/discussions/2426
Issues found as of yet:
File and command entries only
gray area above entry text does not show proper "Help Index / Category / Topic" format. Probably something that needs to be added to the context dictionary in get_contect_data.
entries need to convert from ascii to html. Or likely just drop ascii text tags all together.
In detail view category name is not showing above "context["topic_list"]", the gray list of other entries in the current category. Probably something that needs to the context dictionary in get_contect_data.
command entries only
The general category is not sorting with the other categories. Probably just case sensitivity?
Loads of log_infos throughout …
=> file and command help web support, proof of concept

evennia/utils/utils.py
evennia.utils.format_grid did not reset the row variable after extending past the grid.
Resulting in duplicate rows.
Looks like it only happens when the second to the last element in the row extends into the space that the last element should be in.
Verified issue is in basic evennia game with no code changes (a "mygame" instance).
Example of instance without fix:
After the fix:
Avoid duplicate rows in help command.
=> evennia.utils.format_grid duplicate rows fix

evennia/web/admin/accounts.py, evennia/web/admin/objects.py, evennia/web/admin/scripts.py
This fixes the issue I reported, #2461 where typeclasses are not shown in the admin site.
If this _isn't_ merged, then any time I open an account or an object or a script from the admin site and dare to make a change it'll overwrite the typeclass with one of Evennia's default typeclasses. This should also occur for a stock project, so it's recommended to make this change.
Apparently, you can pass lambda expressions as the choices in a ChoiceField and this will cause Django to call that in order to get the list of choices. I just added `lambda: ` before the call to `adminutils.get_and_load_typeclasses` and it immediately fixed the problem.
(My project uses "share.objects.Object" as the default object typeclass, which wasn't showing up before.)
=> [DEVEL] Fix typeclass dropdown and make it always show all of the available typeclasses

evennia/contrib/xyzgrid/xymap_legend.py
The code attempts to get a specific Room, creating it when it does not exist.
If you use a custom typeclass it seems the exception being caught is of the custom type while
the exception being raised is the base xyroom's exception so it leaks out.
This PR catches the base django.ObjectDoesNotExist so it is guaranteed to catch any exceptions about the object not existing.
It allowed the rooms to spawn normally.
Fixes an issue with XYZGrid Contrib that prevents it from being used with custom room typeclass
I did an Import Optimize with Pycharm which seems to have removed
from evennia.utils.utils import make_iter
=> Fix exception leaking when spawning XYRoom Nodes

docs/source/Getting-Started.md
Issues #2434 or #2070 show that the installation guide can be a little
bit confusing regarding on which directory should the user be when
trying to pip install.
This commit adds an entry on the Troubleshooting section, in hopes of
helping those who stumble with that process.
=> Getting Started: more troubleshooting info

evennia/objects/objects.py
Defaults object get_display_name() looker parameter to none.
Resolves #2415
=> get_display_name looker default. Resolves #2415

evennia/commands/default/help.py
Fixed minor typo in `CmdSetHelp` help documentation.
=> Fix sethelp help file typo.

evennia/contrib/cooldowns.py, evennia/contrib/tests.py
This PR adds a new cooldowns contrib module that can be used off the shelf for tracking cooldown timers. Code can set a cooldown for some number of seconds using an arbitrary cooldown key. The cooldown will be reported as not ready until that amount of time has passed.
Cooldowns can be easily integrated into commands as a manual check to block repeated uses until the cooldown is ready, and can also be easily integrated into a custom lockfunc if desired (not included in this PR).
Cooldowns are a simple attribute handler under the hood but have lots of varied uses. Many kinds of game require an action rate-limiting mechanism, and this system provides it very simply as a drop-in.
I make heavy use of this in my under-development game, and thought it might be helpful to others.
N/A
=> Add new cooldowns contrib.

evennia/utils/dbserialize.py
**Overview:**
Update to imports supports Python 3.10 while maintaining backwards compatibility.
For updated collections references, see:
https://docs.python.org/3.10/library/collections.html
https://docs.python.org/3/library/collections.abc.html
=> dbserialize fix to support Python 3.10

evennia/scripts/scripts.py
Modify DefaultScript to re-use the same attributes for  `_paused_time`, `_paused_callcount`, and `_manually_paused`. These attributes currently are deleted on each script every time it restarts (which occurs for all scripts on server reboot) and then recreated again. For better efficiency, these values can be simply set to None rather than deleted, which allows them to stay in the attr cache and not caused unnecessary creations of new attributes.
Note that I also reformatted the file with the black formatter, which is why you're seeing some other smaller style diffs in here.
DB efficiency.
I posted some comments about this in the discord where I noticed by attribute ID numbers going up quite high (into the 20000's) on a development server with relatively few objects, and tracked it down …
=> Set pause-related script attributes to None rather than deleting them

evennia/commands/default/building.py, evennia/objects/objects.py
Non-Persistent Attributes now shown in examine.
format_nattributes no longer references deprecated all(return_tuple=True) function.
View NAttributes in examine
Closes #2643
=> Fix for bug #2643: NAttributes on examine.

evennia/utils/dbserialize.py, evennia/utils/tests/test_dbserialize.py
Add deserialize() shortcut on _SaverMutable and fix OrderedDict bug and fix a bug in deserialize for _SavedOrderedDict as it uses non-standard
initialization.
Add a simple deserialize() shortcut on _SaverMutables that make it easier to deserialize without needing to import `dbserialize.deserialize()`.
While adding unit tests, I discovered a bug where `OrderedDict` was not being deserialized properly because it requires a single constructor argument rather than varargs like other collections.
Make deserialization easy, fix bug.
=> Add deserialize() shortcut on _SaverMutable and fix OrderedDict bug.

evennia/contrib/rpg/traits/tests.py, evennia/contrib/rpg/traits/traits.py
Adds "mult" as a stat to the traits contrib, allowing developers to use multiplicative modifiers for their traits. Anywhere that you would receive "`base + mod`" as a return has been edited to "`(base + mod) * mult`". This is the current value for Static and Counter traits, and the max value for Gauge traits.
I use multiplicative math for my game's buffs and stats sometimes, so I figure other people might too.
=> Adding "mult" to traits contrib

evennia/contrib/base_systems/components/README.md, evennia/contrib/base_systems/components/__init__.py, evennia/contrib/base_systems/components/component.py, evennia/contrib/base_systems/components/dbfield.py, evennia/contrib/base_systems/components/holder.py, evennia/contrib/base_systems/components/tests.py
This adds a contrib to support Components.
This implementation of Components are made in a way that reuses many core features of Evennia.
It was requested a few times in Discord, so I thought this could help.
There are a few important classes in this PR
Component - Base Class for every component
ComponentProperty - Descriptor for setting class components
(Components that are always created with default values at object creation)
ComponentHolderMixin - Mixin that allows typeclasses to use components via a ComponentHandler
ComponentHandler - Wrapper that handles retrieving components both runtime and class defined
DBField and NDBField, essentially AttributeProperties for Components (They wrap to the "host" typeclass)
Prototypes can be used, if you prefix the attribute name by the component …
=> Components Contrib (Pt1)

evennia/contrib/base_systems/components/holder.py, evennia/contrib/base_systems/components/tests.py
Add component names as a tag with the category "component" on host
Searching objects by their components can be useful
Example:
Applying the logic of a global Weather script to all rooms that contain the component "weather"
This is my first PR ever and also the first time i use tests so i hope i did it the right way ^^'
=> component-contrib:add component name as tag on host

evennia/contrib/base_systems/components/README.md, evennia/contrib/base_systems/components/__init__.py, evennia/contrib/base_systems/components/component.py, evennia/contrib/base_systems/components/dbfield.py, evennia/contrib/base_systems/components/holder.py, evennia/contrib/base_systems/components/tests.py
This allow components to specify tags on the class, using the new descriptor.
It supports providing a default value, having multiple tags or enforcing a single value.
It does this by using the TagHandler and setting the category as component_name__field_name.
Tags set this way will be cleared if the component is removed or if 'del' is called on the field.
It is also possible to set values in the prototypes, like
```
'tags': (
('axe', 'melee__melee_type', ''),
)
```
Similar to regular tags, it can be much more efficient to use than attributes when many entities
use the same 'value', such as Enums like melee_weapon_type.
I also added some doc related to #2686
=> Add TagField to Contrib Components

evennia/prototypes/prototypes.py
Currently, it calls load_module_prototypes if no module prototypes were found.
This works most of the time but it will fail when prototypes are injected, like XYZGrid does.
This fix will force a complete load on the first search.
The benefit is you are guaranteed loading all prototypes in a deferred way.
The drawback is you may load twice if you already loaded for some reason, since only
search will set the _LOADED value on the method.
Prototypes are very useful, having them not load is a pain.
This is a follow-up to #2634
=> Fix Prototype Loading when using injected prototypes

evennia/contrib/base_systems/components/README.md, evennia/contrib/base_systems/components/dbfield.py
This changes the delimiter of DBFields and NDBFields to :: instead of __
Related to the security concern raised by @strikaco
Related to #2692
This will require all current contrib users to update their prototypes and attributes.
For module level prototypes, you can find them with the regex     `['"].*__.*['"]`
For database related stuff, the easiest way is to recreate the DB, if that is not possible...
You can run the following query to update your attributes
```
UPDATE
typeclasses_attribute
SET
db_key = replace(db_key, '__', '::')
WHERE db_key LIKE '%\_\_%' ESCAPE '\'
```
Alternatively, you can use evennia shell OR the `@py` command ingame and run
```
from evennia.typeclasses.attributes import Attribute
from django.db.models import Value
from django.db.models.functions import Replace …
```
=> [Components Contrib] Changed DBField and NDBField delimiters from __ to ::

evennia/utils/containers.py
Moves the `script.start()` call outside of the "(re)create script" block, so the script is actually being started regardless of whether it's new or pre-existing.
I had to fix it for my own game anyway. <.<
Closes #2707
=> Auto-start global scripts

evennia/utils/tests/test_text2html.py, evennia/utils/text2html.py, evennia/web/static/webclient/css/webclient.css
Currently, Evennia attempts to control the display of white-space in the webclient by doing server-side parsing. Not only is this resulting in numerous inconsistent spacing issues, but controlling content display should be done on the client, not the server.
This removes the white-space parsing from the server entirely and instead adds a CSS rule to the webclient that forces display of white space.
Closes #2701 (if backported), #2677
=> Properly display whitespace in the webclient

evennia/commands/default/tests.py
This adds tests for variations of the general commands "look", "home" and "nick".
In the spirit of #1458, I found some chunks of these command implementations that were not covered by current tests. This should improve the coverage of `evennia.commands.default.general` from around 57% to 62%.
(I'm also demonstrating concepts around test suites, coverage, and source control to a small class of prospective software engineers.)
=> Improve coverage of evennia.commands.default.general

evennia/contrib/rpg/rpsystem/rpsystem.py
The search system for the `rpsystem` contrib stores cached regex for non-Character objects under a key+aliases string, so all objects with a given key+aliases match to the first such object cached.
This PR changes the cache identifier to the object's own ID to prevent false references.
Closes #2705
=> `rpsystem` contrib: cache regex tuples by ID instead of key+aliases

evennia/contrib/base_systems/components/holder.py, evennia/contrib/base_systems/components/signals.py, evennia/contrib/base_systems/components/tests.py
This adds a free form Signals system for components, plugging the existing components code.
It allows decoupling components from each other and also from their host to a certain degree.
A brief example would be a level up signal.
Several components could register to this signal "level_up" using a method decorator.
The host typeclass itself could register a method to this signal.
Then, when the "experience" component decides its time for level up, it can
`self.host.signals.trigger("level_up", new_level)`
Which will in turn call every method that was registered as listener, passing the provided args/kwargs.
Similarly, methods can be marked as "responder", which allows querying a particular signal.
This can be useful to something like retrieving bonuses for a stat across an unknown amount of …
=> [Components Contrib] Component signals

evennia/objects/tests.py, evennia/typeclasses/models.py
`init_evennia_properties()` attempts to fetch all object properties with a `__set_name__` attribute in order to ensure that AttributeProperty and TagProperty fields are initialized. In python 3.10, this has the side effect of also initializing any fields defined with `@property` (and similar decorators), which is not desired. As this initialization occurs on a new object before any attributes from a `create` call are applied, `@property` fields that cache attribute data will cache the wrong value.
Fixes bug on new object initialization.
The problem only occurs in python 3.10, where the `__set_name__` attribute now exists. Python 3.9 and older do not appear to have attribute (or `__dict__`) on `@property`.
=> Only initialize AttributeProperty and TagProperty in init_evennia_properties

evennia/scripts/tickerhandler.py
Corrects the index for `interval` in `store_key` and iterates through `ticker_storage` as full key/value pairs to prevent caching bad data.
Note: There are several tuples being passed around in the code with the same data in seemingly different positions, so I referenced the return value for `_store_key` which generates all of the store_keys to find the index of 3:
`        return (packed_obj, methodname, outpath, interval, idstring, persistent)`
Resolves #2722 for develop; can be backported to close it completely.
=> Fix `tickerhandler.clear`

evennia/commands/default/building.py
A typo in the `examine` command messed up the indentation on the NAttributes section; this corrects the typo.
=> Fix NAttr indents on examine

evennia/utils/dbserialize.py, evennia/utils/tests/test_dbserialize.py
The merge/update operator | is the recommended way to combine dicts in python 3.9 and beyond. Implement this operator for SaverDicts.
Apply black formatting to modified files, which causes a few unrelated formatting changes.
Avoid tracebacks on savers when using |.
=> Implement dict update operator (|) for _SaverDict

evennia/contrib/base_systems/custom_gametime/custom_gametime.py, evennia/utils/containers.py, evennia/utils/gametime.py
Corrects leftover and now obsolete `.restart` calls on `schedule` to make them reinitialize delays properly, and updates `GlobalScriptContainer` to make sure all global scripts are loaded in `.start`
Closes #2712 and #2744
=> Schedule and Global Script fixes

CODING_STYLE.md
Current URL for the example google style docstring is leading to a 404 page. This PR just update to the proper URL.
=> fix google style URL on CODING_STYLE.md

evennia/web/static/webclient/js/evennia.js
Adds a check to the webclient to make sure a cmdid has a stored callback before trying to retrieve it.
Closes #2742
=> Fix webclient error on server-side echo

evennia/contrib/rpg/rpsystem/__init__.py, evennia/contrib/rpg/rpsystem/rpsystem.py, evennia/contrib/rpg/rpsystem/tests.py
Moves the SdescHandler to the base `ContribRPObject` class and streamlines the recog/sdesc fetching and processing for ease of customization.
It also rewrites the sdesc parsing for searches and emotes, moving the regex processing onto the search/emote text and eliminating the regex calculations and cache for sdescs, as per #2724
I've been using the rpsystem contrib for a while and it has a lot of quirks which have made basic customizations a bit difficult. Most of the streamlining changes are intended to make that customization simpler by minimizing how much code you have to modify in order to overload display options, such as sdesc vs recog coloring.
Additionally, the current ordered permutation regex generation makes loading multiple objects with multi-word names cause sizeable hangs in …
=> Streamline `rpsystem` sdesc processing

evennia/utils/tests/test_text2html.py, evennia/utils/text2html.py
This replaces the current regex-substitution parsing with state-tracking iterated substring substitution.
The regex method is based on the assumption that ANSI codes function like HTML tags, with a start marker and a stop marker. However, ANSI codes act as state switches and don't strictly speaking have end markers at all, but instead a "restore" switch (`|n`). This difference in design and use is also what resulted in the trailing/unclosed style classes, such as underlines and blinks.
With that in mind, I also opted to replace the nested `span` approach (which for this method would require keeping track of how many spans there were, and what kind) with consecutive `span` elements that are styled with the applicable classes for that segment of text, where the CSS class list represents the …
=> Rewrite text2html color and style parsing

evennia/utils/evmenu.py
Updates `EvMenu.options_formatter` to use fstrings and changes the "manual" row/column padding to use `EvColumn` instead.
This also updates the docstring to remove the erroneous `caller` arg.
=> Update and simplify `options_formatter`

evennia/utils/funcparser.py, evennia/utils/tests/test_funcparser.py
This allows properly escaping strings by using alternating quotes or double quotes.
Like "'" would return a string consisting of the character '
It also handles lone unescaped quotes as part of a literal string.
Fix bugs to get 1.0 released
Related to #2737 
I started working on a refactoring to make it easier by splitting the functions first and handling the args second but I have no idea when and if I'll get this done right, so I decided to also fix it in the current implementation.
=> FuncParser Fix #2737

evennia/utils/text2html.py
This patch resets style states on ANSI_NORMAL flag regardless of `clean` status.
Fixes the webclient displaying undesired styling that should be cleared by the ANSI_NORMAL flag.
=> Fix ANSI_NORMAL override in text2html

docs/source/Links.md
Reorganizes the [Links](https://www.evennia.com/docs/1.0-dev/Links.html) page a bit for easier use, updates some of the descriptions, and gets rid of dead links.
I also added a link to the Discord relay code I made since it was requested, but I did that the last separate commit so I can roll it back easily if we just want the update/reorganization.
=> Update the Links page

evennia/contrib/rpg/rpsystem/rpsystem.py
Fixing a minor oversight with moving the rpsystem contrib to have sdescs on all Objects.
The original logic had an either/or check for "sdesc" versus "key+aliases", so now that objects have valid sdescs, all object aliases were being ignored, rendering the aliases generated for item stacking via `get_numbered_name` (along with any other aliases one might generate) unusable. This changes that to an either/or check for "sdesc" versus "key", and adds any aliases regardless.
Since characters don't generally have aliases, it doesn't affect the character side of things.
Bug fixes
=> rpsystem: Always include aliases as candidates

evennia/utils/tests/test_utils.py, evennia/utils/utils.py
Changes the behavior when `endsep=''` to actually have no final separator instead of presuming a comma. While I feel this is a valuable change, it would affect any code that uses the empty string as a way to simply erase the "and" from the default format, causing a minor break in backwards compatibility.
Also, since I was there, I expanded the functionality slightly to allow for defining a custom separator. _This_ change has no effect on existing usage and would be fully backwards-compatible.
Fulfilling #2785
=> Update separator handling for `iter_to_str`

evennia/server/sessionhandler.py
Fixes a pass-by-reference bug that resulted in msg text overriding prompt text. Also makes sure that msg text is processed before other cmd types in the msg (such as prompt).
Bug fixing
Closes #2783
=> Fix text + prompt msg function

evennia/commands/default/building.py
Adds a check before sending the list of result strings to make sure that there *are* result strings. If not, send an error and syntax reminder.
Also corrects an `attributes.get` call to return the expected list of Attribute objects, rather than the values.
Lastly, removes the "raw" special case for the returned attribute list, since the `view_attr` method is formatting the returned message for us.
Bug fixes
Reported in the discord help channel
=> Fix attribute-list traceback and silent failures on `CmdSetAttribute`

evennia/contrib/rpg/rpsystem/rpsystem.py, evennia/contrib/rpg/rpsystem/tests.py
This changes `parse_sdescs_and_recogs` to actually use the self-reference regex to identify self-references. It also splits the logic for getting case refs out into a helper function.
Bug fixing.
An issue with self-references which I'd patched out but apparently regressed during parser rewrites arose on discord, where `/me` would multimatch if there was anyone else with an sdesc or recog that starts with "me" (such as Melody, or merchant). Originally I'd resolved this by matching full words only, but that's not a desirable limitation.
To resolve things so you don't have multimatches on `/me` but can still reference a merchant with `/merch`, I've added an initial self-ref pass to the sdesc/recog parser, using the `_RE_SELF_REF` regex. This has the added benefit of actually making the `@` …
=> rpsystem: Add special-case handling for self-references.

evennia/contrib/rpg/rpsystem/rpsystem.py, evennia/contrib/rpg/rpsystem/tests.py
the rpsystem contrib is currently stripping out the {"type": "say"} data which the default evennia say command flow creates.
Was easy to add this back in.
Currently working on a project which depends on the text-tuple's data for things like speech.
And just think this should be restored.
Easy peasy.
=> Added msg_type to rpsystem.send_emote()

evennia/typeclasses/tests.py, evennia/utils/dbserialize.py, evennia/utils/tests/test_gametime.py
This PR tentatively fix #2808 by letting un/pickling functions correctly identify dict subclasses and properly serialize them.
close #2808
=> enable dict subclasses serialization

.github/workflows/github_action_test_suite.yml
This PR drastically reduce tests time by exploiting django tests' parallel function. Having a 2/3x faster tests is good as people don't have to wait a lot and everybody is more happy!
Rationale behind that: this stems from another (pypy) branch where something was needed to reduce the extremely long pypy times, mainly because scipy compilation and jit being enemy of a typical testcase run. Django parallel tests require tests are separated one from another, ie. does not cross-depend and this is something we already have, so exploiting that is a no-brainer.  
Other optimizations could be done, starting from those simple which django docs lists [for psql](https://docs.djangoproject.com/en/4.0/ref/databases/#speeding-up-test-execution-with-non-durable-settings) and probably for others …
=> faster CI via parallel tests

evennia/utils/dbserialize.py
This PR allows to `or` two `_SaverMutable` objects. The returned object have the implementing class `_data` type.
close #2789
=> implement _SaverMutable | _SaverMutable

evennia/objects/manager.py
ObjectDB.objects.get_objs_with_key_or_alias() now uses db_key__icontains instead of __istartswith when searching for inexact matches. This makes it match the behavior of how searching by the aliases works.
So, with my (Dragon Ball) project, I tried doing @tel/loc me=Roshi and hey wow, no Roshi found. Then I tried @tel/loc me=Master and got a TON of search results.
But when I @search Roshi, I get plenty of Roshi-related stuff.
Turns out that @search is using db_key__icontains while object.search() ends up calling ObjectDB.objects.get_objs_with_key_or_alias(), which uses db_key__istartswith when handling fuzzy matches - so, it first gathers via startswith, and THEN does a string_partial_match on each word... this seems inconsistent and like an oversight to me.
Simple tweak and now searches …
=> Alter ObjectDB.objects.get_objs_with_key_or_alias() to use icontains

evennia/objects/objects.py
The title kinda says it all.
Because it's useful for rendering messages and other checks in the other hooks, and I cannot think of a single reason why this information is NOT being made available to the move_to chain via kwargs.
Easy peasy.
=> object.at_traverse() now passes the exit being traversed as a kwarg

evennia/objects/objects.py
Since the spawner sets location and destination directly in the db rather than through the typeclass `create` method, Exits were having prototype-set destinations overwritten to location by `basetype_setup`.
This fixes that by checking for a pre-existing destination rather than assuming there isn't one.
Bug fixing
=> Fix DefaultExit overwriting prototype destination

evennia/game_template/server/conf/at_server_startstop.py, evennia/server/server.py, evennia/settings_default.py
Altered AT_SERVER_STARTSTOP_MODULE to alternatively take a list of module paths instead of a string.
Added an at_server_init function which is always called first before any other "start" variants to handle specialized loading. (It's weird that reload_start or cold start is called before normal start but there's nothing that happens first for initial loading of resources or config or whatnot...)
Main reason I thought of it was for helping Athanor - it has its own load process it handles, but it'd be great if this then called the mygame at_server_startstop... at that point I realized, it'd be even better if Evennia just had one more hook and also the ability to optionally call multiple modules in sequence... and that it can be done without overcomplicating anything.
Everything seems to …
=> Improving at_server_startstop modules

.github/workflows/github_action_build_docs.yml, .github/workflows/github_action_test_suite.yml
This PR enable requirements' caching in either test and docs CI pipelines. It also bumps action's version because why not ;)
speedups, survive to third-party sites outages
=> enable dependencies cache in CI

evennia/contrib/game_systems/crafting/crafting.py, evennia/contrib/game_systems/crafting/tests.py, evennia/contrib/rpg/rpsystem/rpsystem.py, evennia/objects/objects.py, evennia/server/evennia_launcher.py, evennia/typeclasses/attributes.py
I'll promise I'll not become a `timeit` zealot but after that:
```
In [3]: %timeit '{foo}'.format(**{'foo': 'bar', 'a': 1})
817 ns ± 6.67 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
In [4]: %timeit '{foo}'.format_map({'foo': 'bar', 'a': 1})
495 ns ± 3.46 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
In [5]: %timeit '{foo}'.format(foo='bar', a=1)
620 ns ± 3.25 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
I've did a quick grep and made couple edits :)
thank you, regards
=> speedier format/_map()s

evennia/game_template/gitignore
Adds a gitignore line to catch root-dir rotated log files (e.g. twistd.log.2)
=> Ignore rotated log files

requirements.txt
This PR addresses the findings of #2840 ; wherein on systems with Python 3.9+ that do not have a timezone set (containers) python attempts to fallback to use of `tzdata` for timestamps on `[MudInfo]` emits. Adding tzdata to dependencies ensures that Evennia works consistently on these systems.
Added `tzdata` to requirements.txt with no version pinning as tzdata is a timezone data package for Python and should never have compatability issues. Rather we would always want Python to leverage the latest tzdata changes in the event of timezone changes (for example, some timezones dropping daylight savings).
Reducing friction for installs on container systems.
This will resolve #2840 once merged.
=> #2840 Add tzdata to requirements.txt to prevent stack traces

docs/source/Contribs/Contrib-Menu-Login.md
Fixes the  `CONNECTION_SCREEN_MODULE` setting missing the `evennia.` which causes the doc instructions to throw a stack trace.
Fixes #2844
=> Fix missing `evennia.` in Menu Contrib Docs

docs/source/Contribs/Contrib-Clothing.md
This fixes the instruction problems mentioned in #2846 - where the `Clothing` typeclass has been renamed to `ContribClothing` but the docs do not yet reflect this.
Fixes #2846
=> Fix clothing creation instructions

evennia/objects/objects.py
The PR adds checks for a 'search' lock for obj.search() and obj.get_visible_contents() which identifies whether the object should be searchable.
Vanilla Evennia does not allow true hidden objects by default.
The 'view' lock will prevent the object being displayed in a room's description and stop the look command with "Could not view 'object(#9)'", where as attempting to look at a non-existant object returns 'Could not find '<object>''. Likewise, the 'get' lock will disallow getting with "Could not get 'object(#9)" instead of 'Could not find '<object>''. Both of which give away the existance of a hidden object.
The PR adds checks for a 'search' lock for obj.search() and obj.get_visible_contents() which identifies whether the object should be searchable. Where search = false, then the …
=> Add 'search' lock for obj.search() and obj.get_visible_contents()

Dockerfile
When copying the user's game directory to a Dockerfile that includes both Evennia source and user game source, chown the game directory contents to the `evennia` user.
The method of using Evennia dockerfiles as explained [here](https://www.evennia.com/docs/1.0-dev/Setup/Installation-Docker.html) works fine, since the Docker `--user` is `$UID:$GID` in the docker run command, so the user inside the container matches the one who owns the game files. This allows Evennia to arbitrarily create/remove/edit files in that game source tree.
However, if one wishes to build a standalone Docker image that can run on a container somewhere in the cloud, this does not suffice. Permissions errors are encountered by the running Evennia process, since the process runs as user `evennia` but copied files by …
=> Add chown to Dockerfile

evennia/server/evennia_launcher.py
Use alternate method of finding `EVENNIA_LIB` path, that works on Windows. Also catch an additional error that can happen on windows with `evennia.__version__`
Allows Windows/Powershell etc users to successfully run `evennia --init` frrom a fresh `develop` branch checkout.
According to [the Python 3 docs](https://docs.python.org/3/reference/import.html#__file__) the `__file__` attribute is completely optional and can be left out by the import system depending on the Python implementation. Clearly something like that is happening on Windows here, but it doesn't matter because we can infer the directory we need from the already resolved `EVENNIA_ROOT` directory.
Fixes #2842
=> Fix Windows specific bugs

evennia/web/api/views.py
Changes the queryset property of the endpoint views to use the `all_family()` method in order to correctly find all child typeclasses.
Bug fixing.
Resolves #2872
=> Fix for REST API endpoints

docs/source/Setup/Online-Setup.md
On the Online Setup documentation there is a settings file sample, but it does not include the `CSRF_TRUSTED_ORIGINS`, which is needed and should be documented.
Closes: #2767
=> docs: added CSRF_TRUSTED_ORIGINS to the example

evennia/web/static/webclient/js/plugins/default_in.js
Fix/address #6211. Add the ability to copy text from webclient panels using Ctrl + C, (or Cmd + c on Mac.)
Requested by #6211 , I also thought it would be a good idea to have the ability to copy text without having focus shifted to an input panel automatically.
=> Webclient copy fix

docs/source/_static/basic.css, docs/source/_static/nature.css, docs/source/_templates/layout.html, docs/source/_templates/localtoc.html
Documentation fix. Removes `position: absolute` from search results when screen is smaller than 960px, so they aren't broken on mobile. Also removes min-width on screens smaller than 960px, so that pages in general don't trail off the screen. Fix minor `height:88` bug, which was broken CSS and being ignored anyways.
See these changes here: https://evennia-doc-develop.netlify.app/
Fixing bug.
Fixes #2741.
=> Documentation fix for mobile/small screens

evennia/web/static/webclient/js/plugins/goldenlayout.js
Updates the unicode characters used in the webclient menu to more widely-supported similar ones.
The current characters do not display correctly on OSX.
Fixes #2181
=> fix: use more widely supported unicode characters in webclient

evennia/utils/tests/test_tagparsing.py, evennia/utils/text2html.py
- Adds a boundary character `\b` before URLs to cut down on false positives.
- Prefixes urls without a protocol with `//` to prevent browsers opening them as relative links on the webclient's domain. (Maybe this should just be `https://` rather than using the protocol-relative `//`? Opinions welcome!)
- Prevent urls with no protocols that are too short or long to be valid URLs according to the RFC from being converted to links
- Updates tests for urls without protocols, removes leading-w test, adds new test for boundary character requirement
- Links of the form "www.example.com" currently open relative to the webclient URL, which is not expected behavior.
- Cuts down on false positives by requiring a non-word character before a url, so `www.example` will turn into a link on its own, but …
=> fix: improve convert_urls

evennia/typeclasses/tags.py
This fix assumes that a search for a specific tag key with category will only ever return one tag, which to my knowledge is consistent with the rest of the code and intended functionality. As such, it appends a boolean for each tag+category combination representing whether a match was found, rather than extending the list with any found tags.
If that assumption is incorrect, then this'll need a different solution.
Bug fixing
Closes #2913
=> Fix `TagHandler.has` to return False for no-match

evennia/web/static/webclient/css/goldenlayout.css, evennia/web/static/webclient/js/plugins/goldenlayout.js
Moves the `+` for adding new input tabs to the right of the input tabs, consolidating it into one button rather than one per open tab.
Old:
New:
Makes the UI feel less cluttered and more aesthetically pleasing.
Feature requested in #2215
=> feat: consolidate new input tab buttons

evennia/utils/verb_conjugation/pronouns.py, evennia/utils/verb_conjugation/tests.py
Refactors the module for better readability/ease of future updates, and updates the pronoun data to be consistent across the neutral/plural 'gender' categories.
The original dictionary structure had a lot of redundancy in defining valid mappings, where it started with each possible pronoun and stepped down through all possible outcomes to a final list of pronouns (which results in the same sets of pronouns being entered multiple times)
While the current result still has some redundancy, I streamlined it by breaking it into two different variables:
- `PRONOUN_TABLE` defines the valid viewpoint, part of speech, and gender for each pronoun
- `PRONOUN_MAPPING` gives the target pronoun for each viewpoint, part of speech, and gender
This makes it imo easier to understand what the validity …
=> Refactor `pronouns.py`

evennia/utils/tests/test_utils.py, evennia/utils/utils.py
Adds a new function, which can convert numbers as represented by English words into integers up through the thousands. It can handle cardinal as well as ordinal numbers.
I also added a test for `int2str` since I was adding a test for `str2int` as well
I discovered `int2str` and was finally motivated to make something to go the other way, to expand basic utility.
=> Add `str2int` as counterpart to `int2str`

evennia/utils/funcparser.py
The `funcparser_callable_round` which provides the builtin `$round` needs to return the calculated value.
Fix bug
Fixes #2912
=> In funcparser, make $round() actually return value

evennia/utils/funcparser.py, evennia/utils/tests/test_funcparser.py
Changes the access control check of the `$search()` callable in funcparser to actually perform the check. Previously, the call was being made with three arguments, which I believe made it so the check was being performed against `target` as the lock and the `access` parameter was being slurped into `*args` and ignored entirely.
Fixes bug.
Fixes #2917
=> Fix access control check in $search() function

evennia/utils/funcparser.py
The `$search()` bultin function of funcparser uses an f-string in an error message, but the local variable is not found. This bug was found when adding tests in #2918. It seems like the error string is from an older version of the code where the variable `query` was defined. Fix is to simply change the error message.
Fixes bug
Fixes #2916
=> Remove f-string with unbound variable in funcparser

evennia/contrib/grid/xyzgrid/README.md, evennia/contrib/grid/xyzgrid/tests.py, evennia/contrib/grid/xyzgrid/xymap_legend.py
- Fix installation instructions
- Use specified typeclass in prototype (if any) to instantiate xyz rooms and exits.
#2695
=> fix: xyzgrid spawn doesn't call at_object_creation

evennia/commands/cmdhandler.py
Changes the implicit `sep` argument to `list_to_string` to an explicit `endsep` key, to improve readability of command suggestions.
Previous:
> Command 'restart' is not available. Maybe you meant "stare"or "stretch" , and "saunter"?
Patched:
> Command 'restart' is not available. Maybe you meant "stare", "stretch" or "saunter"?
Readying 1.0 for release
=> Fix formatting on command suggestions

evennia/utils/tests/test_utils.py, evennia/utils/utils.py
The wrong output from the mismatch of parameters fixed in command suggestions highlighted some *other* problems with `iter_to_str` that weren't caught by the current unit tests.
This adds a couple additional asserts to the test and corrects the issues they would catch.
Bug fixing
#2940 (the "previous" example highlights the spacing issues being fixed here)
=> Fix and catch edge cases in `iter_to_str`

evennia/objects/objects.py, evennia/objects/tests.py
The addition of the matching_exit() function. It takes as_list as a parameter to return the matching exit(s) as a list or single Exit. "Matching exits" being the 'return' exit, i.e. if you go 'north' to go somewhere and 'south' to return, **north**.matching_exit() would give you **south**.
Useful little utility for exits.
=> Add matching_exit() to DefaultExit

evennia/objects/objects.py
Changes the assignment of the parsed message in `msg_contents` to avoid overwriting the input string
Bug fixing
closes #2909
=> Fix msg_contents funcparsing

evennia/contrib/rpg/rpsystem/rpsystem.py, evennia/contrib/rpg/rpsystem/tests.py
Adds an additional kwarg to `parse_sdescs_and_recogs` (which can be passed through `send_emote`) as an optional generic fallback string. When provided to `send_emote`, any references that have zero matches will instead be replaced with that string.
(This should be easily backportable to v0.9.5 for anyone who wants it, as it doesn't touch the new search algorithm or the updated sdesc system.)
Improving contribs
Implements #2383
=> Add optional fallback sdesc to rpsystem emote

evennia/settings_default.py
Removes the "typeclass" key from the `DEFAULT_CHANNELS` setting.
Due to the way Python loads modules, the line in question results in the default channels *always* being created with the typeclass "typeclasses.channels.Channel" regardless of your game settings. Since the initial creation of those default channels uses the game-settings default typeclass by default, there is no need to specify it here - it just causes issues when trying to set your own defaults.
Bug fixing
=> Remove typeclass from default channels setting

evennia/objects/objects.py
Simply changes self.key to self.name so that if get_numbered_name isn't overridden in the call, it will use the name property instead of key, this brings thing in line with other areas, so colorized object names can persist in get_numbered_name.
I believe this is the only place that uses .key instead of .name, and I wanted the consistency of using .name so that other areas didn't need to be overridden to display object name colorization etc.
Not sure why it said before that my develop was behind main one, hopefully this time things are in sync?
=> Use `self.name` instead of `self.key` as fallback in `DefaultObject.get_numbered_name`

evennia/contrib/grid/wilderness/README.md, evennia/contrib/grid/wilderness/tests.py, evennia/contrib/grid/wilderness/wilderness.py
The wilderness contrib is currently a bit buggy in 1.0, with ndb properties not being reapplied on reload, hooks not being called properly on `@teleport`ing out, and probably other things relating to the causes of those issues.
This fixes those hooks and updates/cleans up a few other things, e.g. using (the relatively new) AttributeProperty instead of `@property` wrappers.
I also added a new property, `preserve_items`, to allow for recycling rooms only when they're _actually_ empty rather than just when there are no players present. By default it behaves exactly the same as before, recycling any rooms that have no players.
preparing for 1.0
=> Update wilderness contrib for 1.0

evennia/contrib/rpg/rpsystem/rpsystem.py, evennia/contrib/rpg/rpsystem/tests.py
Updates the appearance changes for `ContribRPObject` to use the new display hooks.
This also gave me the opportunity to add grouping of things (not characters) by pose, as well as re-add stacking, because it's quite annoying to look into a box and see:
> book is here.
> book is here.
> book is here.
> blue shirt is here.
> old key is here.
> pineapple upside-down cake lies upside down.
Now instead those contents will show as:
> Three books, a blue shirt and an old key are here.
> A pineapple upside-down cake lies upside down.
I also added a new test to verify this stacking works correctly.
Preparing for 1.0 release
=> Update rpsystem contrib with new hooks

evennia/commands/default/account.py
Fixes extra and missing spaces in output of quell command as detailed in #2991.
Does not address the other minor thing mentioned relating to the duplication in:
`if self.cmdstring in ("unquell", "unquell")`
=> Fix extra/missing spaces in quell output (#2991)

evennia/accounts/accounts.py
Corrects an `or` to an `and` so that it will only add a channel prefix if neither `no_prefix` nor `emit` are set `True`
Bug fixing
#2998
=> Fix no_prefix bug

docs/source/Setup/Channels-to-Discord.md, evennia/accounts/bots.py, evennia/commands/default/cmdset_account.py, evennia/commands/default/comms.py, evennia/commands/default/tests.py, evennia/server/portal/discord.py, evennia/settings_default.py
This adds a built-in Discord chat integration, similar in intent to the IRC and Grapevine integrations. On the Discord side, it requires the end user to sign up for one Discord bot application and manage the permissions and server access. On the Evennia side, all that's required are enabling it in settings and adding the bot token, then using the `discord2chan` command to link and unlink channels
Since there is no twisted library for Discord, I had the pleasure of writing the handling of Discord's API directly into the portal-side protocol, so I kept it to the bare minimum required to enable a chat relay. However, I've set up the evennia-side bot account and the custom protocol so that any courageous souls who want to build a more elaborate integration should be able to do a lot just by …
=> Add discord chat integration

.github/actions/setup-database.yml, .github/workflows/github_action_test_suite.yml
This PR updates the unit testing and Docker deployment jobs to be more modular and possibly extensible.
To make the workflows more modularized and potentially extensible.
- I don't know how to test these workflows. :)  My thought was that I would have to branch off my `new_workflows` branch and create a test workflow to manually invoke them, but I wasn't sure if that was an effective solution.
- The Docker deploy job is untestable by me because I don't have a DockerHub login, for example, plus it specifically looks for a push/PR to `master` and `develop` and that seemed like it would be ripe for trouble if I made artificial commits for testing. :)
- I'm unclear whether you need to use `actions/checkout` for a second job in a workflow (see `jobs.deploy` for what I mean).  GitHub Docs …
=> Unit testing workflow updates

evennia/server/portal/discord.py
I committed and pushed the wrong logic check when patching the retry bug, which has been causing excessive session connections. This is the correct one.
fixing my own bugs
Closes #3015
=> Fix for the excessive Discord reconnects

.github/workflows/github_action_test_suite.yml, pyproject.toml
This PR adds `[tool.coverage.run]` to `pyproject.toml` based on the workflow settings used for running `coverage`.  ~~It also includes a tentative fix to allow coverage testing to run in parallel.~~  (Removed due to `coverage` producing warnings I can't seem to resolve yet.)
A unit testing run now has a max timeout of 35 minutes (for each run).  This is for the PostgreSQL issue where sometimes it will stall until the full six hours elapse.  That's not good.
Also put in environment variables to allow prettier command lines for the actual test commands.  Remember, I'm neurotic.
To consolidate the settings into `pyproject.toml` which is one of its purposes.
The massive diff in the `pyproject.toml` is a side-effect of the TOML extension I'm using for VSCode which automatically formats it to …
=> Adding coverage settings to TOML and workflow

evennia/commands/default/comms.py, evennia/server/portal/discord.py
A rework of the connection logic for the Discord integration, to play nicely with the reconnecting factory base. This fixes the multiplying sessions issue as well as cleans up the general (re)connection flow.
I have tested these changes *thoroughly* this time. No last minute "it'll be fine" additions, everything has been run through multiple connection cycles.
Bug fixing.
Fully resolves #3021 and related.
As a side note, the original connection logic was spun off the grapevine integration, which purportedly has its own (unreported) difficulties. It may be worth revisiting that protocol at some point as well.
=> Rework Discord reconnection logic

evennia/commands/default/general.py, evennia/commands/default/tests.py
Changed the message output of `get`, `drop`, `give` and `inventory` to use "singular" from `get_numbered_name()`.
This makes the output read a little more nicely. For example:
`Gollum drops ring.` -> `Gollum drops a ring.`
`You pick up ring.` -> `You pick up a ring.`
`You give ring to Gollum.` -> `You give a ring to Gollum.`
The message for a failure of `to_give.move_to()` has also been extended from (for example):
`You could not give ring.`
to:
`You could not give a ring to Sauron.`
`inventory` output has changed from:
```
ring  This thing is bad news.
```
to:
```
a ring  This thing is bad news.
````
- One of the lines in `drop` (475) was changed from old-style formatting to an f-string for consistency.
- Unit tests for default commands have been updated.
=> Change get, drop, give, inv to use get_numbered_name()

docs/source/Coding/Unit-Testing.md
in order to run subfolders of tests, you should not include the . (ex: .world.tests etc), so I have removed it from the relevant lines
minor corrections to testing commands
to improve and clarify the documentation
=> Update to Unit Testing Documentation

evennia/contrib/grid/xyzgrid/xyzroom.py
Expands an if/else statement since the two assignments are not assigning equivalent types. (One is a tuple, the other is an integer.)
Bug fixing
The traceback in question occurs when falling back to default settings:
```
.\evennia\contrib\grid\xyzgrid\xyzroom.py", line 466, in return_appearance
client_width, _ = sessions[0].get_client_size() if sessions else CLIENT_DEFAULT_WIDTH
TypeError: cannot unpack non-iterable int object
```
=> Fix traceback in XYZRoom

evennia/server/evennia_launcher.py
Noticed init_game_directory didn't properly detect correct root game directory when passed a path somewhere inside the directory. Traced it to this function ignoring the passed path and going off of current working directory.
`evennia test evennia` reported 1582 tests passed and 38 skipped
=> fix: set_gamedir use provided path and SETTINGS_DOTPATH

evennia/typeclasses/attributes.py
This modifies NickHandler.nickreplace so it does not also strip whitespace from raw_string. 
Leading whitespace is necessary when using the py command in interactive mode.
Fixes #3035 
Ran `evennia test evennia` and it ran 1582 tests ran: 38 skipped, rest OK
=> fix: NickHandler.nickreplace not to strip raw_input

evennia/utils/tests/test_utils.py, evennia/utils/utils.py
Corrects `iter_to_str` so that it will keep joining punctuation on the end separator when the end separator is the same as the internal separator, and adds a test to prevent this error in the future.
Bug fixing
Resolves #3050
=> Fix `iter_to_str` endsep behavior with two items

evennia/contrib/rpg/traits/README.md
Added section at bottom addressing adding additional TraitHandlers. 
Shows example based on first example, but instead using a "stats" TraitHandler, a "skills" TraitHandler and the default "traits" TraitHandler.
Added example at bottom of traits contrib README that expanded first example, but instead breaks the three traits into a stats, skills and traits TraitHandler.
Useful functionality that should be easily accessible to other users from initial read to prevent later refactoring.
=> Update README.md of TraitHandler contrib to explain undocumented capability for multiple TraitHandlers.

evennia/commands/default/comms.py
Fixing a caller reference to self.caller in comms.py
Adding a line notifying the user that the discord bot session is starting (previously there was no echo)
Informational
N/A
=> Adding notification when discord bot session begins

evennia/contrib/game_systems/gendersub/gendersub.py
'help gender' uses escaped pipes to seperate options, but was not displaying correctly as written (without any white space between the options)
Added white space around escaped pipes.
Fixes display of gender help from ```Usage: @gender male|femaleeutralhersmbiguous``` to ```Usage: @gender male | female | neutral | ambiguous```.
I had not opened a bug for this, so there is no issue to close.
=> fix help gender

evennia/server/portal/discord.py
Fixes the latest duplicate sessions issue by disconnecting sessions from the session handler on *all* closed connections, not just evennia-side disconnections.
Resolves #3077
=> Fix zombie Discord sessions

evennia/commands/default/comms.py, evennia/server/server.py
Changed filtering to be inexact for checking against existing channels in `server.create_default_channels()`
Changed duplicate reference from `connectinfo_chan = settings.CHANNEL_MUDINFO` to point at `settings.CHANNEL_CONNECTINFO` (this was previously causing connect messages to always show up in the mudinfo channel)
Fixed f-string
Bug fix
Fix for https://github.com/evennia/evennia/issues/3106
I would argue that all such filtering should occur within the create_channel method (which is called by both `server.create_default_channels()` and the `CmdChannel` in-game command), but for the sake of minimizing changes I didn't do it.
=> Prevent recreation of same-named channels

docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Characters.md
I noticed that one of the variable names in the documentation wasn't correct. It was `BASE_CHARACTER_CLASS` but should be `BASE_CHARACTER_TYPECLASS`
Cos it's kewl
I searched the codebase for `BASE_CHARACTER_CLASS` and this was the only instance.
=> Fixes BASE_CHARACTER_CLASS to BASE_CHARACTER_TYPECLASS

evennia/contrib/base_systems/components/holder.py, evennia/contrib/base_systems/components/tests.py
This prevents a child typeclass to add its own class components to its parent typeclass
Bugfix
Related to ComponentProperties
=> [Components] Fix class components with inherited typeclasses

docs/source/Components/Exits.md
Adds two changes to `docs/source/Components/Exits.md`:
1. Adds note that Exits are one-way (this is mentioned elsewhere in the documentation but not here)
2. Adds cross-reference to example of how to create Rooms and Exits that is covered elsewhere in the documentation.
I got tripped up with the above two things, and would have found it useful to have that info on the Exits.md page.
None.
=> Adds to Exits documentation

docs/source/Coding/Unit-Testing.md, evennia/utils/test_resources.py
`EvenniaTest` is quite heavy-handed and creates a lot of objects you may not need per test. This makes tests run slower than necessary.
However, `EvenniaTestCase` is insufficient for testing because it does not automatically clear the Django ID cache on test teardown. This can lead to strange and flakey test failures.
Fixes some unpredictable test failures when inheriting from `EvenniaTestCase`.
None - was just something I noticed in my own project.
=> Fix Django ID cache not being flushed in EvenniaTestCase

evennia/contrib/game_systems/containers/README.md, evennia/contrib/game_systems/containers/__init__.py, evennia/contrib/game_systems/containers/containers.py, evennia/contrib/game_systems/containers/tests.py
This contrib adds several commands and a typeclass to implement a basic, but extensible, container mechanic.
The cmdset includes extended versions of `look` and `get` to allow looking at or getting objects that are in another object, as well as a new `put` command that allows you to put an object inside a container. These commands reference a new access type, `get_from`, to determine whether an object can be used as a container or not.
The `ContainerObject` typeclass provided has the `get_from` lock set to true by default and also implements a very basic capacity check, along with two new hooks used by the `get` and `put` commands: `at_pre_get_from` and `at_pre_put_in`.
Nearly everyone wanting to build a game with Evennia has wanted containers of some sort. This contrib is intended to …
=> Add a contrib for Containers

evennia/web/static/webclient/js/plugins/goldenlayout.js
In the default_output.js there is a feature to allow a passed-in kwarg to define what html class to assign to the resulting div.
This feature was not included in the processing that Goldenlayout performs.
This Pull Request allows Goldenlayout to use the same 'cls' kwarg to customize each message with a different html style.
=> BugFix: Restore dynamic class kwarg assignment to goldenlayout clients

docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Making-A-Sittable-Object.md, docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-More-on-Commands.md
- Fixed a couple of spelling errors
- Missing the `py` prefix command before a couple of commands
- Added the `py` command to enter so the next commands will work fine.
Going through the docs again. :smile:
=> fixed a couple of spelling errors and missing py commands

evennia/contrib/game_systems/crafting/crafting.py
Corrects attributes from code copy/pasted from the `consumable` checks to the intended `output` checks - and moves the validation of `output_prototypes` to *before* that, since said checks potentially require iterating through it.
Bug fixing
=> Minor fixes to crafting contrib

docs/source/Setup/Installation.md
`twisted-iocpsupport` now has an updated pip package supporting python 3.11, so the build tools are no longer necessary. As such, I've removed the note about the SDK requirement.
=> Remove obsolete Windows install note

evennia/contrib/game_systems/containers/containers.py, evennia/contrib/game_systems/containers/tests.py
Fixes the logic for targeting in the overloaded `look` command so that the no-args case doesn't attempt to find a target; added a couple test cases to prevent this from being missed in the future.
Bug fixing
=> Fix bug in the container contrib "look"

evennia/contrib/grid/xyzgrid/commands.py
I noticed on the xyzgrid tutorial (https://www.evennia.com/docs/latest/Contribs/Contrib-XYZGrid.html?highlight=xyzgrid#installation) you can teleport using the z-coordinate, such as, "teleport (3,0,the large tree)", but once there on that map, you cannot teleport without the z-coordinate. For example, "teleport (4,1)".
The document says you should be able to teleport within the same map without a z-coordinate.
The error message, btw, is "Z-coordinate is also required since you are not currently in a room with a Z coordinate of its own."
As noted by CatDadKai, the self.caller.xyz was being called, but it should have been self.caller.location.xyz
I did not open an issue for this bug, since it is such a small fix.
=> Fixing Z location in xyzgrid teleport command

CONTRIBUTING.md
The doc links pointed to a dev version that didn't seem to exist.
I changed it to `latest`.
I also changed the markdown for the list, so they don't have the unnecessary indents.
Super minor, not sure if this was intentionally. 
If it was intentionally, just let me know in comments and I will revert that.
It's always nice if contributing.md is up to date :)
=> Broken links in contributing.md

evennia/game_template/server/conf/settings.py
Changes the auto-generated `settings.py` docstring so it has a link to the Default Settings page of the documentation site.
The current settings file is generated with a line pointing to the location of the actual parent settings file on the computer you created the gamedir on. Since the recommended install method now is `pip` and it's discouraged to go digging around in the core library files, and since we have such a nice documentation website, that approach seems obsolete.
=> Point to default settings on documentation site instead of evennia install

evennia/utils/evmenu.py
PR for feature request [#3244](https://github.com/evennia/evennia/issues/3244). 
The purpose of this change is to optionally provide an EvMenu node with a dictionary that acts as tooltip-like entries for displaying text without having to jump nodes. Discussed in discord chat. 
With this fix, optional dictionary parsing happens in the evmenu `parse_input` function. I initially wrote the feature in the `goto` function (under the `is_iter(nodetext)` check) with a new, separate variable to hold the tooltip dict, but ended up opting for the solution which made the least amount of changes (the `goto` change required a new, duplicate formatter and more nested checks under the `is_iter(nodetext)` check). 
Evmenu tests currently don't seem to cover helptext. Is it needed for this change?
=> EvMenu Tooltip Functionality

evennia/contrib/rpg/traits/traits.py
The base `Trait` string conversion references a data value which the `CounterTrait` doesn't have, causing a traceback when printing a counter trait. This adds a `__str__` method to `CounterTrait` to correct that.
Bug fixing
=> Fix traceback on printing `CounterTrait`

evennia/__init__.py
Scripts are only supposed to run in server mode however after recent changes, they start up in both server and portal.
It's supposed to work like this.
Changes introduced in PR https://github.com/evennia/evennia/pull/3187
=> Only start GLOBAL_SCRIPTS in Server mode

evennia/game_template/server/conf/mssp.py
According to https://mudhalla.net/tintin/protocols/mssp/ "Evennia" is a recognized value for FAMILY now, so we no longer need to identify ourselves as "Custom"
=> Update MSSP value

evennia/objects/objects.py
Missing `.items()` method causes a traceback when attempting to create objects with initial nattributes
Bug fixing
=> Fix nattributes typo

evennia/objects/objects.py
Three occurrences of 'return_apperance' are changed to 'return_appearance' in evennia/objects/objects.py
To fix documentation typos
=> fix return_appearance typo

evennia/web/static/webclient/js/plugins/goldenlayout.js
#2247 
**Brief overview of PR changes/additions**
- Introduced a jQuery listener on the #layoutName input field.
- Automatically disables the "Save" button (class .savelayout) if the input is exactly "default".
- Re-enables the "Save" button for other input values.
- This change ensures that users don't have the perception that they can overwrite the default layout.
**Motivation for adding to Evennia**
- I'm still learning the engine, but excited to contribute to the web site of things!
**Other info (issues closed, discussion etc)**
- This change was inspired by an observed behavior where users would often mistakenly try to save a new layout as "default".
- By disabling the button for this specific input, we add a subtle hint to the user about the importance of this default name and guide …
=> added listener + logic to Webclient Save Layout button -  #2247

evennia/settings_default.py, evennia/web/utils/adminsite.py
Currently, the EvenniaAdminSite's get_all_apps method filters out any app which doesn't exist in its app_order listing.
This replaces that logic to allow settings.py to provide priority ordered listing to a selection of apps, and also to provide a list of apps which can be excluded from the listing.
Now it is possible to use the Django Admin properly for any added models.
The Django Admin is currently filtering out access to models from various Django plugins/libraries like Django Wiki and Django Helpdesk, as well as any models I might create in my projects.
An extendable, more generic approach is far better.
The Django Admin site doesn't nicely categorize the displays of where models come from. I wish it displayed in categories like "Here are Evennia models", "Here are wiki models", …
=> Configurable Django Admin

evennia/__init__.py, evennia/server/server.py, evennia/utils/containers.py
Currently, Global Scripts are started at the end of evennia._init(), which is called by both the portal and the server. The GlobalScriptContainer is also having trouble distinguishing "scripts defined in its settings.py section" from "ALL Scripts which have no db_obj attached" and tries to start them all...
Not only that, but the scripts are starting before at_server_init() and all startup hooks are called, so they might fire off before the game has finished loading critical resources.
Even if it's running on the portal.
To combat this, I moved the GLOBAL_SCRIPTS.start() to the very end of the server startup process, after calling startup hooks.
The above is definitely not something we want happening.
=> Alter Global Scripts handling

evennia/commands/default/account.py, evennia/utils/optionhandler.py
Simply alters the output type of OptionHandler.set() so that it returns the BaseOption that was matched, allowing access to its methods and properties like .key and .display() by other systems.
I'm implementing a lot of various things which use OptionHandler, and having access to what was .set() will help with output formatting considerably.
=> Improve OptionHandler.set()

evennia/utils/optionclasses.py
ensure that BaseOption.display() always returns a string.
Turns out this wasn't actually minding its own API; sometimes it would return a number or some other value.
Not everything that wants to use it liked that...
=> Fixing output of BaseOption.display to always be str

docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Rooms.md
Corrects `evadventure.EchoingRoom` to `evadventure.rooms.EchoingRoom`
I'm not sure why github decided that I'd changed the last line as well, they look identical to me
=> Fix typo in tutorial

evennia/commands/default/building.py, evennia/commands/default/tests.py, evennia/contrib/tutorials/batchprocessor/example_batch_cmds_test.ev, evennia/objects/objects.py
All locations in the default building commands which use create_object now call two additional hooks:
builder.can_build_object(), which can generate arbitrary errors if, for some reason, the builder CANNOT currently build that object,
and new_thing.at_object_construction(builder), which is called shortly after the object is created. As it's aware of who made it, it can check them for things like build modes, information about their current location or whatnot, and this can be used for auto-tagging, quota implementation, any number of things.
This will make building complex game grids easier and more powerful through easier implementation of complex building rules and logical grouping of created objects without needing to completely re-implement perfectly working build commands like Dig.
=> Building Command Hook Improvements

evennia/contrib/grid/xyzgrid/README.md
The previous code block contained programmatic errors.
=> Fixing Code Typos in Readme for XYZContrib

Dockerfile
Addressing evennia/evennia#3336
Taking the assumption that the user creation was commented out for a reason and following suit by fixing this to work without it.
=> Fixes evennia/evennia#3336 - Dockerfile's ONBUILD command fails at --chown=evennia

evennia/commands/default/building.py, evennia/commands/default/general.py, evennia/comms/comms.py, evennia/comms/models.py, evennia/locks/lockfuncs.py, evennia/locks/lockhandler.py, evennia/typeclasses/models.py, evennia/utils/evmenu.py, evennia/utils/evmore.py
Tweaked a few uses of hasattr and made a few other minor adjustments where Evennia tries to detect the "account" property to determine if it's looking at an Account or an Object.
I did this by altering hasattr(target, "account") to hasattr(target, "has_account") since DefaultObject has that method and Accounts do not.
Although Evennia itself doesn't strictly need this, one of the projects I'm trying to integrate adds models that establish a OneToOneField to the Django User (settings.AUTH_USER_MODEL, etc). Since this means that Accounts have a .account, it sends Evennia's code off on a wild goose chase and breaks things.
The library in question is Pinax's django-user-accounts, which adds quite an array of features. You might wanna check it out.
Everything appears to be working.
=> Adjusted checks for Object/Account to prevent conflicts.

evennia/commands/cmdset.py, evennia/commands/command.py
This simply modifies CmdSet.add() to stamp each newly added command with cmd.cmdset_source = self
So, Commands now know EXACTLY which CmdSet they came from.
This allows a Command to reference properties, methods, state, etc, on their CmdSet, which can be useful in a number of ways.
See, for instance, creating a kind of pseudo-menu which is aware of all of the commands available to the 'menu'.
This is such a tiny - but useful - change, it doesn't appear to cause any issues.
=> Add Command.cmdset_source

evennia/locks/lockhandler.py
Enable lockfuncs to be aware of the access_type they are checking for.
Although not helpful in many simple cases, if developing complex permission structures with indirection, a lockfunc knowing what kind of access_type it's checking for can allow for more flexible infrastructure.
Nothing that strikes me.
=> Lockfuncs are now called with an access_type kwarg in their **kwargs

evennia/commands/default/help.py
CmdHelp was using old protocol_key strings for trying to detect if the session was a webclient.
They have been updated.
This feature was broken and needed to be fixed?
=> Fixed stale protocol keys in CmdHelp

evennia/accounts/accounts.py, evennia/commands/cmdhandler.py, evennia/commands/default/building.py, evennia/commands/tests.py, evennia/objects/objects.py, evennia/server/serversession.py
Reworked some of the cmdhandler guts to grow more agnostic of the KINDS of objects it can be executing commands from, without breaking existing conventions.
The current cmdhandler code is very messy and not very pythonic; it's also difficult to extend in ways that challenge the internal architecture of Evennia itself. These alterations are a major step in divorcing the process of merging cmdsets from the triad of (session, account, object). It is now possible to add MORE "command-providing objects".
evennia.commands.default.tests.TestCmdTasks.test_new_task_waiting_input keeps failing and I have no idea why.
=> Streamlined cmdhandler to support more extension.

evennia/server/portal/amp_server.py
Currently, AMP sets an attribute of `server_restart_mode` on the portal to the restart mode when the server is being stopped - however, it never resets it on reconnect.
This just sets it to `None` on server connect regardless of mode.
Making that flag actually potentially useful. 👍
=> Reset portal's `server_restart_mode` on server start

evennia/contrib/game_systems/gendersub/gendersub.py, evennia/contrib/game_systems/gendersub/tests.py
Changes `gendersub.GenderCharacter` to reference `from_obj` when replacing pronouns instead of always using the object being messaged. Also adds a test to catch this issue in the future.
Bug fixing.
Brought to my attention on Discord
=> Fix gendersub contrib's gender sourcing

evennia/server/inputfuncs.py
This changes causes _on_monitor_change to first separate out the category from the attribute field name in order to properly reference the attribute on the object.  This fixes errors such as:
File "C:\Users\Scyfris\Projects\norn\evennia\evennia\scripts\monitorhandler.py", line 118, in at_update
callback(obj=obj, fieldname=fieldname, **kwargs)
File "C:\Users\Scyfris\Projects\norn\evennia\evennia\server\inputfuncs.py", line 425, in _on_monitor_change
callsign = {outputfunc_name: {"name": name, "value": _GA(obj, fieldname)}}
AttributeError: 'Attribute' object has no attribute 'db_value[base]'
This is a follow-up fix for closed issue #3307 that I found after some fixes.
This is used in a custom client requiring to access attributes with categories.
Relates to closed issue #3307
=> Fix issue with helper func _on_monitor_change

evennia/settings_default.py
Fixes `webclient.ajax` in the class path to the correct `webclient_ajax`
Bug fixing
Resolves #3362
=> Fix typo in new default AJAX setting

evennia/accounts/accounts.py, evennia/locks/lockhandler.py, evennia/objects/objects.py, evennia/objects/tests.py
Where relevant, typeclass objects now have a new classmethod: generate_default_locks(), which is used to generate lockstrings for .create()
The lockhandler now has better logic for handling empty strings.
The enhancements to the lock system I'm adding to Athanor exposed that Evennia doesn't know what to do if the lockhandler.add() is fed an empty string, and that .create() will explode if .lockstring is empty since an empty string can't be .format()'d...
This change makes it more flexible, while remaining backwards compatible.
=> Improved lock-setting logic

evennia/server/portal/webclient.py, evennia/server/portal/webclient_ajax.py, evennia/web/static/webclient/js/evennia.js, evennia/web/templates/webclient/base.html
Generates a low-security unique ID on loading a new webclient page, so that multiple pages associated with a single browser session properly count as their own play sessions.
Resolves #3327
Quick note: while there is a more cryptographically sound UUID generator available in modern browsers via the `crypto` library, its usage is restricted to secure contexts. Since Evennia doesn't require running a server with HTTPS and individual tabs on a single browser don't actually need to be guaranteed unique on a large scale, I opted for a quicker and more widely functional generator function.
=> Add a unique ID to each webclient instance

evennia/contrib/rpg/rpsystem/rpsystem.py
Changes the prefix marker to be settings-defined, with '/' as a fallback instead of hardcoded.
I also embedded the prefix into the docstring for CmdEmote to avoid the command's help text being confusing; not sure if this breaks any rules, though.
Convenience!
=> Add a reference prefix setting to rpsystem

evennia/commands/cmdhandler.py
The recent refactor of the cmdhandler changed the expected return types to be handled when merging cmdsets, but missed changing the error-case fallback to match, causing additional errors when encountered.
Bug fixing
=> fix _get_cmdset return type

evennia/help/utils.py
The LUNR list of ignored words included "where", and it is a common MUD command for checking player locations! I added it to the words that the search filter for help files should actually not ignore.
An alpha tester on Song of Avaria noticed that HELP WHERE did not work, and after an hour and a half or so of very confused debugging through all my custom help command methods as well as core, I realized that there was actually no glitch or bug at all. It was a very simple fix to add a word to the stopwordfilter settings, and everything was working exactly as intended after all.
Since "where" is a pretty common MUD command, it would be beneficial to add to core in order to help others avoid this kind of confused diving. Thanks to the player of Illi for noticing and reporting this issue! …
=> Added "where" to stop word filter exceptions.

evennia/game_template/gitignore
Adds a gitignore line in the game template for the standard VS Code config location to go along with the PyCharm one
=> Add VS Code config to gitignore

evennia/contrib/grid/extended_room/extended_room.py
1. Renamed the loop variable in the for loop to tod to avoid shadowing the current_time_of_day.
2. Used a loop for applying the regex substitutions to make the code more concise and easier to maintain. This change fixed the main issue, ensuring that current_time_of_day retains the correct value from self.get_time_of_day() throughout the function.
3. Ensured that the current_time_of_day is correctly used for the regex lookup.
Prior implementation did not correctly update room description on first instance of call, only on subsequent iterations. With this change, entering/looking at a room now displays the proper description instead of one that is potentially incorrect.
Resolves #3340
=> Fixing Replace Legacy Time of Day Markup

evennia/game_template/typeclasses/characters.py
Simply fixes a mistake in a variable name in a doc string.
Before: `pre_logout_location`
After: `prelogout_location`
This is how the variable is actually used in the code:
```py
def at_pre_puppet(self, account, session=None, **kwargs):
...
if self.location is None:
location = self.db.prelogout_location if self.db.prelogout_location else self.home
```          
> My goals are beyond your understanding.
Nah, just kidding. I got tripped up with this one, and want to fix so that other people don't make the same mistake :)
No
=> Fixes incorrect variable name in a doc string

evennia/web/templates/webclient/base.html
The core website provides a blank `custom.css` file you can replace to add style overrides into without having to copy the whole core stylesheet into your repo.
This PR just adds the same mechanism to the webclient page, for the same purpose.
Requested feature on Discord
=> Add an option for custom style overrides to the webclient

evennia/contrib/grid/wilderness/tests.py, evennia/contrib/grid/wilderness/wilderness.py
The current logic for moving into a wilderness room completely falls apart if the room already exists - most notably, the object-leave hooks for any prior locations never get checked. Additionally, it contains a lot of redundant checks.
This fixes the logic and makes it more concise.
Bug fixing.
=> Fix underlying logic for moving in and out of Wilderness areas

evennia/contrib/game_systems/crafting/crafting.py
Replaces the example recipes if you've set your own recipe modules, rather than forcing people's games to either include them or go out of their way to hack them back out.
I need to not have these recipes in my game. >.>
=> Override example crafting recipes

evennia/commands/default/comms.py
The boot_user method uses nicks.get without specifying it wants a tuple, so if there is only one matching nick it tracebacks.
bug fixing
traceback from discord:
```
> @chan/ban discord=testius
Are you sure you want to ban user testius from channel(s) discord (make sure name/channels are correct) Y/N?
> y
Error in ask_yes_no. Choice not confirmed (report to admin)
File "/home/redacted/evennia/evennia/evennia/commands/cmdhandler.py", line 628, in _run_command
ret = cmd.func()
File "/home/redacted/evennia/evennia/evennia/utils/evmenu.py", line 1674, in func
yes_no_question.yes_callable(caller, *args, **kwargs)
File "/home/redacted/evennia/evennia/evennia/commands/default/comms.py", line 1234, in _ban_user
success, err = self.ban_user(chan, target, …
```
=> Fix boot/ban function on channel command

evennia/commands/default/help.py, evennia/game_template/world/help_entries.py, evennia/help/utils.py
Changes the lunr weightings to prevent command aliases from taking matching precedence to command keys. I'm not sure why having the boost weights so close was causing this effect, but it does.
Also removes the "building" default filehelp entry, since it conflicts with the "building" category and is thus inaccessible and confusing as well as being a not-very-useful help file anyway. The existing "evennia" entry is sufficient of an example as well as being potentially useful.
mostly bug fixing
=> Patches to improve "help" usability

evennia/contrib/base_systems/components/README.md, evennia/contrib/base_systems/components/__init__.py, evennia/contrib/base_systems/components/component.py, evennia/contrib/base_systems/components/dbfield.py, evennia/contrib/base_systems/components/exceptions.py, evennia/contrib/base_systems/components/holder.py, evennia/contrib/base_systems/components/listing.py, evennia/contrib/base_systems/components/signals.py, evennia/contrib/base_systems/components/tests.py
**WIP**
This refactors Components to remove limitations and add some new functionality
- Registering a component is now done via Metaclass, which allows components to inherit other components
- Components may now specify a slot name, which is used to determine the attribute to access it from.
This would let us have two components for the same feature, using a different name but the same slot name.
Example: CharacterHealth, ItemHealth, they would both have a distinct name but use the slot health and both
would be accessed using object.health or object.cmp.health
- ComponentHolders (Characters/Objects Etc) will also handle a bit better pulling components from inherited classes, 
such as Mixins
- Components will by default use `__slots__` to be a bit lighter, as they are not intended to …
=> [Components] Refactor Component registering with cherry-picked additions

evennia/contrib/game_systems/clothing/clothing.py
The clothing contrib's inventory command was changed to have the item's name prefaced with (qty) when quantity is greater than 1. The output was also truncated to just the name rather than the name and description. The item's id was dropped as it seemed unnecessary in the list. It is still exposed by "look objectName-itemNumber."
Addresses  #3315
=> Added stacking to the Clothing contrib's inventory command.

evennia/contrib/rpg/rpsystem/rpsystem.py
The update to rpsystem to keep it in line with the recent search refactor failed to pass any of the keyword arguments on to the core search, thus breaking all global and dbref searches.
This fixes that.
Bug fixing
Closes #3439
=> Fix rpsystem search

evennia/objects/objects.py, evennia/utils/tests/test_utils.py, evennia/utils/utils.py
This adds a new utility function, `strip_extra_whitespace`, which compresses down repeating sequences of whitespace, and uses it instead of `.strip()` as the default appearance format method in `DefaultObject.format_appearance`
This change removes the need to have the exit/thing/character items on the same line in the appearance template, which also removes the need to have the line breaks for those items included in their return value.
The current method makes using the appearance template to reorder items more work than it should be, since the get_display methods themselves still need to be overloaded. This change means you can now just change the appearance template itself, as intended.
Additionally, the whitespace function allows you to define your maximum preferred spacing, which is …
=> Removes need for hardcoding line breaks into display hooks

evennia/objects/objects.py
Modifies the docstring for `DefaultObject.get_display_name` to match the recent updates to its functionality.
=> Update `get_display_name` docstring

evennia/objects/objects.py
The form used for describing the absence of a noun is plural, not singular. e.g. "no apples" rather than "no apple".
=> Change comparison for singular vs plural

evennia/contrib/rpg/rpsystem/tests.py, evennia/utils/utils.py
Fixed missing alias display when utils.at_search_result() asks for disambiguation.
Additionally, objects without aliases were showing '[]' (instead of nothing) due to a misplaced 'if'.
Old:
```
More than one match for 'box' (please narrow target):
box-1 []
box-2 []
```
New:
```
More than one match for 'box' (please narrow target):
box-1 [cube]
box-2
```
Unit tests for this only exist as part of contrib/rpg and were testing for the presence of '[]' since this is what at_search_result()  always returned. These test have been updated to test for the new behaviour.
When utils.at_search_result() asks for disambiguation it always lists the aliases as '[]' for every matching object, whether or not it has any (non-pluralisation) aliases. This doesn't seem to be the desired behaviour.
=> Fix aliases not being shown for disambiguation

evennia/commands/default/help.py
Creating a new help entry using the form `sethelp/edit topic` (without `= ...`), results in a NULL/None entry being created in the database which then causes a traceback when issuing `help topic`. This also results in any text entered into the editor for the initial creation being lost.
This change defaults `self.rhs` to an empty string if it is `None` at creation when using `/edit`.
Prevent potential loss of an initial help topic edit.
**Before:**
```
>sethelp/edit test
----------Line Editor [topic test]--------------------------------------------
01|
----------[l:01 w:000 c:0000]------------(:h for help)------------------------
>This is a very important help topic.
01| This is a very important help topic.
>:wq
Saved help entry.
Closing the editor.
```
```
>help
(...) …
```
=> Fix traceback when using sethelp/edit to create a new topic

evennia/utils/utils.py
When `format_grid()` uses `_weighted_rows()` and the last item on a row spills over into the last column (as it is allowed to do), the first item of the next row is lost.
This can be demonstrated using `help` with a clean game installation and a client width of 88 (see *other info* section).
Fix grid items not being displayed under certain conditions.
**Note:** I have only tested this change using help and do not know if it might negatively impact other areas where `format_grid()` is used.
**Before:**
```
>help
-------------------------------------------Commands------------------------------------------
-- Admin ------------------------------------------------------------------------------------
ban          boot         emit         perm         unban        userpassword …
```
=> Fix weighted_rows() sometimes 'losing' items

evennia/help/filehelp.py, evennia/help/tests.py
The categories of help topics in files are not lower-cased when they are read which results in the appearance of duplicated categories in the "Game & World" section of the help index when a database help topic is added, as database topic categories are forced to lower-case when created. This also happens if file topics are created with different category casing.
This also causes the default 'evennia' help topic not to be listed when doing `help general` as it is created with a category of 'General' but the query is 'general'.
Command help topics do not have this problem even if their casing is different.
This fix forces the categories of file help topics to lower case when they are read. See *other info* section for examples.
Prevent "duplicated" help categories.
**Before:**
```
>sethelp …
```
=> Fix file help topic category casing differences appearing as duplicates

evennia/commands/default/help.py, evennia/commands/default/tests.py
Add `sethelp/category` switch to change the category of a database help topic.
There was no in-game way to change the category of a database help topic once created.
I wasn't sure exactly how to represent the usage for this but I gave it my best guess based on other help topics.
**Examples:**
*Note that the filehelp topic 'evennia' is not present in these examples. See https://github.com/evennia/evennia/pull/3457.*
```
>help
(...)
test      test2                                                                              
```
```
>sethelp/category test2 = misc
Category for entry 'test2' changed to 'misc'.
```
```
help
(...)
-- General ----------------------------------------------------------------------------------
test …
```
=> Add sethelp/category switch for changing database help topic's category

evennia/contrib/game_systems/crafting/crafting.py, evennia/contrib/game_systems/crafting/tests.py
The `msg` method used by crafting recipes has faulty syntax, resulting in the outgoing text kwargs being interpreted as the `from_obj` keyword argument.
Bug fixing
=> Fix traceback in crafting system recipe.msg

evennia/utils/eveditor.py, evennia/utils/tests/test_eveditor.py
When in normal editing mode (i.e. not in code editing mode) and adding lines with extra whitespace (leading or between words) the input echoing does not correctly reflect what is actually added to the buffer (the extra space is stripped).
This fixes the echo to correctly show what is added.
Correct editor echo display.
**Before (in the editor):**
```
>  This  line   has    whitespace.
01| This line has whitespace.
>:
----------Line Editor [topic test]--------------------------------------------
01|   This  line   has    whitespace.
----------[l:01 w:004 c:0033]------------(:h for help)------------------------
```
**After (in the editor):**
```
>  This  line   has    whitespace.
01|   This  line   has    whitespace.
>:
----------Line Editor [topic …
```
=> Fix editor echo not displaying correctly for lines with whitespace

docs/source/Components/EvEditor.md, evennia/utils/eveditor.py
Correct the help for the editor's `:p` command. The help states that it pastes the line after `<l>`, but it actually pastes it before `<l>` (see *other info*).
Correcting help/documentation.
```
>:
----------Line Editor [desc]--------------------------------------------------
01| line 1
02| line 2
03| line 3
----------[l:03 w:010 c:0051]------------(:h for help)------------------------
```
```
>:y 3
Line 3, ['line 3'] yanked.
```
```
>:p 1
Pasted buffer ['line 3'] to line 1.
>:
----------Line Editor [desc]--------------------------------------------------
01| line 3
02| line 1
03| line 2
04| line 3
----------[l:04 w:012 c:0058]------------(:h for help)------------------------
```
=> Correct help for editor's paste command

evennia/commands/default/building.py, evennia/commands/default/tests.py
Adds `alias/delete` switch to allow deletion of a specific alias. For simplicity's sake, it deletes the specified alias from all categories.
There was no (non-Python) way to delete a specific alias without deleting them all and re-adding the ones you wanted.
```
>alias box
Aliases for box: 'a box'[category:'plural_key'], 'one box'[category:'plural_key']
```
```
>alias/category box=cube:geometry
Alias(es) for 'box' set to 'a box,cube,one box' (category: 'geometry').
```
```
>alias/category box=cube:shape
Alias(es) for 'box' set to 'a box,cube,cube,one box' (category: 'shape').
```
```
>alias box
Aliases for box: 'a box'[category:'plural_key'], 'cube'[category:'geometry'],
'cube'[category:'shape'], 'one box'[category:'plural_key']
```
```
>alias/delete box=cube
Alias 'cube' deleted from …
```
=> Add alias/delete switch

evennia/objects/objects.py, evennia/objects/tests.py
Adds support for a `kwarg` '`no_article`' to `get_numbered_name()`. When set to `True` and `count` is 1, it will return the key as-is without an article.
See below for usage and examples.
(Thanks to Inspector Caracal for the brainstorming on this one.)
Adds support for making the names of proper-named objects scan better.
```
from typeclasses.objects import Object
class ProperNamedObject(Object):
"""
This is a base class for objects that have a proper name, for example "The One Ring'.
The effect of using this class is that the object's numbered name will not include the
indefinite article when there is only one of them in scope.
"""
def get_numbered_name(self, count, looker, **kwargs):
return super().get_numbered_name(count, looker, no_article=True, **kwargs)
```
```
>create The One Ring …
```
=> Add support to get_numbered_name() for omitting the article

evennia/commands/default/general.py, evennia/commands/default/tests.py
This adds a barebones syntax for pulling the number out of a command argument on get, drop, and give - and more significantly, makes the command funcs therein able to handle moving around multiple objects.
Being able to get, give, and drop multiple of an object is an extremely common and fairly fundamental feature that the vast majority of people using Evennia wind up implementing. I consider it's nearly as fundamental as multimatching, honestly. And since the object search itself supports stacking, it seems reasonable that these basic object manipulation commands should also support stacking.
This doesn't work as smoothly as it should, at the moment, due to the bug described in #3432. Since the pluralization search isn't working correctly, for whatever reason, `get 3 rocks` will only …
=> Add the ability to get/give/drop stacks of things

evennia/objects/objects.py
The code checks if the key `"you"` exists, but then adds a key of the actual object referenced by `you` instead of using the string. This seems an evident typo preventing the intended `"{you} does something with {obj}."` third-person functionality.
bug fixing
=> Fix typo in default `msg_contents` mapping

evennia/objects/objects.py
The recent addition of the `filter_visible` method didn't include the check to make sure the viewer isn't included.
Bug fixing
=> Exclude viewer from displayed contents

evennia/commands/default/building.py
Added a missing closing bracket to the `sethome` message:
```
>sethome me = here
Home location of Chiizujin was changed from Limbo(#2 to Limbo(#2).
|
V
>sethome me = here
Home location of Chiizujin was changed from Limbo(#2) to Limbo(#2).
```
Typo fix.
=> Add missing bracket in sethome message

evennia/objects/objects.py, evennia/objects/tests.py
Adds an optional `exit_order` kwarg to `get_display_exits` to allow the sorting of exits in a specified order. 
Exits are specified as an `iterable` of `str`. Any exits not specified will be appended to the end in alphabetic order.
Allow for a specific/preferred order of exit names in room descriptions rather than them appearing in creatiom order.
=> Add exit_order kwarg to get_display_exits to sort exit names

evennia/contrib/rpg/traits/traits.py
* Obligatory Linter PEP adherence.
* CounterTrait calls `validate_input` after a server reload. Previously, this method would default `._data['last_update']` to the current time making rate freeze until trait referenced. Fix has `validate_input` check for an existing last update before assigning it the default value `time()`. #3317
=> CounterTrait now checks for last_update before defaulting to current time.

evennia/utils/utils.py
The docstring is unclear and states that the `adjective` keyword argument is supposed to be an integer, which is incorrect.
=> Fix int2str docstring

evennia/utils/eveditor.py
When using the search/replace function in the editor, the feedback message displays incorrectly if markup is involved.
Bug fix.
**Before**
```
>:
----------Line Editor [topic test]--------------------------------------------
01| A line with |rred text|n in it.
----------[l:01 w:007 c:0031]------------(:h for help)------------------------
```
```
>:s \|r |b
Search-replaced \ ->  for lines 1-1.
```
In the above message, `->` is displayed in red and `for lines 1-1.` is displayed in blue. The message also doesn't reflect what was changed since the markup has been replaced with ANSI codes.
```
>:
----------Line Editor [topic test]--------------------------------------------
01| A line with |bred text|n in it.
----------[l:01 w:007 c:0031]------------(:h for help)------------------------
``` …
=> Fix editor search/replace feedback when replacing markup

evennia/contrib/grid/wilderness/wilderness.py
When navigating the wilderness as an Admin you can see exits that are otherwise invalid.  If you try to use one of these invalid exits, you will encounter stack traces and your character will get stuck unable to teleport themselves out.  You have to go ooc, switch characters, teleport them to safety, and switch back.
Suggested this to `evennia-minimud` but it was rejected on the grounds that the issue is with the contrib, so I'm suggesting it here.
Probably not relevant, but since I mention it above, that rejected pull request:
https://github.com/InspectorCaracal/evennia-minimud/pull/10
=> Prevents admin from walking out non-existent exits in the wilderness

evennia/commands/default/building.py
When rooms are created in-game with `dig` or `tunnel`, the feedback message shows the room's name/key instead of its typeclass path.
Bug fix.
**Before**
```
>dig cave1
Created room cave1(#3) of type cave1.
```
**After**
```
>dig cave2
Created room cave2(#4) of type typeclasses.rooms.Room.
```
=> Fix room creation showing room name instead of typeclass path

evennia/commands/default/help.py
When database help topics are created with a name that overlaps a non-database help topic, the database topic can no longer be edited in any way, including deletion.
Bug fix.
**Before:**
```
>sethelp ban = Test.
Warning:
'ban' matches (or partially matches) the key/alias of Command 'ban'.
Command-help take precedence over other help entries so your help *may* be
impossible to reach for those with access to that command.
Do you still want to continue? Y/[N]?
>y
Topic 'ban' was successfully created.
```
```
>sethelp/replace ban = Test 2.
Warning:
'ban' matches (or partially matches) the key/alias of Command 'ban'.
Command-help take precedence over other help entries so your help *may* be
impossible to reach for those with access to that command.
Do you still want to continue? Y/[N]?
>y …
```
=> Fix inability to edit, delete (etc.) help topics whose names overlap non-db topic names.

evennia/prototypes/menus.py
When setting a prototype parent in the prototype wizard, an exception is raised in the console. No feedback is given in the wizard itself other than `[No prototype_parent set]` being displayed for the current parent.
This fixes the exception, allowing the parent to be set: `Selected prototype parent test.`
Bug fix.
**Exception:**
```
File "/home/chiizujin/Data/Source/Python/Evennia-contrib/evennia/evennia/commands/cmdhandler.py", line 754, in cmdhandler
raise ExecSystemCommand(syscmd, sysarg)
evennia.commands.cmdhandler.ExecSystemCommand: (<evennia.utils.evmenu.CmdEvMenuNode object at 0x7f8a2cc99a50>, '1')
During handling of the above exception, another exception occurred:
File …
```
=> Fix traceback when setting prototype parent

evennia/prototypes/spawner.py
Fixes behaviour in https://github.com/evennia/evennia/issues/3505.
This was caused by the spawned object being used as a comparison for the update directly updating the dict in the prototype cache if it found one, rather than copy of it. This resulted in the cached prototype  being changed to reflect the spawned object.
Bug fix.
Note that this does *not* change the repeated save request behaviour mentioned in the bug report.
**Before**
Starting with an object spawned from a prototype and then adding a new tag ('tag_on_object') directly to the object:
```
>tag test
Tags on test: 'tag_on_object', 'test' (category: from_prototype)
```
Add a new tag to the prototype:
```
Actions: examine <num> | remove <num>
Back (attrs) | Forward (locks) | Index | Validate prototype | Quit
1: new_tag …
```
=> Fix protoype object updates changing cached prototype

docs/source/Components/FuncParser.md, evennia/utils/funcparser.py, evennia/utils/tests/test_funcparser.py, evennia/utils/verb_conjugation/conjugate.py
This adds much-needed support to `$pron` and `$conj` equivalent to `$you` of providing object keys from a provided mapping, as well as an alternate conjugation function, `$pconj`, intended to be used in conjunction with `$pron` instead of `$you`
The added functionality allows you to do messages like this:
```
> py here.msg_contents("$You() $conj(narrow) $pron(your) eyes at $you(test), watching as $pron(you, test) $pconj(drinks, test) the whole thing.", from_obj=self, mapping={'test': self.search('test')})
```
> Your view: `You narrow your eyes at test, watching as they drink the whole thing.`
> The other character's view: `admin narrows his eyes at you, watching as you drink the whole thing.`
After changing the test character's gender to female:
> Your view: `You narrow your eyes at test, …
=> Adds support for mapping keys, pronoun-verb agreement to actor stance callables

evennia/objects/objects.py
Providing an empty list of search candidates currently results in the unexpected behavior of falling back to the default search candidates rather than finding nothing. This replaces the truthiness check to more explicitly verify that the candidates are not the default kwarg of `None`
Bug fixing
=> Don't ignore empty search candidates

evennia/utils/containers.py
There is no `scripts` attribute on the `GlobalScriptsContainer` class; the correct attribute is `loaded_data`, as is done in the base `Container` class. As a result, attempting to do `GLOBAL_SCRIPTS.all()` currently results in the following traceback:
```
File "./evennia/evennia/utils/containers.py", line 247, in all
return self.scripts.values()
^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'values'
```
Bug fixing
Reported on Discord
=> Fix `GlobalScriptsContainer` scripts attribute reference

evennia/objects/objects.py
Fixes cases where exits not specified in the sort order were not appearing at the end of the list as they should.
Bug fix.
**Before:**
`Exits: north, hatch, and southwest`
**After:**
`Exits: north, southwest, and hatch`
=> Fix exit order sorting sometimes being incorrect for exits not in the sort order

evennia/server/portal/telnet_oob.py
Changes the GMCP command encoding to only run capitalize() on command parts that are not fully uppercase.
A previous conversation on Discord identified the current GMCP encoding's command capitalization as somewhat lacking, based on their own previous use of GMCP in other MUD libraries. Additionally, today a specific use-case arose that is currently impossible: sending a Mudlet package install command, as per [the Mudlet docs](https://wiki.mudlet.org/w/Manual:GMCP_Extensions) - it requires the ability to send a fully capitalized command section, `Client.GUI`.
I'm not extremely familiar with the specifications of the GMCP protocol, so I wrote this under the assumption that mixed-case command parts are not allowed.
=> Support full capitalization in GMCP commands

evennia/contrib/game_systems/achievements/README.md, evennia/contrib/game_systems/achievements/__init__.py, evennia/contrib/game_systems/achievements/achievements.py, evennia/contrib/game_systems/achievements/tests.py
Adds a new contrib which provides a mechanism for tracking and checking game achievements.
=> Achievements contrib

evennia/utils/eveditor.py
Adds the ability to optionally specify a width for the editor's `:j` and `:f` commands. Changes `<w>` (alignment) to `<a>` in help so that `<w>` can be used to represent width.
A new syntax element (`=`) had to be introduced to prevent a clash between the numeric arguments `<l>` and `<w>` when some arguments are omitted (e.g. does `:j 10` mean 'justify line 10' or 'justify to width 10'?)
New feature.
```
>:
----------Line Editor [topic test]--------------------------------------------
01| A long line of text to test the editor's justification command with a custom
width.
----------[l:01 w:015 c:0083]------------(:h for help)------------------------
```
```
>:j
Full-justified lines 1-1.
>:
----------Line Editor [topic test]--------------------------------------------
01| A  long  line of …
```
=> Add width argument to editor's :j and :f commands

evennia/commands/default/comms.py
Fixes the `page/list` command not showing received pages. Resolves https://github.com/evennia/evennia/issues/3528.
Also re-words the "You haven't paged anyone yet." message to something more appropriate.
Note that this only applies to legacy pages (i.e. those with no locks at all, which would already be showing correctly) and pages sent after this fix. It does not fix existing pages with locks that do not include the receiver.
Bug fix.
**Before:**
Player account 'Lancelot'.
```
page
You haven't paged anyone yet.
```
```
Account Chiizujin pages: What is your favourite colour?
```
```
>page
You haven't paged anyone yet.
```
```
>page chiizujin Blue.
You paged Chiizujin with: 'Blue.'.
>page
Your latest pages:
06:23:19 to Chiizujin:> Blue.
```
**After:**
```
>page
You haven't sent or received …
```
=> Fix page/list command not showing received pages

evennia/utils/eveditor.py
If an exit's direction command exists in your current location, then `EvEditor` will treat matching input as those commands and move you around the game.
This is fixed by using the same priority for `EvEditorCmdSet` as already exists for `SaveYesNoCmdSet` (150).
Bug fix.
**Before:**
```
>desc/edit
----------Line Editor [desc]--------------------------------------------------
01| This is a room.
----------[l:01 w:004 c:0015]------------(:h for help)------------------------
>e
room2(#51)
This is a room.
Exits: west
```
**After (in the same initial room):**
```
>desc/edit
----------Line Editor [desc]--------------------------------------------------
01| This is a room.
----------[l:01 w:004 c:0015]------------(:h for help)------------------------
>e
02| e
```
=> Fix EvEditor responding to valid direction commands in the current location

evennia/contrib/base_systems/components/component.py, evennia/contrib/base_systems/components/tests.py
Since the last refactoring, the `_fields` in components is getting improperly set.
This fix modifies the metaclass constructor to ensure that the dict is properly set for each component once.
I have added a test and tested locally, I think this fix should work.
It's likely not the most elegant but since lyrewyn told me about the issue and I don't know how long it will take me
to refine, so I am opening as is for now.
Bugfix
=> [Components] Fix components improperly setting _fields

evennia/contrib/rpg/character_creator/README.md, evennia/contrib/rpg/character_creator/character_creator.py
The contrib's account currently uses the default `ooc_appearance_template` string, which doesn't match the contrib's modified `charcreate` command usage. This corrects that oversight, and modifies the documentation accordingly.
=> Update contrib account for character creator

evennia/commands/cmdhandler.py
This corrects two issues that have arisen recently on Discord:
- The "fallback" value when merging a cmdset uses a list containing a value of `None`. Should this fallback actually get used, `None` is treated by subsequent code as a cmdset and tracebacks.
- There is no validation on `report_to` having been set before attempting to message errors to the object.
Bug fixing
=> Fix cmdhandler error-handling issues

evennia/contrib/rpg/character_creator/README.md, evennia/contrib/rpg/character_creator/character_creator.py
The previous update adding auto-look back to the chargen menu neglected to include the session, causing errors.
Also, I originally neglected to include the override to the `ic` command in the contrib which is supposed to prevent you from puppeting an in-progress character; I added that back in and updated the instructions.
Bug fixing
Thanks to Uncle Buff on discord for catching these
=> Fix character creator contrib commands

evennia/web/templates/website/channel_detail.html, evennia/web/templates/website/channel_list.html, evennia/web/templates/website/character_form.html, evennia/web/templates/website/character_list.html, evennia/web/templates/website/character_manage_list.html, evennia/web/templates/website/generic_form.html, evennia/web/templates/website/help_detail.html, evennia/web/templates/website/help_list.html, evennia/web/templates/website/object_confirm_delete.html, evennia/web/templates/website/object_detail.html, evennia/web/templates/website/object_list.html, evennia/web/templates/website/registration/password_change_done.html, evennia/web/templates/website/registration/password_change_form.html, evennia/web/templates/website/registration/password_reset_complete.html, evennia/web/templates/website/registration/password_reset_confirm.html, evennia/web/templates/website/registration/password_reset_done.html, evennia/web/templates/website/registration/password_reset_form.html, evennia/web/templates/website/registration/register.html
This changes the extensions of "base.html" in the website templates to the more accurate and specific "website/base.html"
The current templates will use any `base.html` template provided in the game dir as first priority, resulting in most of the website breaking if you create your own webclient base template.
=> Update web templates to use correct base.html

docs/source/Concepts/Colors.md
This PR clarifies that brightness is boldness, fixes a broken link, and adds info on 24-bit color.
I built it with Sphinx to double-check it
I suck at ANSI colors and didn't know that bright == bold
=> docs update: fix Understanding Color Tags link, add true color information

evennia/contrib/rpg/rpsystem/rpsystem.py, evennia/contrib/rpg/rpsystem/tests.py
This PR modifies the `get_search_result` method to avoid erroneous global searches and multimatches, and `parse_sdescs_and_recogs` to correctly remove the multimatch disambiguator from the actual string to be matched
I also added a new test to verify the correct behaviors.
Bug fixing
=> Fix rpsystem contrib searching issues

evennia/utils/ansi.py, evennia/utils/hex_colors.py, evennia/utils/tests/test_truecolor.py
test = evennia.utils.ansi.ANSIString('|#ff0000TEST')
caller.msg(test)
before this PR:
client receives: "\u001b[38;5;196mTEST\r\n"
after this PR:
client receives: "\u001b[38;2;255;0;0mTEST\r\n"
=> add true color parsing to ANSIString

evennia/server/service.py
A tiny update that should provide a decent performance gain for SQLite.
Testing it is a bit of a chore.  I didn't create a test because I wasn't sure how to set up Django's test DB to test this.
I also didn't have luck creating a test which changes the journaling mode automatically because the DB doesn't like doing that at any other time besides startup, it seems.
Test command:
```
import time
from evennia.commands.command import Command
from evennia.utils.create import create_object
class CmdTestDB(Command):
"""
test SQLite speed by creating/deleting 1000 objects
"""
key = 'testdb'
def func(self):
caller = self.caller
count = 1000
start = time.time()
for _ in range(count):
obj = create_object(key='test', typeclass='evennia.objects.objects.DefaultObject')
obj.delete()
elapsed = …
```
=> update SQLite PRAGMAs for faster DB

evennia/contrib/rpg/llm/llm_client.py
Puts the header value in a list.
The content of the headers are expected to be iterables, so passing a string into it causes the header value to be broken up into a list of individual characters, like so:
`Headers({b'content-type': [b'a', b'p', b'p', b'l', b'i', b'c', b'a', b't', b'i', b'o', b'n', b'/', b'j', b's', b'o', b'n']})`
Bug fixing
This isn't a breaking issue when running a local API server like koboldcpp, since they don't validate request headers, but it does completely break with remote APIs so it's better to have the default/example be correct.
=> Fix LLM contrib client headers

docs/source/Components/FuncParser.md, docs/source/Components/Typeclasses.md
typeclasses "subside" (i.e. diminish) -> typeclasses "subsist" (i.e. keep existing, which I think is the intention)
Clarity of documentation
=> Minor typo fixes in documentation

evennia/commands/default/tests.py
This is a fix for https://github.com/evennia/evennia/issues/3596
I'm not entirely sure why it works, but the test reliably passes for me now.
Is the clock advance creating a possible race condition?
`self.task = self.task_handler.add(self.timedelay, func_test_cmd_tasks)`
If the timedelay arg for self.task_handler.add is anything other than `self.timedelay`, it passes reliably for me.
if it's `self.timedelay` then on Windows it will fail 50% of the time or so.
=> make test_new_task_waiting_input more reliable on Windows

evennia/contrib/base_systems/ingame_reports/menu.py, evennia/contrib/base_systems/ingame_reports/reports.py
This fixes a bug caused by several lines of code in the menu having migrated to the wrong part of the function without being caught. It also adds in the usage of `GLOBAL_SCRIPTS` instead of a search, since that is working again.
Bug fixing
=> Update Reports contrib

evennia/contrib/game_systems/clothing/clothing.py, evennia/contrib/game_systems/clothing/tests.py, evennia/objects/manager.py, evennia/objects/tests.py
This PR makes modifications to both the DefaultObject manager methods of `get_objs_by_key_and_alias` and `search_object`.
`get_objs_by_key_and_alias` will now properly respect partial matches in its queries, leading to the expected result of an empty search string partial-matching all candidates and additionally running fewer queries.
`search_object` has been moderately streamlined, removing the need for special-case handling of tags or search terms, and applying all filtering keywords consistently to all types of searches rather than unintuitively picking and choosing based on which combination of keywords were provided.
Usability improvements
The undesirable behavior brought up on Discord where searching with tag criteria but no search string is resolved by this PR. It additionally …
=> Rework Object searching to behave more consistently

evennia/objects/objects.py, evennia/prototypes/spawner.py
This adds two additional hooks to `DefaultObject` and integrates them into the appropriate locations.
1. `at_object_post_creation` - An additional hook which is added to `at_first_save` *after* the attributes etc. from `create_object` or prototypes have been applied. Named to match the pattern of `at_object_post_copy`
2. `at_object_spawn` - A specific hook intended for additional post-spawning processing of updates applied by a prototype. It is called both when the object is initially spawned, and when the object is updated to match any changes to the prototype.
This should fulfill the feature requests and use-case requirements presented in #3095
I played it safe when integrating the new `at_object_spawn` hook into the spawner code and used `getattr`, just in case someone decides to use …
=> Add post-creation and spawn hooks to DefaultObject

docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Django-queries.md
"lycanthropy" was consistently misspelled, and the tutorial was mixed between requiring "exactly 2" for the attribute in the code, while being described as "greater than 2" in some of the text, and the attribute was actually set to 3, preventing the example code from working.
This changes the attribute from 3 to 2 so the example code will work, changes the descriptions where it claimed we were looking for greater than 2 to match, and corrects the misspelling of "[lycanthropy](https://www.merriam-webster.com/dictionary/lycanthropy)".
Fixing typos in the beginner's guide.
=> Fix lycanthropy tutorial

evennia/commands/default/building.py, evennia/typeclasses/attributes.py
Check if attr.strvalue exists before attempting to use it.
When an .ndb.item is set to None, it has no attribute db_strvalue. Later when examining an object we attempt to access its attributes' db_strvalue. InMemoryAttributes only have one if the value is not None.
Alternatively, we may want to set any default db_strvalue (i.e. in InMemoryAttribute's init function), but updating the check accomplishes the same result.
Bug fix
Fix for https://github.com/evennia/evennia/issues/3622 and https://github.com/evennia/evennia/issues/3602
=> Fix for #3622 - check if attr.strvalue exists

docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Equipment.md
The code to replace equipment in a single-item slot referenced a variable that is never used before or after, and incorrectly set it to the item that is doing the replacement instead of the item being replaced, which causes the replaced item to not be moved back into the backpack.
It also incorrectly attempted to append items meant to move to the backpack to the current use_slot, causing an error if the item being moved is not already going to the backpack.
When moving an object into an empty slot, the example code was adding `None` entries into the backpack slots.
Fix broken example code.
=> Fix incorrect example code in equipment tutorial

evennia/contrib/game_systems/storage/README.md, evennia/contrib/game_systems/storage/__init__.py, evennia/contrib/game_systems/storage/storage.py, evennia/contrib/game_systems/storage/tests.py
This contrib adds tag-based off-grid item storage.
Players can store, retrieve, and list items stored in a room. Rooms can be marked as storerooms with the `storage` command by builders. Storerooms can have individual per-character storage or shared storage between all characters able to access the room. When storerooms are removed via `storage/delete`, all stored items are moved to the room contents. Stored items are moved off grid and returned to the grid when retrieved (after an at_pre_move check for both actions).
This is a common feature for MUDs that Evennia doesn't already have as a contrib.
=> Contrib - Item Storage

evennia/accounts/accounts.py
At the moment, the fallback permissions for characters reference the entire permissions handler rather than the permissions within the handler. This causes the undesirable behavior of permission strings like `"developer,player"` being added to new characters, rather than the expected separate permissions of `"developer"` and `"player"`
Bug fixing
=> Fix permission fallback when creating characters

evennia/commands/default/building.py
Using existing option parsing to parse categories in ObjManipCommands, enabling us to include categories in the `cpattr` command.
`cpattr` likely existed before attribute categories, this brings it up to speed.
https://github.com/evennia/evennia/issues/3093
Doubt - the help file examples are pretty unwieldy, so I didn't include `[:category]` everywhere, but I added it in the example given.
=> Add attr:category functionality on cpattr

evennia/objects/models.py
The contents cache handler currently has an oversights when reinitalizing:
1. The typecache is not reset before being initialized in `init`, allowing invalid data to persist and continue erroring.
2. ~~The `load` function includes objects that have been deleted but are still in memory, leading to idcache errors.~~
This PR corrects this.
Bug fixing
Resolves #3646 (or at least the parts of it that weren't my own fault)
=> Properly reinitialize contents cache

evennia/utils/eveditor.py
Changed the default align of the `:j` command in EvEditor to "left", to match both the behaviour indicated in EvEditor help and the default behaviour of `utils.justify`.
Align functionality between Python and in-game, and avoid unintended behaviour!
=> Fix default justify behaviour in EvEditor

evennia/help/filehelp.py
This hashes FileHelpEntry so it can pass equality checks. A lack of this causes `do_search` in help.py to fail at this line: https://github.com/evennia/evennia/blob/88afac2874160bada78189b82eff3782db1705f7/evennia/commands/default/help.py#L505
This is because removal has to check for equality.
Production bug on Secrets of Aelandris breaking several help files
=> Make FileHelpEntry hashable so it does not fail equality checks

evennia/commands/default/tests.py, evennia/objects/objects.py
Fixes issue where renaming an object keeps the old plural aliases.
- Moves plural_category to object level variable
- Modifies DefaultObject `at_rename` hook to clear plural aliases
Fixes issue #3660.
Root cause:
Plural aliases are added in the `DefaultObject.get_numbered_name` method which is called when a character uses `CmdInventory` or `CmdLook`.  If a builder renames an object, but doesn't use a command that calls get_numbered_name, the object can still be referenced by the old aliases.
Closes #3660
=> #3660 bugfix old name saved in alias

evennia/server/serversession.py
This removes a few lines of code which update the `last_login` attribute on Accounts when their session is disconnected.
While it seems this was done deliberately at some point, it doesn't make any actual sense with the intent of `last_login` representing the last time the account logged in. Especially as the most recent account *activity* is iirc tracked elsewhere.
=> Remove last_login update on disconnect

docs/source/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-Python-classes-and-objects.md
Game Template does not actually have `pass` beneath the ObjectParent docstring. In #3661 this was pointed out. PR resolves.
=> #3661 Fixing docstring/game template mismatch.

evennia/commands/default/comms.py
In certain cases, CmdPage can fail with a traceback.
- When attempting to `tell` someone without providing a message
- When attempting to `tell` someone a single-word reply
This fixes the code to prevent those errors.
Bug fixing
=> Fix CmdPage tracebacks

evennia/accounts/accounts.py
Despite using code that assumes username and password are strings, `DefaultAccount.create` currently uses the default fallback value of `None` if they aren't provided.
This updates that to use an empty string instead, and additionally updates `normalize_username` to enforce that the provided username is normalized to a string.
Fixing edge cases
=> Avoid certain tracebacks when creating accounts

evennia/web/static/webclient/js/plugins/goldenlayout.js, evennia/web/static/webclient/js/plugins/options2.js
- Move input focus logic to onActiveMainTabChange hook
- Remove input focus logic from individual component (options)
Fixes bug #3658 Autofocus is not re-enabled after opening options
When options pane is opened it disables the input setKeydownFocus.  It never reenables it unless you specifically close out of it, either with the 'x' icon or clicking the options button until the options tab is removed.
Golden layout already has a hook `activeContentItemChanged` which is already registered to fire custom `onActiveMainTabChange`.  It seemed like a reasonable place to put the logic.  
Closes #3658
=> 3658 bug input autofocus

evennia/utils/funcparser.py, evennia/utils/tests/test_funcparser.py
Addresses some funcparser issues identified in #3692 where funcparser would eat characters.
Fix bugs seen in #3692 
This is not a full fix for #3692 as that specifically requests `help nick` (as the example) to return as it is written, and the parser seems to eat escapes '\' by design.  So in example case the literal
`nick tm\=$1=page tallman=$1` 
becomes
`nick tm=$1=page tallman=$1`
Without the escape character.
=> Fixing funcparser issues

evennia/server/service.py
The server-start code which calls this hook already correctly handles whether or not the session IDs should be cleared or not. The removed code is thus only serving to break session tracking when using `reset` mode.
Bug fixing
=> Remove redundant and incorrect session-clearing from `at_server_cold_start`

evennia/commands/cmdhandler.py
At the moment, the cmdhandler will load all of the command sets on all of the objects in a room when checking for merged commands, *regardless* of whether those objects will even allow you to call the commands on them. In most cases, this has no noticeable effect - however, in cases where there are a large number of commands attached to these objects, it can cause significant overhead by loading those cmdsets, despite them never being used.
This PR moves the lock check on the objects to the portion of the code which builds the list of objects to check, avoiding that cmdset-building for objects that are not callable.
Avoiding certain edge-case lag issues.
=> Avoid loading cmdsets that don't need to be checked

evennia/contrib/grid/ingame_map_display/ingame_map_display.py, evennia/contrib/grid/ingame_map_display/tests.py
```
left ass cheek: Hi - Using the in-game map display contrib, I'm confused how checking for compass directions in exit aliases is supposed to work in this code from exit_name_as_ordinal:
if exit_name not in _COMPASS_DIRECTIONS:
compass_aliases = [
direction in ex.aliases.all() for direction in _COMPASS_DIRECTIONS.keys()
]
if compass_aliases[0]:
exit_name = compass_aliases[0]
if exit_name not in _COMPASS_DIRECTIONS:
return ""
compass_aliases is a list of booleans, which makes sense checking a value with an if statement (although - it only checks north for some reason anyway?) but in the next line, exit_name is set to that boolean value, and then compared to _COMPASS_DIRECTIONS keys, which are strings representing north, south, etc. So since True and False aren't compass directions, the …
```
=> Fix bug that prevented exits with an ordinal alias from displaying

evennia/commands/cmdhandler.py, pyproject.toml
fixes https://github.com/evennia/evennia/issues/3724
twisted.internet.defer.returnValue is deprecated and slated for removal.
bugfix
in the lines i removed(`ret = yield ret`), `ret` is always None or a generator in my testing.... never a Deferred (this is inside func decorated with \@inlineCallbacks).  Since it's not a Deferred I don't think it can be yielded.  Why is it failing now?  Not sure, but Twisted did make a change that allows you to yield coroutines as well, so my best guess is that change is causing it to fail now.
3.13 tests were failing because scipy 1.12.0 wheels weren't available for 3.13...bumped version so tests can run
=> fix create/destroy bug that surfaced in Twisted 24, get rid of some uses of returnValue()

evennia/server/evennia_launcher.py
Whether altgamedir from argparse has set GAMEDIR or not, the GAMEDIR is set based on the present working directory. This stops `evennia --gamedir /some/path/not/the/pwd` from having any effect (tested in podman with `docker.io/evennia/evennia:latest` )
Check if GAMEDIR is set, don't set it again if so
To allow podman to run Evennia with, e.g.,
```podman run -it --rm -p 4000:4000 -p 4001:4001 -p 4002:4002 -v /path/to/my/games:/usr/src/game evennia/evennia evennia $@```
None
=> --gamedir doesn't work as GAMEDIR gets overwritten

evennia/accounts/accounts.py
Python f-strings don't work with i18n (gettext). Refactor to use `.format` instead.
Bux Fixing
Similar issue already discussed in 2021 on [Discord](https://discordapp.com/channels/246323978879107073/246323978879107073/885436654825902090)
In that file (accounts.py) are also some Strings that are not marked for translation (`"..."` instead of `_("...")`). Is that intentionally? For example `"You are already puppeting this object."` on [Line 474](https://github.com/evennia/evennia/blob/main/evennia/accounts/accounts.py#L474). That one was at some point translated (see e.g. current german (de) PO file) but does not get pulled into the PO file on `evennia makemessages` at the moment.
=> Don't use f-string for i18n

evennia/accounts/accounts.py
The formating of the strings via `.format()` has to be called "after" translation via `gettext()`.
`_("...").format()` instead of `_("...".format())`
Otherwise the string will not be translated because at runtime the format method returns a String with already filled out content which then does not match any translation message via gettext().
Bux fixing.
similar discussion: [Stackoverflow: Translating formatted strings in Django not working](https://stackoverflow.com/questions/44957261/translating-formatted-strings-in-django-not-working)
=> fix format strings for i18n

evennia/contrib/tutorials/tutorial_world/rooms.py
Hi all, I noticed this while checking out the tutorial world. Seems like a bug to me: 
`random.random()` returns a float in the [0, 1) range, meaning `random.random() < 80` will always be true.
=> Fix tutorial bridge room

evennia/help/models.py, evennia/typeclasses/attributes.py, evennia/typeclasses/models.py
Fix:
```
> evennia migrate
/home/jake/evennia/evennia/evennia/typeclasses/models.py:951: SyntaxWarning: invalid escape sequence '\w'
"""
/home/jake/evennia/evennia/evennia/typeclasses/models.py:991: SyntaxWarning: invalid escape sequence '\w'
"""
/home/jake/evennia/evennia/evennia/typeclasses/models.py:1029: SyntaxWarning: invalid escape sequence '\w'
"""
/home/jake/evennia/evennia/evennia/typeclasses/models.py:1068: SyntaxWarning: invalid escape sequence '\w'
"""
/home/jake/evennia/evennia/evennia/typeclasses/attributes.py:1474: SyntaxWarning: invalid escape sequence '\@'
"""
/home/jake/evennia/evennia/evennia/help/models.py:209: SyntaxWarning: invalid escape sequence '\w'
"""
/home/jake/evennia/evennia/evennia/help/models.py:245: SyntaxWarning: invalid escape sequence '\w'
""" …
```
=> Resolving SyntaxWarnings for Py 3.13

evennia/commands/default/admin.py, evennia/commands/default/building.py, evennia/comms/comms.py, evennia/help/filehelp.py
fix these warnings:
```
Superuser created successfully.
/Users/jake/Evennia/evennia/evennia/comms/comms.py:817: SyntaxWarning: invalid escape sequence '\w'
"""
/Users/jake/Evennia/evennia/evennia/comms/comms.py:853: SyntaxWarning: invalid escape sequence '\w'
"""
/Users/jake/Evennia/evennia/evennia/comms/comms.py:889: SyntaxWarning: invalid escape sequence '\w'
"""
/Users/jake/Evennia/evennia/evennia/commands/default/admin.py:215: SyntaxWarning: invalid escape sequence '\.'
ipregex = ban.replace(".", "\.")
/Users/jake/Evennia/evennia/evennia/commands/default/building.py:3252: SyntaxWarning: invalid escape sequence '\s'
sorted(dbref(x, False) for x in re.split("[-\s]+", self.rhs.strip()))
/Users/jake/Evennia/evennia/evennia/help/filehelp.py:131: SyntaxWarning: invalid escape sequence '\w' …
```
=> fix SyntaxWarnings

evennia/typeclasses/models.py
I realized a (for me) unexpected behavior. If there are `AttributeProperty`s (with default values) in a parent typeclass, they won't be initialized at object creation if they are not (yet) used in the class . Just the `AttributeProperty`s from the "direct" typeclass of the object are set at object creation. 
Therefore one could not view those attributes ingame via `examine <obj>` or `set <obj>/<attr>`.
The method `init_evennia_properties()` loops through all properties of the typeclass but not of the parent typeclasses. 
With the help of "exsavio" (Discord) we changed that to also include parent classes.
Bug fixing.
Discussion about that finding on [Discord](https://discord.com/channels/246323978879107073/980878618685231194/1354440454367740074)
=> Let init_evennia_properties() also init properties of parent classes

evennia/objects/objects.py, evennia/typeclasses/models.py
Marked some more strings for translation so you don't need to overwrite whole methods of e.g. `DefaultObject` in your own game just to translate the simple messages defined there (without changing the behavior of the methods).
**Disclaimer:** [get_numbered_name()](https://github.com/evennia/evennia/blob/main/evennia/objects/objects.py#L1674) is impossible to translate via gettext because it uses [inflect](https://pypi.org/project/inflect/) for inflection (only works in english). So you still need to overwrite this method in your foreign language.
Internationalization
=> Add internationalization (i18n via gettext)

pyproject.toml
Updates to the `pyproject.toml` file to configure the `ruff` tool for linting and code formatting. The changes mirror current `black` tool configuration.
Configuration updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R173-R189): Added `ruff` tool configuration, including exclusions for directories such as `/.eggs/`, `/.git/`, `/.tox/`, and others, and set the line length to 100 characters.
Resolves #3782
=> Add exclusions and line-length for ruff lint support

evennia/contrib/game_systems/turnbattle/tb_basic.py
Original scripts.add was (self.command_handler_class), which does not exist. It should be (self.combat_handler_class)
This fix updates that only.
=> Update tb_basic.py to resolve type in scripts caller
